buildscript {
    ext.kotlin_version = '2.1.20'
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.afterEvaluate {
        if (project.name == 'pusher_channels_flutter') {
            project.android {
                compileSdkVersion 35
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    project.plugins.withId('com.android.library') {
        if (project.name == 'firebase_core') {
            project.android {
                namespace 'io.flutter.plugins.firebase.core'
            }
        } else if (project.name == 'just_audio') {
            project.android {
                namespace 'com.ryanheise.just_audio'
            }
        } else if (project.name == 'pusher_beams_android') {
            project.android {
                namespace 'com.pusher.pusher_beams'
            }
        } else if (project.name == 'wakelock') {
            project.android {
                namespace 'creativemaybeno.wakelock'
            }
        } else if (project.name == 'pusher_channels_flutter') {
            project.android {
                namespace 'com.pusher.channels_flutter'
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
