// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_4rCTW1k8PZ90yGmyhUyG9reXuPURiw',
    appId: '1:985118071013:web:8e12b0d28062389e779c0c',
    messagingSenderId: '985118071013',
    projectId: 'funmoments-project',
    authDomain: 'funmoments-project.firebaseapp.com',
    storageBucket: 'funmoments-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWtpgMPHD0FE_cqiA3Md9IwSjj6MZK6rM',
    appId: '1:985118071013:android:4bc1cf8c1a2583e7779c0c',
    messagingSenderId: '985118071013',
    projectId: 'funmoments-project',
    storageBucket: 'funmoments-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsH64P-uLJoH7dVVyO56YqXKh1VZdVv3c',
    appId: '1:985118071013:ios:4740b3d99eaf1bd1779c0c',
    messagingSenderId: '985118071013',
    projectId: 'funmoments-project',
    storageBucket: 'funmoments-project.appspot.com',
    iosBundleId: 'com.sa.funmomments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_4rCTW1k8PZ90yGmyhUyG9reXuPURiw',
    appId: '1:985118071013:web:4cf09f418d4f2d0e779c0c',
    messagingSenderId: '985118071013',
    projectId: 'funmoments-project',
    authDomain: 'funmoments-project.firebaseapp.com',
    storageBucket: 'funmoments-project.appspot.com',
  );
}
