var appStrings = {
  "welcome": "welcome",
  "Browse categories": "Browse categories",
  "All categories": "All categories",
  "Top services": "Top services",
  "Recently listed": "Recently listed",
  "See all": "See all",
  "Home": "Home",
  "Discover": "Discover",
  "Bookings": "Bookings",
  "Orders": "Orders",
  "Save": "Save",
  "Saved": "Saved",
  "Search": "Search",
  "Profile": "Profile",
  "Settings": "Settings",
  "Search services": "Search services",
  "Date": "Date",
  "Schedule": "Schedule",
  "Billed": "Billed",
  "My orders": "My orders",
  "Seller Details": "Seller Details",
  "Name": "Name",
  "Email": "Email",
  "Phone": "Phone",
  "Post Code": "Post Code",
  "Address": "Address",
  "Date & Schedule": "Date & Schedule",
  "Amount Details": "Amount Details",
  "Package fee": "Package fee",
  "Extra service": "Extra service",
  "Subtotal": "Subtotal",
  "Tax": "Tax",
  "Total": "Total",
  "Payment status": "Payment status",
  "Order Status": "Order Status",
  "Saved Services": "Saved Services",
  "Starts from": "Starts from",
  "No result found": "No result found",
  "Pending orders": "Pending orders",
  "Active orders": "Active orders",
  "Completed orders": "Completed orders",
  "Total orders": "Total orders",
  "City": "City",
  "Area": "Area",
  "Country": "Country",
  "Support ticket": "Support ticket",
  "Edit profile": "Edit profile",
  "Change Password": "Change Password",
  "Logout": "Logout",
  "Create": "Create",
  "No ticket": "No ticket",
  "All services": "All services",
  "All": "All",
  "Highest price": "Highest price",
  "Lowest price": "Lowest price",
  "Latest service": "Latest service",
  "Full Name": "Full Name",
  "About": "About",
  "Your Address": "Your Address",
  "Choose country": "Choose country",
  "Choose city": "Choose city",
  "Choose Area": "Choose Area",
  "Service Name": "Service Name",
  "Our Package": "Our Package",
  "Orders Completed": "Orders Completed",
  "Seller ratings": "Seller ratings",
  "Overview": "Overview",
  "About Seller": "About Seller",
  "Review": "Review",
  "Benefits of premium Package": "Benefits of premium Package",
  "Benefits of the premium package": "Benefits of the premium package",
  "FAQ": "FAQ",
  "Book appointment": "Book appointment",
  "Personalize": "Personalize",
  "Service personalization": "Service personalization",
  "Next": "Next",
  "What's included": "What's included",
  "Add Extra": "Add Extra",
  "Benefits of the package": "Benefits of the package",
  "Benefits of the Package": "Benefits of the Package",
  "Available Schedules": "Available Schedules",
  "Available time": "Available time",
  "No schedule available on this date": "No schedule available on this date",
  "Choose Location": "Choose Location",
  "Booking information's": "Booking information's",
  "Booking confirmation": "Booking confirmation",
  "Booking Details": "Booking Details",
  "Location": "Location",
  "Swipe up for details": "Swipe up for details",
  "Proceed to payment": "Proceed to payment",
  "Collapse details": "Collapse details",
  "Appointment package service": "Appointment package service",
  "Extra service fee": "Extra service fee",
  "Coupon": "Coupon",
  "Coupon code": "Coupon code",
  "Enter coupon code": "Enter coupon code",
  "Apply": "Apply",
  "Payment": "Payment",
  "Total payable": "Total payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Pay & confirm order": "Pay & confirm order",
  "Payment successful": "Payment successful",
  "Book a DJ": "Book a DJ",
  "Rent Party Equipment": "Rent Party Equipment",
  "Discover your next event": "Discover your next event",
  "Premium entertainment for Riyadh and Saudi Arabia":
      "Premium entertainment for Riyadh and Saudi Arabia",
  "DJ booking": "DJ booking",
  "Equipment rental": "Equipment rental",
  "Riyadh nights": "Riyadh nights",
  "Everything you need for music and events":
      "Everything you need for music and events",
  "Discover your next moment": "Discover your next moment",
  "Search premium services, providers, and bookings":
      "Search premium services, providers, and bookings",
  "Welcome back": "Welcome back",
  "Login to continue your FUN MOMENT journey":
      "Login to continue your FUN MOMENT journey",
  "Create your account to book or sell services.":
      "Create your account to book or sell services.",
  "Login or register to unlock your FUN MOMENT profile":
      "Login or register to unlock your FUN MOMENT profile",
  "Order status": "Order status",
  "Are you sure?": "Are you sure?",
  "Cancel": "Cancel",
  "Welcome back! Login": "Welcome back! Login",
  "Password": "Password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Enter password": "Enter password",
  "Do not have an account": "Do not have an account",
  "Register": "Register",
  "Or": "Or",
  "Login with google": "Login with google",
  "Login with facebook": "Login with facebook",
  "Register to join us": "Register to join us",
  "Enter your full name": "Enter your full name",
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  "Continue": "Continue",
  "Already have an account": "Already have an account",
  "Repeat password": "Repeat password",
  "Phone number": "Phone number",
  "Reset password": "Reset password",
  "Enter the email you used to create account and we well send information for resetting password":
      "Enter the email you used to create account and we well send information for resetting password",
  "Enter email": "Enter email",
  "Send instructions": "Send instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "Enter the 4 digit code we sent to your email in order to reset password",
  "Did not receive": "Didn't receive",
  "Send again": "Send again",
  "Something went wrong": "Something went wrong",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Have an account": "Have an account",
  'Menu': 'Menu',
  "My jobs": "My jobs",
  "Job requests": "Job requests",
  "Support Ticket": "Support Ticket",
  "Wallet": "Wallet",
  "My report list": "My report list",
  "Edit Profile": "Edit Profile",
  "Change password": "Change password",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  "Please enter your password": "Please enter your password",
  "Repeat new password": "Repeat new password",
  "Please retype your password": "Please retype your password",
  "Retype new password": "Retype new password",
  "Make sure you repeated new password correctly":
      "Make sure you repeated new password correctly",
  "Password changed successfully": "Password changed successfully",
  "Please turn on your internet connection":
      "Please turn on your internet connection",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "Your entered the otp correctly but something went wrong. Please try again later",
  "Otp didn't match": "Otp didn't match",
  "Otp is null": "Otp is null",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "Didn't get any user info after google sign in. visit google sign in service file",
  "Login successful": "Login successful",
  "Invalid Email or Password": "Invalid Email or Password",
  "Password didn't match": "Password didn't match",
  "Password updated successfully": "Password updated successfully",
  "Registration successful": "Registration successful",
  "Otp send failed": "Otp send failed",
  "You already applied this coupon": "You already applied this coupon",
  "Please enter a valid coupon": "Please enter a valid coupon",
  "Order placed successfully": "Order placed successfully",
  "Failed to make payment status successful":
      "Failed to make payment status successful",
  "Check your internet connection and try again":
      "Check your internet connection and try again",
  "You have received an order from": "You have received an order from",
  "You must select an image": "You must select an image",
  "You must select category & subcategory":
      "You must select category & subcategory",
  "Job posted successfully": "Job posted successfully",
  "Job updated successfully": "Job updated successfully",
  "Only zip file is supported": "Only zip file is supported",
  "Please check your internet connection":
      "Please check your internet connection",
  "New job chat message": "New job chat message",
  "Hiring successful": "Hiring successful",
  "Job deleted successfully": "Job deleted successfully",
  "New chat message": "New chat message",
  "You don't have enough wallet balance":
      "You don't have enough wallet balance",
  "Payment cancelled": "Payment cancelled",
  "Service Personalization": "Service Personalization",
  "Information's": "Information's",
  "Booking Confirmations": "Booking Confirmations",
  "Select Country": "Select Country",
  "Select State": "Select State",
  "Select Area": "Select Area",
  "review posted successfully": "Review posted successfully",
  "Report submitted": "Report submitted",
  "accepted your order extra request": "accepted your order extra request",
  "Error accepting order extra": "Error accepting order extra",
  "Error declining order extra": "Error declining order extra",
  "accepted your order completion request":
      "accepted your order completion request",
  "Profile updated successfully": "Profile updated successfully",
  "Wallet deposit success": "Wallet deposit success",
  "You must enter an amount": "You must enter an amount",
  "Please enter a valid amount": "Please enter a valid amount",
  "Ticket created successfully": "Ticket created successfully",
  "Welcome": "Welcome",
  "Create Job": "Create Job",
  "Please enter a title": "Please enter a title",
  "Title": "Title",
  "Budget": "Budget",
  "Please enter your budget": "Please enter your budget",
  "Description": "Description",
  "End date": "End date",
  "Create job": "Create job",
  "You must enter a valid budget": "You must enter a valid budget",
  "Choose states": "Choose states",
  "Category": "Category",
  "Sub Category": "Sub Category",
  "Ratings": "Ratings",
  "Sort By": "Sort By",
  'Select Category': 'Select Category',
  'Select Subcategory': 'Select Subcategory',
  "Highest Price": "Highest Price",
  "Lowest Price": "Lowest Price",
  "Latest Service": "Latest Service",
  "Offline": "Offline",
  "Online": "Online",
  "Job Requests": "Job Requests",
  "View details": "View details",
  "Conversation": "Conversation",
  "Hire now": "Hire now",
  'Your offer': 'Your offer',
  "Seller offer": "Seller offer",
  "No request found": "No request found",
  'Deadline': 'Deadline',
  "Balance": "Balance",
  "History": "History",
  "Gateway": "Gateway",
  "Amount": "Amount",
  "Payment Status": "Payment Status",
  'No history found': 'No history found',
  "Total Payable": "Total Payable",
  "Deposit Amount": "Deposit Amount",
  "Enter deposit amount": "Enter deposit amount",
  "You must agree with the terms and conditions to place the order":
      "You must agree with the terms and conditions to place the order",
  "Pay & Confirm": "Pay & Confirm",
  "I agree with terms and conditions": "I agree with terms and conditions",
  "Reports": "Reports",
  "Report id": "Report id",
  'Chat admin': 'Chat admin',
  "Order id": "Order id",
  "No Report": "No Report",
  "Please write a message first": "Please write a message first",
  "Write message": "Write message",
  "Remember Me": "Remember Me",
  "Don't have account?": "Don't have account?",
  "Login with Google": "Login with Google",
  "Login with Facebook": "Login with Facebook",
  "Full name": "Full name",
  "Please enter your full name": "Please enter your full name",
  "Username": "Username",
  "Please enter your username": "Please enter your username",
  "Enter phone number": "Enter phone number",
  "Have an account?": "Have an account?",
  "Sign Up": "Sign Up",
  "Choose area": "Choose area",
  "Book Now": 'Book Now',
  "Recent jobs": 'Recent jobs',
  "Top booked services": 'Top booked services',
  "About seller": 'About seller',
  "Order Completed": 'Order Completed',
  "From": 'From',
  "Order Completion Rate": 'Order Completion Rate',
  "Seller Since": 'Seller Since',
  "Orders completed": 'Orders completed',
  "Seller Ratings": 'Seller Ratings',
  "Watch video": 'Watch video',
  "Book Appointment": 'Book Appointment',
  "What is included": 'What is included',
  "Add extras": 'Add extras',
  "Booking Information": 'Booking Information',
  "Details": 'Details',
  "Booking details": 'Booking details',
  "Package Fee": 'Package Fee',
  "Extra Service Fee": 'Extra Service Fee',
  "Extra Service": 'Extra Service',
  "My Orders": 'My Orders',
  "You can not cancel this order": 'You can not cancel this order',
  "No active order": 'No active order',
  "Leave feedback": 'Leave feedback',
  "Cancel order": 'Cancel order',
  "Report to admin": 'Report to admin',
  "Order Details": 'Order Details',
  "Payment method": 'Payment method',
  "Pay now": 'Pay now',
  "Saved services": 'Saved services',
  "No service saved": 'No service saved',
  "Payment failed!": 'Payment failed!',
  "Go to home": 'Go to home',
  "Personal information's": "Personal information's",
  "Your address": 'Your address',
  "Time": 'Time',
  "Active": 'Active',
  "Pending": 'Pending',
  "pending": 'pending',
  "Delivered": 'Delivered',
  "Completed": 'Completed',
  "complete": 'complete',
  "Cancelled": 'Cancelled',
  "Unknown": 'Unknown',
  "Decline history": 'Decline history',
  "Decline reason": 'Decline reason',
  "Buyer details": 'Buyer details',
  "Complete Request": 'Complete Request',
  "Declined": 'Declined',
  "Order completed": 'Order completed',
  "Seller requested to mark this order complete":
      'Seller requested to mark this order complete',
  "Decline": 'Decline',
  "Accept": 'Accept',
  "Skip": 'Skip',
  "Job Request ID": 'Job Request ID',
  "Attachment": 'Attachment',
  "Conversations": 'Conversations',
  "You don't have any active conversation":
      "You don't have any active conversation",
  "Write message...": "Write message...",
  "Edit": 'Edit',
  "Delete": 'Delete',
  "On/Off": 'On/Off',
  "Urgent": 'Urgent',
  "High": 'High',
  "Medium": 'Medium',
  "Low": 'Low',
  "Please enter ticket title": 'Please enter ticket title',
  "Ticket title": 'Ticket title',
  "Please explain your problem": 'Please explain your problem',
  "Create ticket": 'Create ticket',
  "You don't have any active order": "You don't have any active order",
  "open": 'open',
  "close": 'close',
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "Enter the email you used to create account and we'll send instruction for resetting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "All Categories": 'All Categories',
  "Already hired a seller for this job.":
      'Already hired a seller for this job.',
  "Enter the 4 digit code we sent to to your email in order to reset password":
      'Enter the 4 digit code we sent to to your email in order to reset password',
  "OR": 'OR',
  "Sign in": 'Sign in',
  "Search country": 'Search country',
  "Verify Email": 'Verify Email',
  "by": 'by',
  "Star": 'Star',
  "Write a review": 'Write a review',
  "How was the service?": "How was the service?",
  "Post review": "Post review",
  "Report": "Report",
  "What went wrong?": "What went wrong?",
  "Write the issue": "Write the issue",
  "Submit Report": "Submit Report",
  "You must write something to submit report":
      "You must write something to submit report",
  "Yes": "Yes",
  "No": "No",
  "Load Failed": "Load Failed",
  "Release to load more": "Release to load more",
  "No more Data": "No more Data",
  "Edit Job": "Edit Job",
  "Edit job": "Edit job",
  "Select area": "Select area",
  "New password": "New password",
  "Enter new password": "Enter new password",
  "No service available": "No service available",
  "No service available in your area": "No service available in your area",
  "No Date Created": "No Date Created",
  "No Schedule Created": "No Schedule Created",
  "Show Description": "Show Description",
  "Hide Description": "Hide Description",
  "Post code": "Post code",
  "All Services": "All Services",
  "Select Date": "Select Date",
  "Support tickets": "Support tickets",
  "Priority": "Priority",
  "Order number": "Order number",
  "Success": "Success",
  "Order extra accepted": "Order extra accepted",
  "Hired successfully": "Hired successfully",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "Enter the 4 digit code we sent to to your email in order verify your email":
      "Enter the 4 digit code we sent to to your email in order verify your email",
  "Describe why you want to decline the request":
      "Describe why you want to decline the request",
  "You must enter decline reason": "You must enter decline reason",
  "Press again to exit": "Press again to exit",
  "Order complete request successfully approved.":
      "Order complete request successfully approved.",
  "No city found": "No city found",
  "Search state": "Search state",
  "Select City": "Select City",
  "No country found": "No country found",
  "No area found": "No area found",
  "Search area": "Search area",
  "Choose image": "Choose image",
  "Unit price": "Unit price",
  "Quantity": "Quantity",
  "declined your order extra request": "declined your order extra request",
  "Order Id": "Order Id",
  "Decline Success": "Decline Success",
  "Extra Service Not Found": "Low",
  "No date found": "No date found",
  "Delete Account": "Delete Account",
  "active": "active",
  "delivered": "delivered",
  "cancelled": "cancelled",
  "Order Not Found": "Order Not Found",
  "Support Ticket Created Success": "Support Ticket Created Success",
  "Message:": "Message:",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.":
      "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.",
  "Payment cancelled!": "Payment cancelled!",
  "Payment has been expired.": "Payment has been expired.",
  "Payment has been cancelled.": "Payment has been cancelled.",
  "Welcome to Fun Moments": "Welcome to Fun Moments",
  "Hello! 👋": "Hello! 👋",
  "You'll have to login/register to edit or see your profile info.":
      "You'll have to login/register to edit or see your profile info.",
  "Sign-In/Sign-Up": "Sign-In/Sign-Up",
  "Sign in with Apple": "Sign in with Apple",
  "Apple id revoked successfully": "Apple id revoked successfully",
  "Apple id revoke failed": "Apple id revoke failed",
  "Please provide maximum filter price amount":
      "Please provide maximum filter price amount",
  "Apply Filter": "Apply Filter",
  "Clear Filter": "Clear Filter",
  "Select child-category": "Select child-category",
  "Child-category": "Child-category",
  "Filter": "Filter",
  "Reset": "Reset",
  "Type": "Type",
  "Distance": "Distance",
  "Search Location": "Search Location",
  "No location found": "No location found",
  "Chose location": "Chose location",
  "Choosing current location": "Choosing current location",
  "Failed to get location": "Failed to get location",
  "Location set successfully": "Location set successfully",
  "Choose Current Location": "Choose Current Location",
  "Email or username": "Email or username",
  "No message found": "No message found",
  "Order": "Order",
  "No results found": "No results found",
  "Enter your post code": "Enter your post code",
  "Short description": "Short description",
  "description": "description",
  "Delete account": "Delete account",
  "Choose Reason": "Choose Reason",
  "Vacation": "Vacation",
  "Personal reason": "Personal reason",
  "Price": "Price",
  "Min": "Min",
  "Max": "Max",
  "Best Selling Service": "Best Selling Service",
  "Popular Service": "Popular Service",
  "Featured Service": "Featured Service",
  "Select subcategory": "Select subcategory",
  "Subcategory": "Subcategory",
  "Select category": "Select category"
};

var translations = {
  "welcome": "أهلاً بك",
  "Browse categories": "تصفح الفئات",
  "All categories": "جميع الفئات",
  "Top services": "أفضل الخدمات",
  "Recently listed": "المضافة حديثاً",
  "See all": "عرض الكل",
  "Home": "الرئيسية",
  "Orders": "الطلبات",

  //here
  "Order": "الطلب",
  "Enter your post code": "أدخل رمز البريد الخاص بك",
  "Short description": "وصف مختصر",
  "description": "الوصف",
  "Search": "البحث",
  "Reset": "إعادة تعيين",
  "Location": "الموقع",
  "Filter": "التصفية",
  "No results found": "لا توجد نتائج",
  "Delete account": "حذف الحساب",
  "Choose Reason": "اختر السبب",
  "Vacation": "إجازة",
  "Personal reason": "سبب شخصي",
  "Price": "السعر",
  "Min": "الحد الأدنى",
  "Max": "الحد الأقصى",
  "Best Selling Service": "الخدمة الأكثر مبيعًا",
  "Popular Service": "الخدمة الشهيرة",
  "Featured Service": "الخدمة المميزة",
  "Select subcategory": "تحديد الفئة الفرعية",
  "Subcategory": "الفئة الفرعية",
  "Select category": "تحديد الفئة",

  //here
  "Save": "حفظ",
  "Saved": "تم الحفظ",
  "Settings": "الإعدادات",
  "Search services": "بحث عن خدمات",
  "Date": "التاريخ",
  "Schedule": "الجدول",
  "Billed": "مفوتر",
  "My orders": "طلباتي",
  "Seller Details": "تفاصيل البائع",
  "Name": "الاسم",
  "Email": "البريد الإلكتروني",
  "Phone": "الهاتف",
  "Post Code": "الرمز البريدي",
  "Address": "العنوان",
  "Date & Schedule": "التاريخ والجدول",
  "Amount Details": "تفاصيل المبلغ",
  "Package fee": "رسوم الباقة",
  "Extra service": "خدمة إضافية",
  "Subtotal": "المجموع الفرعي",
  "Tax": "الضريبة",
  "Total": "الإجمالي",
  "Payment status": "حالة الدفع",
  "Order Status": "حالة الطلب",
  "Saved Services": "الخدمات المحفوظة",
  "Starts from": "يبدأ من",
  "No result found": "لا توجد نتائج",
  "Pending orders": "الطلبات المعلقة",
  "Active orders": "الطلبات النشطة",
  "Completed orders": "الطلبات المكتملة",
  "Total orders": "إجمالي الطلبات",
  "City": "المدينة",
  "Area": "المنطقة",
  "Country": "الدولة",
  "Support ticket": "تذكرة الدعم",
  "Edit profile": "تعديل الملف الشخصي",
  "Change Password": "تغيير كلمة المرور",
  "Logout": "تسجيل الخروج",
  "Create": "إنشاء",
  "No ticket": "لا توجد تذكرة",
  "All services": "جميع الخدمات",
  "All": "الكل",
  "Highest price": "السعر الأعلى",
  "Lowest price": "السعر الأدنى",
  "Latest service": "أحدث خدمة",
  "Full Name": "الاسم الكامل",
  "About": "عن",
  "Your Address": "عنوانك",
  "Choose country": "اختر الدولة",
  "Choose city": "اختر المدينة",
  "Choose Area": "اختر المنطقة",
  "Service Name": "اسم الخدمة",
  "Our Package": "الباقة الخاصة بنا",
  "Orders Completed": "الطلبات المكتملة",
  "Seller ratings": "تقييمات البائع",
  "Overview": "نظرة عامة",
  "About Seller": "عن البائع",
  "Review": "مراجعة",
  "Benefits of premium Package": "مزايا الباقة المميزة",
  "Benefits of the premium package": "مزايا الباقة المميزة",
  "FAQ": "الأسئلة الشائعة",
  "Book appointment": "حجز موعد",
  "Personalize": "تخصيص",
  "Service personalization": "تخصيص الخدمة",
  "Next": "التالي",
  "What's included": "ما الذي يشمله",
  "Add Extra": "إضافة إضافي",
  "Benefits of the package": "مزايا الباقة",
  "Benefits of the Package": "مزايا الباقة",
  "Available Schedules": "الجداول المتاحة",
  "Available time": "الوقت المتاح",
  "No schedule available on this date": "لا توجد جداول متاحة في هذا التاريخ",
  "Choose Location": "اختر الموقع",
  "Booking information's": "معلومات الحجز",
  "Booking confirmation": "تأكيد الحجز",
  "Booking Details": "تفاصيل الحجز",
  "Swipe up for details": "اسحب لأعلى للتفاصيل",
  "Proceed to payment": "المتابعة إلى الدفع",
  "Collapse details": "طي التفاصيل",
  "Appointment package service": "خدمة حزمة المواعيد",
  "Extra service fee": "رسوم الخدمة الإضافية",
  "Coupon": "كوبون",
  "Coupon code": "كود الكوبون",
  "Enter coupon code": "أدخل كود الكوبون",
  "Apply": "تطبيق",
  "Payment": "الدفع",
  "Total payable": "المبلغ الإجمالي المستحق",
  "Choose payment method": "اختر طريقة الدفع",
  "Choose images": "اختر الصور",
  "I agree with the terms and conditions": "أوافق على الشروط والأحكام",
  "Pay & confirm order": "ادفع وأكد الطلب",
  "Payment successful": "تم الدفع بنجاح",
  "Book a DJ": "احجز دي جي",
  "Rent Party Equipment": "استأجر معدات الحفلات",
  "Discover your next event": "اكتشف لحظتك التالية",
  "Premium entertainment for Riyadh and Saudi Arabia":
      "ترفيه مميز للرياض والسعودية",
  "DJ booking": "حجز دي جي",
  "Equipment rental": "تأجير المعدات",
  "Riyadh nights": "ليالي الرياض",
  "Everything you need for music and events":
      "كل ما تحتاجه للموسيقى والمناسبات",
  "Discover your next moment": "اكتشف لحظتك التالية",
  "Search premium services, providers, and bookings":
      "ابحث عن الخدمات المميزة ومقدمي الخدمة والحجوزات",
  "Welcome back": "مرحبًا بعودتك",
  "Login to continue your FUN MOMENT journey":
      "سجل الدخول لمتابعة رحلتك مع FUN MOMENT",
  "Create your account to book or sell services.":
      "أنشئ حسابك لحجز أو بيع الخدمات.",
  "Login or register to unlock your FUN MOMENT profile":
      "سجل الدخول أو أنشئ حسابك لفتح ملف FUN MOMENT الخاص بك",
  "Order status": "حالة الطلب",
  "Are you sure?": "هل أنت متأكد؟",
  "Cancel": "إلغاء",
  "Welcome back! Login": "مرحبًا بعودتك! تسجيل الدخول",
  "Password": "كلمة المرور",
  "Remember me": "تذكرني",
  "Forgot Password?": "نسيت كلمة المرور؟",
  "Login": "تسجيل الدخول",
  "Enter password": "أدخل كلمة المرور",
  "Do not have an account": "ليس لديك حساب",
  "Register": "تسجيل",
  "Or": "أو",
  "Login with google": "تسجيل الدخول باستخدام جوجل",
  "Login with facebook": "تسجيل الدخول باستخدام فيسبوك",
  "Register to join us": "سجل للانضمام إلينا",
  "Enter your full name": "أدخل اسمك الكامل",
  "Enter your username": "أدخل اسم المستخدم الخاص بك",
  "Enter your email": "أدخل بريدك الإلكتروني",
  "Continue": "استمر",
  "Already have an account": "هل لديك حساب بالفعل",
  "Repeat password": "أعد كتابة كلمة المرور",
  "Phone number": "رقم الهاتف",
  "Reset password": "إعادة تعيين كلمة المرور",
  "Enter the email you used to create account and we well send information for resetting password":
      "أدخل البريد الإلكتروني الذي استخدمته لإنشاء الحساب وسنرسل المعلومات لإعادة تعيين كلمة المرور",
  "Enter email": "أدخل البريد الإلكتروني",
  "Send instructions": "أرسل التعليمات",
  "Enter the 4 digit code": "أدخل الرمز المكون من 4 أرقام",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني لإعادة تعيين كلمة المرور",
  "Didn't receive": "لم تتلقى",
  "Send again": "أرسل مرة أخرى",
  "Something went wrong": "حدث خطأ ما",
  "Please wait while the profile is updating":
      "يرجى الانتظار أثناء تحديث الملف الشخصي",
  "Please enter your email": "الرجاء إدخال بريدك الإلكتروني",
  "Please enter post code": "الرجاء إدخال الرمز البريدي",
  "You must select a state and area": "يجب عليك اختيار ولاية ومنطقة",
  "Address field is required": "حقل العنوان مطلوب",
  "Phone field is required": "حقل الهاتف مطلوب",
  "Updating profile...It may take few seconds":
      "جارٍ تحديث الملف الشخصي... قد يستغرق ذلك بضع ثوان",
  "You must agree with the terms and conditions to register":
      "يجب أن توافق على الشروط والأحكام للتسجيل",
  "Password did not match": "كلمة المرور غير متطابقة",
  "Password must be at least 6 characters":
      "يجب أن تكون كلمة المرور على الأقل 6 أحرف",
  "Have an account": "لديك حساب",
  "Menu": "القائمة",
  "My jobs": "وظائفي",
  "Job requests": "طلبات العمل",
  "Support Ticket": "تذكرة الدعم",
  "Wallet": "المحفظة",
  "My report list": "قائمة تقاريري",
  "Edit Profile": "تعديل الملف الشخصي",
  "Change password": "تغيير كلمة المرور",
  "Enter current password": "أدخل كلمة المرور الحالية",
  "Enter your current password": "أدخل كلمة المرور الحالية الخاصة بك",
  "Please enter your password": "الرجاء إدخال كلمة المرور الخاصة بك",
  "Repeat new password": "أعد كتابة كلمة المرور الجديدة",
  "Please retype your password": "الرجاء إعادة كتابة كلمة المرور الخاصة بك",
  "Retype new password": "أعد كتابة كلمة المرور الجديدة",
  "Make sure you repeated new password correctly":
      "تأكد من تكرار كلمة المرور الجديدة بشكل صحيح",
  "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Please turn on your internet connection": "يرجى تشغيل اتصال الإنترنت",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "لقد أدخلت رمز التحقق بشكل صحيح ولكن حدث خطأ ما. الرجاء المحاولة لاحقاً",
  "Otp didn't match": "رمز التحقق غير مطابق",
  "Otp is null": "رمز التحقق فارغ",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "لم يتم الحصول على أي معلومات مستخدم بعد تسجيل الدخول باستخدام جوجل. قم بزيارة ملف خدمة تسجيل الدخول بجوجل",
  "Login successful": "تسجيل الدخول ناجح",
  "Invalid Email or Password": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "Password didn't match": "كلمة المرور غير متطابقة",
  "Password updated successfully": "تم تحديث كلمة المرور بنجاح",
  "Registration successful": "تم التسجيل بنجاح",
  "Otp send failed": "فشل إرسال رمز التحقق",
  "You already applied this coupon": "لقد قمت بالفعل بتطبيق هذا الكوبون",
  "Please enter a valid coupon": "الرجاء إدخال كوبون صالح",
  "Order placed successfully": "تم تقديم الطلب بنجاح",
  "Failed to make payment status successful": "فشل في جعل حالة الدفع ناجحة",
  "Check your internet connection and try again":
      "تحقق من اتصالك بالإنترنت وحاول مرة أخرى",
  "You have received an order from": "لقد تلقيت طلباً من",
  "You must select an image": "يجب عليك اختيار صورة",
  "You must select category & subcategory":
      "يجب عليك اختيار الفئة والفئة الفرعية",
  "Job posted successfully": "تم نشر الوظيفة بنجاح",
  "Job updated successfully": "تم تحديث الوظيفة بنجاح",
  "Only zip file is supported": "يدعم فقط ملف مضغوط",
  "Please check your internet connection": "يرجى التحقق من اتصالك بالإنترنت",
  "New job chat message": "رسالة دردشة وظيفة جديدة",
  "Hiring successful": "تم التوظيف بنجاح",
  "Job deleted successfully": "تم حذف الوظيفة بنجاح",
  "New chat message": "رسالة دردشة جديدة",
  "You don't have enough wallet balance": "رصيد المحفظة لديك غير كافٍ",
  "Payment cancelled": "تم إلغاء الدفع",
  "Service Personalization": "تخصيص الخدمة",
  "Information's": "المعلومات",
  "Booking Confirmations": "تأكيدات الحجز",
  "Select Country": "اختر الدولة",
  "Select State": "اختر الولاية",
  "Select Area": "اختر المنطقة",
  "review posted successfully": "تم نشر المراجعة بنجاح",
  "Report submitted": "تم تقديم التقرير",
  "accepted your order extra request": "تم قبول طلبك الإضافي",
  "Error accepting order extra": "خطأ في قبول الطلب الإضافي",
  "Error declining order extra": "خطأ في رفض الطلب الإضافي",
  "accepted your order completion request": "تم قبول طلب إكمال طلبك",
  "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
  "Wallet deposit success": "نجاح إيداع المحفظة",
  "You must enter an amount": "يجب عليك إدخال مبلغ",
  "Please enter a valid amount": "يرجى إدخال مبلغ صالح",
  "Ticket created successfully": "تم إنشاء التذكرة بنجاح",
  "Welcome": "مرحبا",
  "Create Job": "إنشاء وظيفة",
  "Please enter a title": "الرجاء إدخال عنوان",
  "Title": "العنوان",
  "Budget": "الميزانية",
  "Please enter your budget": "الرجاء إدخال ميزانيتك",
  "Description": "الوصف",
  "End date": "تاريخ الانتهاء",
  "Create job": "إنشاء وظيفة",
  "You must enter a valid budget": "يجب عليك إدخال ميزانية صحيحة",
  "Choose states": "اختر الولايات",
  "Category": "الفئة",
  "Sub Category": "الفئة الفرعية",
  "Ratings": "التقييمات",
  "Sort By": "ترتيب حسب",
  "Select Category": "اختر الفئة",
  "Select Subcategory": "اختر الفئة الفرعية",
  "Highest Price": "أعلى سعر",
  "Lowest Price": "أقل سعر",
  "Latest Service": "أحدث خدمة",
  "Offline": "غير متصل",
  "Online": "متصل",
  "Job Requests": "طلبات العمل",
  "View details": "عرض التفاصيل",
  "Conversation": "المحادثة",
  "Hire now": "توظيف الآن",
  "Your offer": "عرضك",
  "Seller offer": "عرض البائع",
  "No request found": "لم يتم العثور على طلبات",
  "Deadline": "الموعد النهائي",
  "Balance": "الرصيد",
  "History": "التاريخ",
  "Gateway": "البوابة",
  "Amount": "المبلغ",
  "Payment Status": "حالة الدفع",
  "No history found": "لم يتم العثور على تاريخ",
  "Total Payable": "المجموع المستحق",
  "Deposit Amount": "مبلغ الإيداع",
  "Enter deposit amount": "أدخل مبلغ الإيداع",
  "You must agree with the terms and conditions to place the order":
      "يجب أن توافق على الشروط والأحكام لتقديم الطلب",
  "Pay & Confirm": "ادفع وأكد",
  "I agree with terms and conditions": "أوافق على الشروط والأحكام",
  "Reports": "التقارير",
  "Report id": "معرف التقرير",
  "Chat admin": "إدارة الدردشة",
  "Order id": "معرف الطلب",
  "No Report": "لا يوجد تقرير",
  "Please write a message first": "الرجاء كتابة رسالة أولاً",
  "Write message": "كتابة رسالة",
  "Remember Me": "تذكرني",
  "Don't have account?": "لا تملك حساب؟",
  "Login with Google": "تسجيل الدخول باستخدام جوجل",
  "Login with Facebook": "تسجيل الدخول باستخدام فيسبوك",
  "Full name": "الاسم الكامل",
  "Please enter your full name": "الرجاء إدخال اسمك الكامل",
  "Username": "اسم المستخدم",
  "Please enter your username": "الرجاء إدخال اسم المستخدم الخاص بك",
  "Enter phone number": "أدخل رقم الهاتف",
  "Have an account?": "هل لديك حساب؟",
  "Sign Up": "اشترك",
  "Choose area": "اختر المنطقة",
  "Book Now": "احجز الآن",
  "Recent jobs": "الوظائف الأخيرة",
  "Top booked services": "أعلى الخدمات حجزاً",
  "About seller": "عن البائع",
  "Order Completed": "تم إكمال الطلب",
  "From": "من",
  "Order Completion Rate": "معدل إكمال الطلبات",
  "Seller Since": "بائع منذ",
  "Orders completed": "الطلبات المكتملة",
  "Seller Ratings": "تقييمات البائع",
  "Watch video": "مشاهدة الفيديو",
  "Book Appointment": "حجز موعد",
  "What is included": "ما هو المشمول",
  "Add extras": "إضافة إضافات",
  "Booking Information": "معلومات الحجز",
  "Details": "التفاصيل",
  "Booking details": "تفاصيل الحجز",
  "Package Fee": "رسوم الباقة",
  "Extra Service Fee": "رسوم الخدمة الإضافية",
  "Extra Service": "خدمة إضافية",
  "My Orders": "طلباتي",
  "You can not cancel this order": "لا يمكنك إلغاء هذا الطلب",
  "No active order": "لا يوجد طلب نشط",
  "Leave feedback": "ترك تعليق",
  "Cancel order": "إلغاء الطلب",
  "Report to admin": "الإبلاغ للمسؤول",
  "Order Details": "تفاصيل الطلب",
  "Payment method": "طريقة الدفع",
  "Pay now": "ادفع الآن",
  "Saved services": "الخدمات المحفوظة",
  "No service saved": "لا توجد خدمات محفوظة",
  "Payment failed!": "فشل الدفع!",
  "Go to home": "الذهاب إلى الرئيسية",
  "Personal information's": "معلومات شخصية",
  "Your address": "عنوانك",
  "Time": "الوقت",
  "Active": "نشط",
  "Pending": "قيد الانتظار",
  "pending": "قيد الانتظار",
  "Delivered": "تم التوصيل",
  "Completed": "مكتمل",
  "complete": "اكتمل",
  "Cancelled": "أُلغيت",
  "Unknown": "غير معروف",
  "Decline history": "تاريخ الرفض",
  "Decline reason": "سبب الرفض",
  "Buyer details": "تفاصيل المشتري",
  "Complete Request": "طلب الإكمال",
  "Declined": "مرفوض",
  "Order completed": "تم إكمال الطلب",
  "Seller requested to mark this order complete":
      "طلب البائع تمييز هذا الطلب كمكتمل",
  "Decline": "رفض",
  "Accept": "قبول",
  "Skip": "تخطي",
  "Job Request ID": "معرف طلب العمل",
  "Attachment": "مرفق",
  "Conversations": "المحادثات",
  "You don't have any active conversation": "ليس لديك أي محادثة نشطة",
  "Write message...": "اكتب رسالة...",
  "Edit": "تعديل",
  "Delete": "حذف",
  "On/Off": "تشغيل/إيقاف",
  "Urgent": "عاجل",
  "High": "عالي",
  "Medium": "متوسط",
  "Low": "منخفض",
  "Please enter ticket title": "الرجاء إدخال عنوان التذكرة",
  "Ticket title": "عنوان التذكرة",
  "Please explain your problem": "يرجى شرح مشكلتك",
  "Create ticket": "إنشاء تذكرة",
  "You don't have any active order": "ليس لديك أي طلب نشط",
  "open": "فتح",
  "close": "إغلاق",
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "أدخل البريد الإلكتروني الذي استخدمته لإنشاء الحساب وسنرسل تعليمات إعادة تعيين كلمة المرور",
  "Enter Email": "أدخل البريد الإلكتروني",
  "Send Instructions": "أرسل التعليمات",
  "All Categories": "جميع الفئات",
  "Already hired a seller for this job.": "تم تعيين بائع بالفعل لهذه الوظيفة.",
  "Enter the 4 digit code we sent to to your email in order to reset password":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني لإعادة تعيين كلمة المرور",
  "OR": "أو",
  "Sign in": "تسجيل الدخول",
  "Search country": "بحث عن دولة",
  "Verify Email": "تحقق من البريد الإلكتروني",
  "by": "بواسطة",
  "Star": "نجمة",
  "Write a review": "اكتب مراجعة",
  "How was the service?": "كيف كانت الخدمة؟",
  "Post review": "نشر المراجعة",
  "Report": "تقرير",
  "What went wrong?": "ما الذي حدث بشكل خاطئ؟",
  "Write the issue": "اكتب المشكلة",
  "Submit Report": "تقديم التقرير",
  "You must write something to submit report":
      "يجب أن تكتب شيئًا لتقديم التقرير",
  "Yes": "نعم",
  "No": "لا",
  "Load Failed": "فشل التحميل",
  "Release to load more": "حرر لتحميل المزيد",
  "No more Data": "لا توجد بيانات إضافية",
  "Edit Job": "تعديل الوظيفة",
  "Edit job": "تعديل الوظيفة",
  "Select area": "اختر المنطقة",
  "New password": "كلمة مرور جديدة",
  "Enter new password": "أدخل كلمة المرور الجديدة",
  "No service available": "لا توجد خدمة متاحة",
  "No service available in your area": "لا توجد خدمات متاحة في منطقتك",
  "No Date Created": "لم يتم إنشاء تاريخ",
  "No Schedule Created": "لم يتم إنشاء جدول",
  "Show Description": "عرض الوصف",
  "Hide Description": "إخفاء الوصف",
  "Post code": "الرمز البريدي",
  "All Services": "جميع الخدمات",
  "Select Date": "اختر التاريخ",
  "Support tickets": "تذاكر الدعم",
  "Priority": "الأولوية",
  "Order number": "رقم الطلب",
  "Success": "نجاح",
  "Order extra accepted": "تم قبول الإضافات للطلب",
  "Hired successfully": "تم التعيين بنجاح",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "Enter the 4 digit code we sent to to your email in order verify your email":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني للتحقق من بريدك الإلكتروني",
  "Describe why you want to decline the request": "صف لماذا تريد رفض الطلب",
  "You must enter decline reason": "يجب عليك إدخال سبب الرفض",
  "Press again to exit": "اضغط مرة أخرى للخروج",
  "Order complete request successfully approved.":
      "تمت الموافقة بنجاح على طلب إكمال الطلب.",
  "No city found": "لم يتم العثور على مدينة",
  "Search state": "بحث عن ولاية",
  "Select City": "اختر المدينة",
  "No country found": "لم يتم العثور على دولة",
  "No area found": "لم يتم العثور على منطقة",
  "Search area": "بحث عن منطقة",
  "Choose image": "اختر صورة",
  "Unit price": "سعر الوحدة",
  "Quantity": "الكمية",
  "declined your order extra request": "رفض طلبك الإضافي للطلب",
  "Order Id": "معرف الطلب",
  "Decline Success": "نجاح الرفض",
  "Extra Service Not Found": "لم يتم العثور على خدمة إضافية",
  "No date found": "لم يتم العثور على تاريخ",
  "Delete Account": "حذف الحساب",
  "active": "نشط",
  "delivered": "تم التوصيل",
  "cancelled": "ملغى",
  "Order Not Found": "لم يتم العثور على الطلب",
  "Support Ticket Created Success": "تم إنشاء تذكرة الدعم بنجاح",
  "Message:": "الرسالة:",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.":
      "تغيير كلمة المرور غير متاح. نأسف، ولكن لا يمكن للمستخدمين الذين قاموا بالتسجيل أو تسجيل الدخول باستخدام حسابات جوجل أو فيسبوك تغيير كلمة المرور مباشرة على هذه المنصة.",
  "Payment cancelled!": "تم إلغاء الدفع!",
  "Payment has been expired.": "انتهت صلاحية الدفع.",
  "Payment has been cancelled.": "تم إلغاء الدفع.",
  "Welcome to Fun Moments": "مرحباً بك في Fun Moments",
  "Hello! 👋": "مرحبا! 👋",
  "You'll have to login/register to edit or see your profile info.":
      "سيتعين عليك تسجيل الدخول/التسجيل لتعديل معلومات ملفك الشخصي أو عرضها.",
  "Sign-In/Sign-Up": "تسجيل الدخول/التسجيل",
  "Sign in with Apple": "تسجيل الدخول باستخدام Apple",
  "Apple id revoked successfully": "تم إلغاء معرف Apple بنجاح",
  "Apple id revoke failed": "فشل إلغاء معرف Apple",
  "Please provide maximum filter price amount": "يرجى توفير أقصى مبلغ للتصفية",
  "Apply Filter": "تطبيق الفلتر",
  "Clear Filter": "مسح الفلتر",
  "Select child-category": "اختر الفئة الفرعية",
  "Child-category": "الفئة الفرعية",
  "Type": "النوع",
  "Distance": "المسافة",
  "Search Location": "بحث عن موقع",
  "No location found": "لم يتم العثور على موقع",
  "Chose location": "اختر موقع",
  "Choosing current location": "اختيار الموقع الحالي",
  "Failed to get location": "فشل في الحصول على الموقع",
  "Location set successfully": "تم تعيين الموقع بنجاح",
  "Choose Current Location": "اختر الموقع الحالي",
  "Email or username": "البريد الإلكتروني أو اسم المستخدم",
  "No message found": "لم يتم العثور على رسالة"
};
