import 'package:funmoments/view/utils/saudi_locations_strings.dart';

var appStrings = {
  "welcome": "welcome",
  "Browse categories": "Browse categories",
  "All categories": "All categories",
  "Top services": "Top services",
  "Recently listed": "Recently listed",
  "See all": "See all",
  "Home": "Home",
  "Discover": "Discover",
  "Bookings": "Bookings",
  "Orders": "Orders",
  "Dashboard": "Dashboard",
  "Services": "Services",
  "Jobs": "Jobs",
  "Book Now": "Book Now",
  "Save": "Save",
  "Saved": "Saved",
  "Search": "Search",
  "Profile": "Profile",
  "Settings": "Settings",
  "Search services": "Search services",
  "Date": "Date",
  "Schedule": "Schedule",
  "Billed": "Billed",
  "My orders": "My orders",
  "Seller Details": "Seller Details",
  "Name": "Name",
  "Email": "Email",
  "Phone": "Phone",
  "Post Code": "Post Code",
  "Address": "Address",
  "Date & Schedule": "Date & Schedule",
  "Amount Details": "Amount Details",
  "Package fee": "Package fee",
  "Extra service": "Extra service",
  "Subtotal": "Subtotal",
  "Tax": "Tax",
  "Total": "Total",
  "Payment status": "Payment status",
  "Order Status": "Order Status",
  "Saved Services": "Saved Services",
  "Starts from": "Starts from",
  "No result found": "No result found",
  "Pending orders": "Pending orders",
  "Active orders": "Active orders",
  "Completed orders": "Completed orders",
  "Total orders": "Total orders",
  "City": "City",
  "Area": "Area",
  "Country": "Country",
  "Support ticket": "Support ticket",
  "Edit profile": "Edit profile",
  "Change Password": "Change Password",
  "Logout": "Logout",
  "Create": "Create",
  "No ticket": "No ticket",
  "All services": "All services",
  "All": "All",
  "Highest price": "Highest price",
  "Lowest price": "Lowest price",
  "Latest service": "Latest service",
  "Full Name": "Full Name",
  "About": "About",
  "Your Address": "Your Address",
  "Choose country": "Choose country",
  "Choose city": "Choose city",
  "Choose Area": "Choose Area",
  "Service Name": "Service Name",
  "Our Package": "Our Package",
  "Orders Completed": "Orders Completed",
  "Seller ratings": "Seller ratings",
  "Overview": "Overview",
  "About Seller": "About Seller",
  "Review": "Review",
  "Benefits of premium Package": "Benefits of premium Package",
  "Benefits of the premium package": "Benefits of the premium package",
  "FAQ": "FAQ",
  "Book appointment": "Book appointment",
  "Personalize": "Personalize",
  "Service personalization": "Service personalization",
  "Next": "Next",
  "What's included": "What's included",
  "Add Extra": "Add Extra",
  "Benefits of the package": "Benefits of the package",
  "Benefits of the Package": "Benefits of the Package",
  "Available Schedules": "Available Schedules",
  "Available time": "Available time",
  "No schedule available on this date": "No schedule available on this date",
  "Choose Location": "Choose Location",
  "Booking information's": "Booking information's",
  "Booking confirmation": "Booking confirmation",
  "Booking Details": "Booking Details",
  "Location": "Location",
  "Swipe up for details": "Swipe up for details",
  "Proceed to payment": "Proceed to payment",
  "Collapse details": "Collapse details",
  "Appointment package service": "Appointment package service",
  "Extra service fee": "Extra service fee",
  "Coupon": "Coupon",
  "Coupon code": "Coupon code",
  "Enter coupon code": "Enter coupon code",
  "Apply": "Apply",
  "Payment": "Payment",
  "Total payable": "Total payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Pay & confirm order": "Pay & confirm order",
  "Payment successful": "Payment successful",
  "Book a DJ": "Book a DJ",
  "Rent Party Equipment": "Rent Party Equipment",
  "Discover your next event": "Discover your next event",
  "Premium entertainment for Riyadh and Saudi Arabia":
      "Premium entertainment for Riyadh and Saudi Arabia",
  "DJ booking": "DJ booking",
  "Equipment rental": "Equipment rental",
  "Riyadh nights": "Riyadh nights",
  "Everything you need for music and events":
      "Everything you need for music and events",
  "Discover your next moment": "Discover your next moment",
  "Search premium services, providers, and bookings":
      "Search premium services, providers, and bookings",
  "Welcome back": "Welcome back",
  "Login to continue your FUN MOMENT journey":
      "Login to continue your FUN MOMENT journey",
  "Create your account to book or sell services.":
      "Create your account to book or sell services.",
  "Login or register to unlock your FUN MOMENT profile":
      "Login or register to unlock your FUN MOMENT profile",
  "Order status": "Order status",
  "Are you sure?": "Are you sure?",
  "Cancel": "Cancel",
  "Welcome back! Login": "Welcome back! Login",
  "Password": "Password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Enter password": "Enter password",
  "Do not have an account": "Do not have an account",
  "Register": "Register",
  "Or": "Or",
  "Login with google": "Login with google",
  "Login with facebook": "Login with facebook",
  "Register to join us": "Register to join us",
  "Enter your full name": "Enter your full name",
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  "Continue": "Continue",
  "Already have an account": "Already have an account",
  "Repeat password": "Repeat password",
  "Phone number": "Phone number",
  "Reset password": "Reset password",
  "Enter the email you used to create account and we well send information for resetting password":
      "Enter the email you used to create account and we well send information for resetting password",
  "Enter email": "Enter email",
  "Send instructions": "Send instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "Enter the 4 digit code we sent to your email in order to reset password",
  "Did not receive": "Didn't receive",
  "Send again": "Send again",
  "Something went wrong": "Something went wrong",
  "Retry": "Retry",
  "Service not found": "Service not found",
  "Request timed out. Please try again.": "Request timed out. Please try again.",
  "Network connection failed": "Network connection failed",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Password must be at least 8 characters":
      "Password must be at least 8 characters",
  "Password should be at least 8 characters long":
      "Password should be at least 8 characters long",
  "Password should contain at least 1 uppercase letter":
      "Password should contain at least 1 uppercase letter",
  "Password should contain at least 1 lowercase letter":
      "Password should contain at least 1 lowercase letter",
  "Password should contain at least 1 digit":
      "Password should contain at least 1 digit",
  "Password should contain at least 1 special character":
      "Password should contain at least 1 special character",
  "Have an account": "Have an account",
  'Menu': 'Menu',
  "My jobs": "My jobs",
  "Job requests": "Job requests",
  "Support Ticket": "Support Ticket",
  "Wallet": "Wallet",
  "My report list": "My report list",
  "Edit Profile": "Edit Profile",
  "Change password": "Change password",
  "Enter current password": "Enter current password",
  "Enter your current password": "Enter your current password",
  "Please enter your password": "Please enter your password",
  "Repeat new password": "Repeat new password",
  "Please retype your password": "Please retype your password",
  "Retype new password": "Retype new password",
  "Make sure you repeated new password correctly":
      "Make sure you repeated new password correctly",
  "Password changed successfully": "Password changed successfully",
  "Please turn on your internet connection":
      "Please turn on your internet connection",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "Your entered the otp correctly but something went wrong. Please try again later",
  "Otp didn't match": "Otp didn't match",
  "Otp is null": "Otp is null",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "Didn't get any user info after google sign in. visit google sign in service file",
  "Login successful": "Login successful",
  "Invalid Email or Password": "Invalid Email or Password",
  "Password didn't match": "Password didn't match",
  "Password updated successfully": "Password updated successfully",
  "Registration successful": "Registration successful",
  "Otp send failed": "Otp send failed",
  "You already applied this coupon": "You already applied this coupon",
  "Please enter a valid coupon": "Please enter a valid coupon",
  "Order placed successfully": "Order placed successfully",
  "Failed to make payment status successful":
      "Failed to make payment status successful",
  "Check your internet connection and try again":
      "Check your internet connection and try again",
  "You have received an order from": "You have received an order from",
  "You must select an image": "You must select an image",
  "You must select category & subcategory":
      "You must select category & subcategory",
  "Job posted successfully": "Job posted successfully",
  "Job updated successfully": "Job updated successfully",
  "Only zip file is supported": "Only zip file is supported",
  "Please check your internet connection":
      "Please check your internet connection",
  "New job chat message": "New job chat message",
  "Hiring successful": "Hiring successful",
  "Job deleted successfully": "Job deleted successfully",
  "New chat message": "New chat message",
  "You don't have enough wallet balance":
      "You don't have enough wallet balance",
  "Payment cancelled": "Payment cancelled",
  "Service Personalization": "Service Personalization",
  "Information's": "Information's",
  "Booking Confirmations": "Booking Confirmations",
  "Select Country": "Select Country",
  "Select State": "Select State",
  "Select Area": "Select Area",
  "review posted successfully": "Review posted successfully",
  "Report submitted": "Report submitted",
  "accepted your order extra request": "accepted your order extra request",
  "Error accepting order extra": "Error accepting order extra",
  "Error declining order extra": "Error declining order extra",
  "accepted your order completion request":
      "accepted your order completion request",
  "Profile updated successfully": "Profile updated successfully",
  "Wallet deposit success": "Wallet deposit success",
  "You must enter an amount": "You must enter an amount",
  "Please enter a valid amount": "Please enter a valid amount",
  "Ticket created successfully": "Ticket created successfully",
  "Welcome": "Welcome",
  "Create Job": "Create Job",
  "Please enter a title": "Please enter a title",
  "Title": "Title",
  "Budget": "Budget",
  "Please enter your budget": "Please enter your budget",
  "Description": "Description",
  "End date": "End date",
  "Create job": "Create job",
  "You must enter a valid budget": "You must enter a valid budget",
  "Choose states": "Choose states",
  "Category": "Category",
  "Sub Category": "Sub Category",
  "Ratings": "Ratings",
  "Sort By": "Sort By",
  'Select Category': 'Select Category',
  'Select Subcategory': 'Select Subcategory',
  "Highest Price": "Highest Price",
  "Lowest Price": "Lowest Price",
  "Latest Service": "Latest Service",
  "Offline": "Offline",
  "Online": "Online",
  "Job Requests": "Job Requests",
  "View details": "View details",
  "Conversation": "Conversation",
  "Hire now": "Hire now",
  'Your offer': 'Your offer',
  "Seller offer": "Seller offer",
  "No request found": "No request found",
  'Deadline': 'Deadline',
  "Balance": "Balance",
  "History": "History",
  "Gateway": "Gateway",
  "Amount": "Amount",
  "Payment Status": "Payment Status",
  'No history found': 'No history found',
  "Total Payable": "Total Payable",
  "Deposit Amount": "Deposit Amount",
  "Enter deposit amount": "Enter deposit amount",
  "You must agree with the terms and conditions to place the order":
      "You must agree with the terms and conditions to place the order",
  "Pay & Confirm": "Pay & Confirm",
  "I agree with terms and conditions": "I agree with terms and conditions",
  "Reports": "Reports",
  "Report id": "Report id",
  'Chat admin': 'Chat admin',
  "Order id": "Order id",
  "No Report": "No Report",
  "Please write a message first": "Please write a message first",
  "Write message": "Write message",
  "Remember Me": "Remember Me",
  "Don't have account?": "Don't have account?",
  "Login with Google": "Login with Google",
  "Login with Facebook": "Login with Facebook",
  "Full name": "Full name",
  "Please enter your full name": "Please enter your full name",
  "Username": "Username",
  "Please enter your username": "Please enter your username",
  "Enter phone number": "Enter phone number",
  "Have an account?": "Have an account?",
  "Sign Up": "Sign Up",
  "Choose area": "Choose area",
  "Recent jobs": 'Recent jobs',
  "Top booked services": 'Top booked services',
  "About seller": 'About seller',
  "Order Completed": 'Order Completed',
  "From": 'From',
  "Order Completion Rate": 'Order Completion Rate',
  "Seller Since": 'Seller Since',
  "Orders completed": 'Orders completed',
  "Seller Ratings": 'Seller Ratings',
  "Watch video": 'Watch video',
  "Book Appointment": 'Book Appointment',
  "What is included": 'What is included',
  "Add extras": 'Add extras',
  "Booking Information": 'Booking Information',
  "Details": 'Details',
  "Booking details": 'Booking details',
  "Package Fee": 'Package Fee',
  "Extra Service Fee": 'Extra Service Fee',
  "Extra Service": 'Extra Service',
  "My Orders": 'My Orders',
  "You can not cancel this order": 'You can not cancel this order',
  "No active order": 'No active order',
  "Leave feedback": 'Leave feedback',
  "Cancel order": 'Cancel order',
  "Report to admin": 'Report to admin',
  "Order Details": 'Order Details',
  "Payment method": 'Payment method',
  "Pay now": 'Pay now',
  "Saved services": 'Saved services',
  "No service saved": 'No service saved',
  "Payment failed!": 'Payment failed!',
  "Go to home": 'Go to home',
  "Personal information's": "Personal information's",
  "Your address": 'Your address',
  "Time": 'Time',
  "Active": 'Active',
  "Pending": 'Pending',
  "pending": 'pending',
  "Delivered": 'Delivered',
  "Completed": 'Completed',
  "complete": 'complete',
  "Cancelled": 'Cancelled',
  "Unknown": 'Unknown',
  "Decline history": 'Decline history',
  "Decline reason": 'Decline reason',
  "Buyer details": 'Buyer details',
  "Complete Request": 'Complete Request',
  "Declined": 'Declined',
  "Order completed": 'Order completed',
  "Seller requested to mark this order complete":
      'Seller requested to mark this order complete',
  "Decline": 'Decline',
  "Accept": 'Accept',
  "Skip": 'Skip',
  "Job Request ID": 'Job Request ID',
  "Attachment": 'Attachment',
  "Conversations": 'Conversations',
  "You don't have any active conversation":
      "You don't have any active conversation",
  "Write message...": "Write message...",
  "Edit": 'Edit',
  "Delete": 'Delete',
  "On/Off": 'On/Off',
  "Urgent": 'Urgent',
  "High": 'High',
  "Medium": 'Medium',
  "Low": 'Low',
  "Please enter ticket title": 'Please enter ticket title',
  "Ticket title": 'Ticket title',
  "Please explain your problem": 'Please explain your problem',
  "Create ticket": 'Create ticket',
  "You don't have any active order": "You don't have any active order",
  "open": 'open',
  "close": 'close',
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "Enter the email you used to create account and we'll send instruction for resetting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "All Categories": 'All Categories',
  "Already hired a seller for this job.":
      'Already hired a seller for this job.',
  "Enter the 4 digit code we sent to to your email in order to reset password":
      'Enter the 4 digit code we sent to to your email in order to reset password',
  "OR": 'OR',
  "Sign in": 'Sign in',
  "Search country": 'Search country',
  "Verify Email": 'Verify Email',
  "by": 'by',
  "Star": 'Star',
  "Write a review": 'Write a review',
  "How was the service?": "How was the service?",
  "Post review": "Post review",
  "Report": "Report",
  "What went wrong?": "What went wrong?",
  "Write the issue": "Write the issue",
  "Submit Report": "Submit Report",
  "You must write something to submit report":
      "You must write something to submit report",
  "Yes": "Yes",
  "No": "No",
  "Load Failed": "Load Failed",
  "Release to load more": "Release to load more",
  "No more Data": "No more Data",
  "Edit Job": "Edit Job",
  "Edit job": "Edit job",
  "Select area": "Select area",
  "New password": "New password",
  "Enter new password": "Enter new password",
  "No service available": "No service available",
  "No service available in your area": "No service available in your area",
  "No Date Created": "No Date Created",
  "No Schedule Created": "No Schedule Created",
  "Show Description": "Show Description",
  "Hide Description": "Hide Description",
  "Post code": "Post code",
  "All Services": "All Services",
  "Select Date": "Select Date",
  "Support tickets": "Support tickets",
  "Priority": "Priority",
  "Order number": "Order number",
  "Success": "Success",
  "Order extra accepted": "Order extra accepted",
  "Hired successfully": "Hired successfully",
  "January": "January",
  "February": "February",
  "March": "March",
  "April": "April",
  "Enter the 4 digit code we sent to to your email in order verify your email":
      "Enter the 4 digit code we sent to to your email in order verify your email",
  "Describe why you want to decline the request":
      "Describe why you want to decline the request",
  "You must enter decline reason": "You must enter decline reason",
  "Press again to exit": "Press again to exit",
  "Order complete request successfully approved.":
      "Order complete request successfully approved.",
  "No city found": "No city found",
  "Search state": "Search state",
  "Select City": "Select City",
  "No country found": "No country found",
  "No area found": "No area found",
  "Search area": "Search area",
  "Choose image": "Choose image",
  "Unit price": "Unit price",
  "Quantity": "Quantity",
  "declined your order extra request": "declined your order extra request",
  "Order Id": "Order Id",
  "Decline Success": "Decline Success",
  "Extra Service Not Found": "Low",
  "No date found": "No date found",
  "Delete Account": "Delete Account",
  "active": "active",
  "delivered": "delivered",
  "cancelled": "cancelled",
  "Order Not Found": "Order Not Found",
  "Support Ticket Created Success": "Support Ticket Created Success",
  "Message:": "Message:",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.":
      "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.",
  "Payment cancelled!": "Payment cancelled!",
  "Payment has been expired.": "Payment has been expired.",
  "Payment has been cancelled.": "Payment has been cancelled.",
  "Welcome to Fun Moments": "Welcome to Fun Moments",
  "Hello! 👋": "Hello! 👋",
  "You'll have to login/register to edit or see your profile info.":
      "You'll have to login/register to edit or see your profile info.",
  "Sign-In/Sign-Up": "Sign-In/Sign-Up",
  "Sign in with Apple": "Sign in with Apple",
  "Apple id revoked successfully": "Apple id revoked successfully",
  "Apple id revoke failed": "Apple id revoke failed",
  "Please provide maximum filter price amount":
      "Please provide maximum filter price amount",
  "Apply Filter": "Apply Filter",
  "Clear Filter": "Clear Filter",
  "Select child-category": "Select child-category",
  "Child-category": "Child-category",
  "Filter": "Filter",
  "Reset": "Reset",
  "Type": "Type",
  "Distance": "Distance",
  "Search Location": "Search Location",
  "No location found": "No location found",
  "Chose location": "Chose location",
  "Choosing current location": "Choosing current location",
  "Failed to get location": "Failed to get location",
  "Location set successfully": "Location set successfully",
  "Choose Current Location": "Choose Current Location",
  "Email or username": "Email or username",
  "No message found": "No message found",
  "Order": "Order",
  "No results found": "No results found",
  "Enter your post code": "Enter your post code",
  "Short description": "Short description",
  "description": "description",
  "Delete account": "Delete account",
  "Choose Reason": "Choose Reason",
  "Vacation": "Vacation",
  "Personal reason": "Personal reason",
  "Price": "Price",
  "Min": "Min",
  "Max": "Max",
  "Best Selling Service": "Best Selling Service",
  "Popular Service": "Popular Service",
  "Featured Service": "Featured Service",
  "Select subcategory": "Select subcategory",
  "Subcategory": "Subcategory",
  "Select category": "Select category",
  "Provider Workspace": "Provider Workspace",
  "Pending Orders": "Pending Orders",
  "Manage your services, client orders, and earnings":
      "Manage your services, client orders, and earnings",
  "Active Services": "Active Services",
  "Total Revenue": "Total Revenue",
  "SELLER": "SELLER",
  "My Services": "My Services",
  "Add Service": "Add Service",
  "Language": "Language",
  "English": "English",
  "Arabic": "Arabic",
  "Choose language": "Choose language",
  "Welcome to FUN MOMENT": "Welcome to FUN MOMENT",
  "Guest": "Guest",
  "Explore the most requested moments first":
      "Explore the most requested moments first",
  "Active booking and updates will appear here":
      "Active booking and updates will appear here",
  "Personal information": "Personal information",
  "Default": "Default",
  "Switch to English": "Switch to English",
  "Switch to Arabic": "Switch to Arabic",
  "Are you sure you want to delete": "Are you sure you want to delete",
  "Delete Service": "Delete Service",
  "Provider Tools": "Provider Tools",
  "Create listing": "Create listing",
  "Client bookings": "Client bookings",
  "Applied jobs": "Applied jobs",
  "Direct invites": "Direct invites",
  "Payouts & balance": "Payouts & balance",
  "Support": "Support",
  "Help tickets": "Help tickets",
  "Discover Your Perfect Moment": "Discover Your Perfect Moment",
  "Find DJs, entertainment, venues, and everything you need to bring your event to life.":
      "Find DJs, entertainment, venues, and everything you need to bring your event to life.",
  "Everything for Your Event": "Everything for Your Event",
  "From equipment and décor to catering and more, find it all in one place.":
      "From equipment and décor to catering and more, find it all in one place.",
  "Choose. Book. Celebrate.": "Choose. Book. Celebrate.",
  "Compare services, book with ease, and enjoy the moment you created.":
      "Compare services, book with ease, and enjoy the moment you created.",
  "Pending Admin Approval": "Pending Admin Approval",
  "Approved": "Approved",
  "Service Submitted Successfully": "Service Submitted Successfully",
  "Your service has been submitted and is pending admin approval.":
      "Your service has been submitted and is pending admin approval.",
  "View My Services": "View My Services",
  "Awaiting admin approval before publishing to customers":
      "Awaiting admin approval before publishing to customers",
  "Music & DJ": "Music & DJ",
  "Food & Hospitality": "Food & Hospitality",
  "Sound & Lighting": "Sound & Lighting",
  "Event Setup & Equipment": "Event Setup & Equipment",
  "Decor & Event Styling": "Decor & Event Styling",
  "Photography & Video": "Photography & Video",
  "Entertainment Activities": "Entertainment Activities",
  "Saudi Arabia": "Saudi Arabia",
  "Riyadh": "Riyadh",
  "Olaya": "Olaya",
  "Building number": "Building number",
  "Enter building number": "Enter building number (e.g. 1234)",
  "Additional details / Notes": "Additional details / Notes",
  "Enter additional details (e.g. apartment, floor, landmark)": "Enter additional details (e.g. apartment, floor, landmark)",
  "District / Area": "District / Area",
  "Street address": "Street address",
  "Enter street address": "Enter street address",
  "Selected Location": "Selected Location",
  "Please select a city and area": "Please select a city and area",
  "No cities found": "No cities found",
  "No areas found": "No areas found",
  "Please enter a valid phone number": "Please enter a valid phone number",
  "Please enter building number": "Please enter building number",
  "Please select a city first": "Please select a city first",
  "No items here yet": "No items here yet",
  "no services in this category yet": "no services in this category yet",
  "No services available yet in this category.": "No services available yet in this category.",
  "There are no services available right now.": "There are no services available right now.",
  "We could not load services": "We could not load services",
  "Please check your connection and try again.": "Please check your connection and try again.",
  "Registration": "Registration",
  "What would you like to do?": "What would you like to do?",
  "Book services": "Book services",
  "Offer my services": "Offer my services",
  "Sign In": "Sign In",
  "Sign up": "Sign up",
  "Repeat Password": "Repeat Password",
  "Passwords do not match": "Passwords do not match",
  "You must agree to the terms and conditions": "You must agree to the terms and conditions",
  "You must select a city and area": "You must select a city and area",
  "Fixed": "Fixed",
  "Search city": "Search city",
  "Failed to load cities": "Failed to load cities",
  "Failed to load areas": "Failed to load areas",
  "No operating areas are registered for this city yet.": "No operating areas are registered for this city yet.",
  "Could not load locations. Tap retry.": "Could not load locations. Tap retry.",
  "Select Location": "Select Location",
  "Provider Registration": "Provider Registration",
  "Join as Service Provider": "Join as Service Provider",
  "Offer your talents and services on FUN MOMENT. Account verification is reviewed by administration.": "Offer your talents and services on FUN MOMENT. Account verification is reviewed by administration.",
  "Provider Type": "Provider Type",
  "Individual": "Individual",
  "Performer, Solo, Specialist": "Performer, Solo, Specialist",
  "Company": "Company",
  "Agency, Business, Est.": "Agency, Business, Est.",
  "Agency, Studio, Establishment": "Agency, Studio, Establishment",
  "Account Information": "Account Information",
  "Enter full name": "Enter full name",
  "Please enter full name": "Please enter full name",
  "Enter username": "Enter username",
  "Please enter username": "Please enter username",
  "Email Address": "Email Address",
  "Enter email address": "Enter email address",
  "Valid email is required": "Valid email is required",
  "Phone Number": "Phone Number",
  "Enter password (min 8 chars)": "Enter password (min 8 chars)",
  "Re-enter password": "Re-enter password",
  "Identity & Qualifications": "Identity & Qualifications",
  "National ID / Iqama Number": "National ID / Iqama Number",
  "10-digit National ID or Iqama": "10-digit National ID or Iqama",
  "National ID / Iqama Document": "National ID / Iqama Document",
  "Upload a clear photo or PDF copy": "Upload a clear photo or PDF copy",
  "Professional License Number": "Professional License Number",
  "Optional professional/freelance permit": "Optional professional/freelance permit",
  "Professional License Document": "Professional License Document",
  "Upload if applicable": "Upload if applicable",
  "Register as Band / Ensemble": "Register as Band / Ensemble",
  "Enable if you represent a musical band or group": "Enable if you represent a musical band or group",
  "Band / Group Name": "Band / Group Name",
  "Enter band name": "Enter band name",
  "Number of Members": "Number of Members",
  "Minimum 2 members": "Minimum 2 members",
  "Company & Commercial Registration": "Company & Commercial Registration",
  "Company / Agency Name": "Company / Agency Name",
  "Registered company name": "Registered company name",
  "Commercial Registration (CR) Number": "Commercial Registration (CR) Number",
  "10-digit CR number": "10-digit CR number",
  "CR Certificate Document": "CR Certificate Document",
  "Official CR document (PDF or image)": "Official CR document (PDF or image)",
  "Contact Person Details": "Contact Person Details",
  "Contact Person Name": "Contact Person Name",
  "Authorized representative": "Authorized representative",
  "Contact Person Email": "Contact Person Email",
  "Contact Person Phone": "Contact Person Phone",
  "Offered Service Categories": "Offered Service Categories",
  "selected": "selected",
  "Select all services you can provide": "Select all services you can provide",
  "Unable to load categories": "Unable to load categories",
  "Location & Operating Area": "Location & Operating Area",
  "Street, District, Building": "Street, District, Building",
  "Postal Code": "Postal Code",
  "Postal code (optional)": "Postal code (optional)",
  "I agree with the terms and conditions and provider policies": "I agree with the terms and conditions and provider policies",
  "Submit Provider Application": "Submit Provider Application",
  "(Optional)": "(Optional)",
  "Optional": "Optional",
  "Upload document (PDF / JPG / PNG)": "Upload document (PDF / JPG / PNG)",
  "Replace": "Replace",
  "Remove": "Remove",
  "Only PDF, JPG, JPEG, and PNG files are supported": "Only PDF, JPG, JPEG, and PNG files are supported",
  "File size must be under 10MB": "File size must be under 10MB",
  "Failed to select file": "Failed to select file",
  "Full name is required": "Full name is required",
  "Email is required": "Email is required",
  "Username is required": "Username is required",
  "Please enter a username": "Please enter a username",
  "Phone number is required": "Phone number is required",
  "Please enter your phone number": "Please enter your phone number",
  "City is required": "City is required",
  "Please select a city": "Please select a city",
  "Area is required": "Area is required",
  "Please select an area": "Please select an area",
  "At least one service category is required": "At least one service category is required",
  "Please select at least one service category": "Please select at least one service category",
  "National ID / Iqama number is required": "National ID / Iqama number is required",
  "Please enter your National ID or Iqama number": "Please enter your National ID or Iqama number",
  "National ID document is required": "National ID document is required",
  "Please upload your National ID or Iqama document": "Please upload your National ID or Iqama document",
  "Document must be PDF, JPG, JPEG, or PNG": "Document must be PDF, JPG, JPEG, or PNG",
  "National ID must be a PDF, JPG, or PNG file": "National ID must be a PDF, JPG, or PNG file",
  "License must be PDF, JPG, JPEG, or PNG": "License must be PDF, JPG, JPEG, or PNG",
  "License must be a PDF, JPG, or PNG file": "License must be a PDF, JPG, or PNG file",
  "Band / Group name is required": "Band / Group name is required",
  "Please enter your band or group name": "Please enter your band or group name",
  "Band must have at least 2 members": "Band must have at least 2 members",
  "Company name is required": "Company name is required",
  "Please enter the registered company name": "Please enter the registered company name",
  "Commercial Registration (CR) number is required": "Commercial Registration (CR) number is required",
  "Please enter the CR number": "Please enter the CR number",
  "CR certificate document is required": "CR certificate document is required",
  "Please upload the CR document": "Please upload the CR document",
  "CR document must be PDF, JPG, JPEG, or PNG": "CR document must be PDF, JPG, JPEG, or PNG",
  "CR document must be a PDF, JPG, or PNG file": "CR document must be a PDF, JPG, or PNG file",
  "Contact person name is required": "Contact person name is required",
  "Please enter the contact person name": "Please enter the contact person name",
  "Contact person email is required": "Contact person email is required",
  "Please enter the contact person email": "Please enter the contact person email",
  "Contact person phone is required": "Contact person phone is required",
  "Please enter the contact person phone": "Please enter the contact person phone",
  "Account already created. Please verify your email.": "Account already created. Please verify your email.",
  "Registration successful. Please verify your email.": "Registration successful. Please verify your email.",
  "Registration failed": "Registration failed",
  "Validation failed. Please check your data.": "Validation failed. Please check your data.",
  "Registration request timed out. Please check your connection and try again.": "Registration request timed out. Please check your connection and try again.",
  "Verify Code": "Verify Code",
  "Please enter the 4 digit code": "Please enter the 4 digit code",
  "OTP sent successfully": "OTP sent successfully",
  "Verification code is missing. Please tap \"Send again\".": "Verification code is missing. Please tap \"Send again\".",
  "Verification timed out. Please try again.": "Verification timed out. Please try again.",
  "Network error: Unable to reach email service": "Network error: Unable to reach email service",
  "Connection error during verification. Please try again.": "Connection error during verification. Please try again.",
  "Network connection failed. Please check your internet and try again.": "Network connection failed. Please check your internet and try again.",
  "The email has already been taken.": "The email has already been taken.",
  "The username has already been taken.": "The username has already been taken.",
  "The phone has already been taken.": "The phone has already been taken.",
  "The password must be at least 8 characters.": "The password must be at least 8 characters.",
  "Notifications": "Notifications",
  "Mark all read": "Mark all read",
  "No notifications yet": "No notifications yet",
  "Updates about your bookings and orders will appear here": "Updates about your bookings and orders will appear here",
  "New Booking Alert": "New Booking Alert",
  "Booking Confirmed": "Booking Confirmed",
  "Booking Cancelled": "Booking Cancelled",
  "Booking Completed": "Booking Completed",
  "Payment Confirmed": "Payment Confirmed",
  "Booking Update": "Booking Update",
  "PayTabs": "PayTabs",
  "Payment successfully verified!": "Payment successfully verified!",
  "Payment failed": "Payment failed",
  "No categories yet": "No categories yet",
  "Categories will appear here when the backend has records.": "Categories will appear here when the backend has records.",
  "Top Booked Services": "Top Booked Services",
  "View More": "View More",
  "Booking Submitted": "Booking Submitted",
  "Enter your name": "Enter your name",
  "Please enter a valid email": "Please enter a valid email",
  "No payment methods available": "No payment methods available",
  "Please check back later or contact customer support.": "Please check back later or contact customer support.",
  "Previous Week": "Previous Week",
  "Next Week": "Next Week",
  "Scheduling for:": "Scheduling for:",
  "Sub total": "Sub total",
  "Extras": "Extras",
  "My Availability": "My Availability",
  "Chat": "Chat",
  "Please enter order id": "Please enter order id",
  "Please enter your email or username": "Please enter your email or username",
  "Please enter a valid password": "Please enter a valid password",
};

var translations = {
  "no services in this category yet": "لا توجد خدمات في هذه الفئة بعد",
  "welcome": "أهلاً بك",
  "Browse categories": "تصفح الفئات",
  "All categories": "جميع الفئات",
  "All Categories": "جميع الفئات",
  "Top services": "أفضل الخدمات",
  "Top booked services": "الخدمات الأكثر حجزاً",
  "Recently listed": "المضافة حديثاً",
  "We could not load recent services right now. Please try again.": "تعذر تحميل أحدث الخدمات حالياً. يرجى المحاولة مرة أخرى.",
  "We could not load categories right now. Please try again.": "تعذر تحميل الفئات حالياً. يرجى المحاولة مرة أخرى.",
  "No service available in your area": "لا توجد خدمات متاحة في منطقتك",
  "The latest services will appear here once the backend has records.": "ستظهر أحدث الخدمات هنا بمجرد توفرها.",
  "See all": "عرض الكل",
  "Home": "الرئيسية",
  "Discover": "استكشاف",
  "Bookings": "الحجوزات",
  "Orders": "الطلبات",
  "Profile": "الملف الشخصي",
  "Dashboard": "لوحة التحكم",
  "Services": "الخدمات",
  "Jobs": "الوظائف",
  "Book Now": "احجز الآن",

  //here
  "Order": "الطلب",
  "Enter your post code": "أدخل رمز البريد الخاص بك",
  "Short description": "وصف مختصر",
  "description": "الوصف",
  "Search": "البحث",
  "Reset": "إعادة تعيين",
  "Location": "الموقع",
  "Filter": "التصفية",
  "No results found": "لا توجد نتائج",
  "Delete account": "حذف الحساب",
  "Choose Reason": "اختر السبب",
  "Vacation": "إجازة",
  "Personal reason": "سبب شخصي",
  "Price": "السعر",
  "Min": "الحد الأدنى",
  "Max": "الحد الأقصى",
  "Best Selling Service": "الخدمة الأكثر مبيعًا",
  "Popular Service": "الخدمة الشهيرة",
  "Featured Service": "الخدمة المميزة",
  "Select subcategory": "تحديد الفئة الفرعية",
  "Subcategory": "الفئة الفرعية",
  "Select category": "تحديد الفئة",

  //here
  "Save": "حفظ",
  "Saved": "تم الحفظ",
  "Settings": "الإعدادات",
  "Search services": "بحث عن خدمات",
  "Date": "التاريخ",
  "Schedule": "الجدول",
  "Billed": "مفوتر",
  "My orders": "طلباتي",
  "Seller Details": "تفاصيل البائع",
  "Name": "الاسم",
  "Email": "البريد الإلكتروني",
  "Phone": "الهاتف",
  "Post Code": "الرمز البريدي",
  "Address": "العنوان",
  "Date & Schedule": "التاريخ والجدول",
  "Amount Details": "تفاصيل المبلغ",
  "Package fee": "رسوم الباقة",
  "Extra service": "خدمة إضافية",
  "Subtotal": "المجموع الفرعي",
  "Tax": "الضريبة",
  "Total": "الإجمالي",
  "Payment status": "حالة الدفع",
  "Order Status": "حالة الطلب",
  "Saved Services": "الخدمات المحفوظة",
  "Starts from": "يبدأ من",
  "No result found": "لا توجد نتائج",
  "Pending orders": "الطلبات المعلقة",
  "Active orders": "الطلبات النشطة",
  "Completed orders": "الطلبات المكتملة",
  "Total orders": "إجمالي الطلبات",
  "City": "المدينة",
  "Area": "المنطقة",
  "Country": "الدولة",
  "Support ticket": "تذكرة الدعم",
  "Edit profile": "تعديل الملف الشخصي",
  "Change Password": "تغيير كلمة المرور",
  "Logout": "تسجيل الخروج",
  "Create": "إنشاء",
  "No ticket": "لا توجد تذكرة",
  "All services": "جميع الخدمات",
  "All": "الكل",
  "Highest price": "السعر الأعلى",
  "Lowest price": "السعر الأدنى",
  "Latest service": "أحدث خدمة",
  "Full Name": "الاسم الكامل",
  "About": "عن",
  "Your Address": "عنوانك",
  "Choose country": "اختر الدولة",
  "Choose city": "اختر المدينة",
  "Choose Area": "اختر المنطقة",
  "Service Name": "اسم الخدمة",
  "Our Package": "الباقة الخاصة بنا",
  "Orders Completed": "الطلبات المكتملة",
  "Seller ratings": "تقييمات البائع",
  "Overview": "نظرة عامة",
  "About Seller": "عن البائع",
  "Review": "مراجعة",
  "Benefits of premium Package": "مزايا الباقة المميزة",
  "Benefits of the premium package": "مزايا الباقة المميزة",
  "FAQ": "الأسئلة الشائعة",
  "Book appointment": "حجز موعد",
  "Personalize": "تخصيص",
  "Service personalization": "تخصيص الخدمة",
  "Next": "التالي",
  "What's included": "ما الذي يشمله",
  "Add Extra": "إضافة إضافي",
  "Benefits of the package": "مزايا الباقة",
  "Benefits of the Package": "مزايا الباقة",
  "Available Schedules": "الجداول المتاحة",
  "Available time": "الوقت المتاح",
  "No schedule available on this date": "لا توجد جداول متاحة في هذا التاريخ",
  "Choose Location": "اختر الموقع",
  "Booking information's": "معلومات الحجز",
  "Booking confirmation": "تأكيد الحجز",
  "Booking Details": "تفاصيل الحجز",
  "Swipe up for details": "اسحب لأعلى للتفاصيل",
  "Proceed to payment": "المتابعة إلى الدفع",
  "Collapse details": "طي التفاصيل",
  "Appointment package service": "خدمة حزمة المواعيد",
  "Extra service fee": "رسوم الخدمة الإضافية",
  "Coupon": "كوبون",
  "Coupon code": "كود الكوبون",
  "Enter coupon code": "أدخل كود الكوبون",
  "Apply": "تطبيق",
  "Payment": "الدفع",
  "Total payable": "المبلغ الإجمالي المستحق",
  "Choose payment method": "اختر طريقة الدفع",
  "Choose images": "اختر الصور",
  "I agree with the terms and conditions": "أوافق على الشروط والأحكام",
  "Pay & confirm order": "ادفع وأكد الطلب",
  "Payment successful": "تم الدفع بنجاح",
  "Book a DJ": "احجز دي جي",
  "Rent Party Equipment": "استأجر معدات الحفلات",
  "Discover your next event": "اكتشف لحظتك التالية",
  "Premium entertainment for Riyadh and Saudi Arabia":
      "ترفيه مميز للرياض والسعودية",
  "DJ booking": "حجز دي جي",
  "Equipment rental": "تأجير المعدات",
  "Riyadh nights": "ليالي الرياض",
  "Everything you need for music and events":
      "كل ما تحتاجه للموسيقى والمناسبات",
  "Discover your next moment": "اكتشف لحظتك التالية",
  "Search premium services, providers, and bookings":
      "ابحث عن الخدمات المميزة ومقدمي الخدمة والحجوزات",
  "Welcome back": "مرحبًا بعودتك",
  "Login to continue your FUN MOMENT journey":
      "سجل الدخول لمتابعة رحلتك مع FUN MOMENT",
  "Create your account to book or sell services.":
      "أنشئ حسابك لحجز أو بيع الخدمات.",
  "Login or register to unlock your FUN MOMENT profile":
      "سجل الدخول أو أنشئ حسابك لفتح ملف FUN MOMENT الخاص بك",
  "Order status": "حالة الطلب",
  "Are you sure?": "هل أنت متأكد؟",
  "Cancel": "إلغاء",
  "Welcome back! Login": "مرحبًا بعودتك! تسجيل الدخول",
  "Password": "كلمة المرور",
  "Remember me": "تذكرني",
  "Forgot Password?": "نسيت كلمة المرور؟",
  "Login": "تسجيل الدخول",
  "Enter password": "أدخل كلمة المرور",
  "Do not have an account": "ليس لديك حساب",
  "Register": "تسجيل",
  "Or": "أو",
  "Login with google": "تسجيل الدخول باستخدام جوجل",
  "Login with facebook": "تسجيل الدخول باستخدام فيسبوك",
  "Register to join us": "سجل للانضمام إلينا",
  "Enter your full name": "أدخل اسمك الكامل",
  "Enter your username": "أدخل اسم المستخدم الخاص بك",
  "Enter your email": "أدخل بريدك الإلكتروني",
  "Continue": "استمر",
  "Already have an account": "هل لديك حساب بالفعل",
  "Repeat password": "أعد كتابة كلمة المرور",
  "Phone number": "رقم الهاتف",
  "Reset password": "إعادة تعيين كلمة المرور",
  "Enter the email you used to create account and we well send information for resetting password":
      "أدخل البريد الإلكتروني الذي استخدمته لإنشاء الحساب وسنرسل المعلومات لإعادة تعيين كلمة المرور",
  "Enter email": "أدخل البريد الإلكتروني",
  "Send instructions": "أرسل التعليمات",
  "Enter the 4 digit code": "أدخل الرمز المكون من 4 أرقام",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني لإعادة تعيين كلمة المرور",
  "Didn't receive": "لم تتلقى",
  "Send again": "أرسل مرة أخرى",
  "Something went wrong": "حدث خطأ ما",
  "Retry": "إعادة المحاولة",
  "Service not found": "الخدمة غير متوفرة",
  "Request timed out. Please try again.": "انتهت مهلة الطلب. يرجى المحاولة مرة أخرى",
  "Network connection failed": "فشل الاتصال بالشبكة",
  "Please wait while the profile is updating":
      "يرجى الانتظار أثناء تحديث الملف الشخصي",
  "Please enter your email": "الرجاء إدخال بريدك الإلكتروني",
  "Please enter post code": "الرجاء إدخال الرمز البريدي",
  "You must select a state and area": "يجب عليك اختيار ولاية ومنطقة",
  "Address field is required": "حقل العنوان مطلوب",
  "Phone field is required": "حقل الهاتف مطلوب",
  "Updating profile...It may take few seconds":
      "جارٍ تحديث الملف الشخصي... قد يستغرق ذلك بضع ثوان",
  "You must agree with the terms and conditions to register":
      "يجب أن توافق على الشروط والأحكام للتسجيل",
  "Password did not match": "كلمة المرور غير متطابقة",
  "Password must be at least 6 characters":
      "يجب أن تكون كلمة المرور على الأقل 6 أحرف",
  "Password must be at least 8 characters":
      "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
  "Password should be at least 8 characters long":
      "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
  "Password should contain at least 1 uppercase letter":
      "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل",
  "Password should contain at least 1 lowercase letter":
      "يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل",
  "Password should contain at least 1 digit":
      "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
  "Password should contain at least 1 special character":
      "يجب أن تحتوي كلمة المرور على رمز خاص واحد على الأقل",
  "Have an account": "لديك حساب",
  "Menu": "القائمة",
  "My jobs": "وظائفي",
  "Job requests": "طلبات العمل",
  "Support Ticket": "تذكرة الدعم",
  "Wallet": "المحفظة",
  "My report list": "قائمة تقاريري",
  "Edit Profile": "تعديل الملف الشخصي",
  "Change password": "تغيير كلمة المرور",
  "Enter current password": "أدخل كلمة المرور الحالية",
  "Enter your current password": "أدخل كلمة المرور الحالية الخاصة بك",
  "Please enter your password": "الرجاء إدخال كلمة المرور الخاصة بك",
  "Repeat new password": "أعد كتابة كلمة المرور الجديدة",
  "Please retype your password": "الرجاء إعادة كتابة كلمة المرور الخاصة بك",
  "Retype new password": "أعد كتابة كلمة المرور الجديدة",
  "Make sure you repeated new password correctly":
      "تأكد من تكرار كلمة المرور الجديدة بشكل صحيح",
  "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
  "Please turn on your internet connection": "يرجى تشغيل اتصال الإنترنت",
  "Your entered the otp correctly but something went wrong. Please try again later":
      "لقد أدخلت رمز التحقق بشكل صحيح ولكن حدث خطأ ما. الرجاء المحاولة لاحقاً",
  "Otp didn't match": "رمز التحقق غير مطابق",
  "Otp is null": "رمز التحقق فارغ",
  "Didn't get any user info after google sign in. visit google sign in service file":
      "لم يتم الحصول على أي معلومات مستخدم بعد تسجيل الدخول باستخدام جوجل. قم بزيارة ملف خدمة تسجيل الدخول بجوجل",
  "Login successful": "تسجيل الدخول ناجح",
  "Invalid Email or Password": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  "Password didn't match": "كلمة المرور غير متطابقة",
  "Password updated successfully": "تم تحديث كلمة المرور بنجاح",
  "Registration successful": "تم التسجيل بنجاح",
  "Otp send failed": "فشل إرسال رمز التحقق",
  "You already applied this coupon": "لقد قمت بالفعل بتطبيق هذا الكوبون",
  "Please enter a valid coupon": "الرجاء إدخال كوبون صالح",
  "Order placed successfully": "تم تقديم الطلب بنجاح",
  "Failed to make payment status successful": "فشل في جعل حالة الدفع ناجحة",
  "Check your internet connection and try again":
      "تحقق من اتصالك بالإنترنت وحاول مرة أخرى",
  "You have received an order from": "لقد تلقيت طلباً من",
  "You must select an image": "يجب عليك اختيار صورة",
  "You must select category & subcategory":
      "يجب عليك اختيار الفئة والفئة الفرعية",
  "Job posted successfully": "تم نشر الوظيفة بنجاح",
  "Job updated successfully": "تم تحديث الوظيفة بنجاح",
  "Only zip file is supported": "يدعم فقط ملف مضغوط",
  "Please check your internet connection": "يرجى التحقق من اتصالك بالإنترنت",
  "New job chat message": "رسالة دردشة وظيفة جديدة",
  "Hiring successful": "تم التوظيف بنجاح",
  "Job deleted successfully": "تم حذف الوظيفة بنجاح",
  "New chat message": "رسالة دردشة جديدة",
  "You don't have enough wallet balance": "رصيد المحفظة لديك غير كافٍ",
  "Payment cancelled": "تم إلغاء الدفع",
  "Service Personalization": "تخصيص الخدمة",
  "Information's": "المعلومات",
  "Booking Confirmations": "تأكيدات الحجز",
  "Select Country": "اختر الدولة",
  "Select State": "اختر الولاية",
  "Select Area": "اختر المنطقة",
  "review posted successfully": "تم نشر المراجعة بنجاح",
  "Report submitted": "تم تقديم التقرير",
  "accepted your order extra request": "تم قبول طلبك الإضافي",
  "Error accepting order extra": "خطأ في قبول الطلب الإضافي",
  "Error declining order extra": "خطأ في رفض الطلب الإضافي",
  "accepted your order completion request": "تم قبول طلب إكمال طلبك",
  "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",
  "Wallet deposit success": "نجاح إيداع المحفظة",
  "You must enter an amount": "يجب عليك إدخال مبلغ",
  "Please enter a valid amount": "يرجى إدخال مبلغ صالح",
  "Ticket created successfully": "تم إنشاء التذكرة بنجاح",
  "Welcome": "مرحبا",
  "Create Job": "إنشاء وظيفة",
  "Please enter a title": "الرجاء إدخال عنوان",
  "Title": "العنوان",
  "Budget": "الميزانية",
  "Please enter your budget": "الرجاء إدخال ميزانيتك",
  "Description": "الوصف",
  "End date": "تاريخ الانتهاء",
  "Create job": "إنشاء وظيفة",
  "You must enter a valid budget": "يجب عليك إدخال ميزانية صحيحة",
  "Choose states": "اختر الولايات",
  "Category": "الفئة",
  "Sub Category": "الفئة الفرعية",
  "Ratings": "التقييمات",
  "Sort By": "ترتيب حسب",
  "Select Category": "اختر الفئة",
  "Select Subcategory": "اختر الفئة الفرعية",
  "Highest Price": "أعلى سعر",
  "Lowest Price": "أقل سعر",
  "Latest Service": "أحدث خدمة",
  "Offline": "غير متصل",
  "Online": "متصل",
  "Job Requests": "طلبات العمل",
  "View details": "عرض التفاصيل",
  "Conversation": "المحادثة",
  "Hire now": "توظيف الآن",
  "Your offer": "عرضك",
  "Seller offer": "عرض البائع",
  "No request found": "لم يتم العثور على طلبات",
  "Deadline": "الموعد النهائي",
  "Balance": "الرصيد",
  "History": "التاريخ",
  "Gateway": "البوابة",
  "Amount": "المبلغ",
  "Payment Status": "حالة الدفع",
  "No history found": "لم يتم العثور على تاريخ",
  "Total Payable": "المجموع المستحق",
  "Deposit Amount": "مبلغ الإيداع",
  "Enter deposit amount": "أدخل مبلغ الإيداع",
  "You must agree with the terms and conditions to place the order":
      "يجب أن توافق على الشروط والأحكام لتقديم الطلب",
  "Pay & Confirm": "ادفع وأكد",
  "I agree with terms and conditions": "أوافق على الشروط والأحكام",
  "Reports": "التقارير",
  "Report id": "معرف التقرير",
  "Chat admin": "إدارة الدردشة",
  "Order id": "معرف الطلب",
  "No Report": "لا يوجد تقرير",
  "Please write a message first": "الرجاء كتابة رسالة أولاً",
  "Write message": "كتابة رسالة",
  "Remember Me": "تذكرني",
  "Don't have account?": "لا تملك حساب؟",
  "Login with Google": "تسجيل الدخول باستخدام جوجل",
  "Login with Facebook": "تسجيل الدخول باستخدام فيسبوك",
  "Full name": "الاسم الكامل",
  "Please enter your full name": "الرجاء إدخال اسمك الكامل",
  "Username": "اسم المستخدم",
  "Please enter your username": "الرجاء إدخال اسم المستخدم الخاص بك",
  "Enter phone number": "أدخل رقم الهاتف",
  "Have an account?": "هل لديك حساب؟",
  "Sign Up": "اشترك",
  "Choose area": "اختر المنطقة",
  "Recent jobs": "الوظائف الأخيرة",
  "About seller": "عن البائع",
  "Order Completed": "تم إكمال الطلب",
  "From": "من",
  "Order Completion Rate": "معدل إكمال الطلبات",
  "Seller Since": "بائع منذ",
  "Orders completed": "الطلبات المكتملة",
  "Seller Ratings": "تقييمات البائع",
  "Watch video": "مشاهدة الفيديو",
  "Book Appointment": "حجز موعد",
  "What is included": "ما هو المشمول",
  "Add extras": "إضافة إضافات",
  "Booking Information": "معلومات الحجز",
  "Details": "التفاصيل",
  "Booking details": "تفاصيل الحجز",
  "Package Fee": "رسوم الباقة",
  "Extra Service Fee": "رسوم الخدمة الإضافية",
  "Extra Service": "خدمة إضافية",
  "My Orders": "طلباتي",
  "You can not cancel this order": "لا يمكنك إلغاء هذا الطلب",
  "No active order": "لا يوجد طلب نشط",
  "Leave feedback": "ترك تعليق",
  "Cancel order": "إلغاء الطلب",
  "Report to admin": "الإبلاغ للمسؤول",
  "Order Details": "تفاصيل الطلب",
  "Payment method": "طريقة الدفع",
  "Pay now": "ادفع الآن",
  "Saved services": "الخدمات المحفوظة",
  "No service saved": "لا توجد خدمات محفوظة",
  "Payment failed!": "فشل الدفع!",
  "Go to home": "الذهاب إلى الرئيسية",
  "Personal information's": "معلومات شخصية",
  "Your address": "عنوانك",
  "Time": "الوقت",
  "Active": "نشط",
  "Pending": "قيد الانتظار",
  "pending": "قيد الانتظار",
  "Delivered": "تم التوصيل",
  "Completed": "مكتمل",
  "complete": "اكتمل",
  "Cancelled": "أُلغيت",
  "Unknown": "غير معروف",
  "Decline history": "تاريخ الرفض",
  "Decline reason": "سبب الرفض",
  "Buyer details": "تفاصيل المشتري",
  "Complete Request": "طلب الإكمال",
  "Declined": "مرفوض",
  "Order completed": "تم إكمال الطلب",
  "Seller requested to mark this order complete":
      "طلب البائع تمييز هذا الطلب كمكتمل",
  "Decline": "رفض",
  "Accept": "قبول",
  "Skip": "تخطي",
  "Job Request ID": "معرف طلب العمل",
  "Attachment": "مرفق",
  "Conversations": "المحادثات",
  "You don't have any active conversation": "ليس لديك أي محادثة نشطة",
  "Write message...": "اكتب رسالة...",
  "Edit": "تعديل",
  "Delete": "حذف",
  "On/Off": "تشغيل/إيقاف",
  "Urgent": "عاجل",
  "High": "عالي",
  "Medium": "متوسط",
  "Low": "منخفض",
  "Please enter ticket title": "الرجاء إدخال عنوان التذكرة",
  "Ticket title": "عنوان التذكرة",
  "Please explain your problem": "يرجى شرح مشكلتك",
  "Create ticket": "إنشاء تذكرة",
  "You don't have any active order": "ليس لديك أي طلب نشط",
  "open": "فتح",
  "close": "إغلاق",
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "أدخل البريد الإلكتروني الذي استخدمته لإنشاء الحساب وسنرسل تعليمات إعادة تعيين كلمة المرور",
  "Enter Email": "أدخل البريد الإلكتروني",
  "Send Instructions": "أرسل التعليمات",
  "Already hired a seller for this job.": "تم تعيين بائع بالفعل لهذه الوظيفة.",
  "Enter the 4 digit code we sent to to your email in order to reset password":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني لإعادة تعيين كلمة المرور",
  "OR": "أو",
  "Sign in": "تسجيل الدخول",
  "Search country": "بحث عن دولة",
  "Verify Email": "تحقق من البريد الإلكتروني",
  "by": "بواسطة",
  "Star": "نجمة",
  "Write a review": "اكتب مراجعة",
  "How was the service?": "كيف كانت الخدمة؟",
  "Post review": "نشر المراجعة",
  "Report": "تقرير",
  "What went wrong?": "ما الذي حدث بشكل خاطئ؟",
  "Write the issue": "اكتب المشكلة",
  "Submit Report": "تقديم التقرير",
  "You must write something to submit report":
      "يجب أن تكتب شيئًا لتقديم التقرير",
  "Yes": "نعم",
  "No": "لا",
  "Load Failed": "فشل التحميل",
  "Release to load more": "حرر لتحميل المزيد",
  "No more Data": "لا توجد بيانات إضافية",
  "Edit Job": "تعديل الوظيفة",
  "Edit job": "تعديل الوظيفة",
  "Select area": "اختر المنطقة",
  "New password": "كلمة مرور جديدة",
  "Enter new password": "أدخل كلمة المرور الجديدة",
  "No service available": "لا توجد خدمة متاحة",
  "No Date Created": "لم يتم إنشاء تاريخ",
  "No Schedule Created": "لم يتم إنشاء جدول",
  "Show Description": "عرض الوصف",
  "Hide Description": "إخفاء الوصف",
  "Post code": "الرمز البريدي",
  "All Services": "جميع الخدمات",
  "Select Date": "اختر التاريخ",
  "Support tickets": "تذاكر الدعم",
  "Priority": "الأولوية",
  "Order number": "رقم الطلب",
  "Success": "نجاح",
  "Order extra accepted": "تم قبول الإضافات للطلب",
  "Hired successfully": "تم التعيين بنجاح",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "Enter the 4 digit code we sent to to your email in order verify your email":
      "أدخل الرمز المكون من 4 أرقام الذي أرسلناه إلى بريدك الإلكتروني للتحقق من بريدك الإلكتروني",
  "Describe why you want to decline the request": "صف لماذا تريد رفض الطلب",
  "You must enter decline reason": "يجب عليك إدخال سبب الرفض",
  "Press again to exit": "اضغط مرة أخرى للخروج",
  "Order complete request successfully approved.":
      "تمت الموافقة بنجاح على طلب إكمال الطلب.",
  "No city found": "لم يتم العثور على مدينة",
  "Search state": "بحث عن ولاية",
  "Select City": "اختر المدينة",
  "No country found": "لم يتم العثور على دولة",
  "No area found": "لم يتم العثور على منطقة",
  "Search area": "بحث عن منطقة",
  "Choose image": "اختر صورة",
  "Unit price": "سعر الوحدة",
  "Quantity": "الكمية",
  "declined your order extra request": "رفض طلبك الإضافي للطلب",
  "Order Id": "معرف الطلب",
  "Decline Success": "نجاح الرفض",
  "Extra Service Not Found": "لم يتم العثور على خدمة إضافية",
  "No date found": "لم يتم العثور على تاريخ",
  "Delete Account": "حذف الحساب",
  "active": "نشط",
  "delivered": "تم التوصيل",
  "cancelled": "ملغى",
  "Order Not Found": "لم يتم العثور على الطلب",
  "Support Ticket Created Success": "تم إنشاء تذكرة الدعم بنجاح",
  "Message:": "الرسالة:",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform.":
      "تغيير كلمة المرور غير متاح. نأسف، ولكن لا يمكن للمستخدمين الذين قاموا بالتسجيل أو تسجيل الدخول باستخدام حسابات جوجل أو فيسبوك تغيير كلمة المرور مباشرة على هذه المنصة.",
  "Payment cancelled!": "تم إلغاء الدفع!",
  "Payment has been expired.": "انتهت صلاحية الدفع.",
  "Payment has been cancelled.": "تم إلغاء الدفع.",
  "Welcome to Fun Moments": "مرحباً بك في Fun Moments",
  "Hello! 👋": "مرحبا! 👋",
  "You'll have to login/register to edit or see your profile info.":
      "سيتعين عليك تسجيل الدخول/التسجيل لتعديل معلومات ملفك الشخصي أو عرضها.",
  "Sign-In/Sign-Up": "تسجيل الدخول/التسجيل",
  "Sign in with Apple": "تسجيل الدخول باستخدام Apple",
  "Apple id revoked successfully": "تم إلغاء معرف Apple بنجاح",
  "Apple id revoke failed": "فشل إلغاء معرف Apple",
  "Please provide maximum filter price amount": "يرجى توفير أقصى مبلغ للتصفية",
  "Apply Filter": "تطبيق الفلتر",
  "Clear Filter": "مسح الفلتر",
  "Select child-category": "اختر الفئة الفرعية",
  "Child-category": "الفئة الفرعية",
  "Type": "النوع",
  "Distance": "المسافة",
  "Search Location": "بحث عن موقع",
  "No location found": "لم يتم العثور على موقع",
  "Chose location": "اختر موقع",
  "Choosing current location": "اختيار الموقع الحالي",
  "Failed to get location": "فشل في الحصول على الموقع",
  "Location set successfully": "تم تعيين الموقع بنجاح",
  "Choose Current Location": "اختر الموقع الحالي",
  "Email or username": "البريد الإلكتروني أو اسم المستخدم",
  "No message found": "لم يتم العثور على رسالة",
  "Provider Workspace": "مساحة عمل المزود",
  "Pending Orders": "الطلبات المعلقة",
  "Manage your services, client orders, and earnings":
      "إدارة خدماتك وطلبات العملاء والأرباح",
  "Active Services": "الخدمات النشطة",
  "Total Revenue": "إجمالي الأرباح",
  "SELLER": "مزود خدمة",
  "My Services": "خدماتي",
  "Add Service": "إضافة خدمة",
  "Language": "اللغة",
  "English": "الإنجليزية",
  "Arabic": "العربية",
  "Choose language": "اختر اللغة",
  "Welcome to FUN MOMENT": "مرحبًا بك في FUN MOMENT",
  "Guest": "ضيف",
  "Explore the most requested moments first":
      "استكشف اللحظات الأكثر طلبًا أولاً",
  "Active booking and updates will appear here":
      "ستظهر الحجوزات النشطة والتحديثات هنا",
  "Personal information": "المعلومات الشخصية",
  "Default": "الافتراضي",
  "Switch to English": "التحويل إلى الإنجليزية",
  "Switch to Arabic": "التحويل إلى العربية",
  "Are you sure you want to delete": "هل أنت متأكد أنك تريد حذف",
  "Delete Service": "حذف الخدمة",
  "Provider Tools": "أدوات المزود",
  "Create listing": "إنشاء قائمة",
  "Client bookings": "حجوزات العملاء",
  "Applied jobs": "الوظائف المقدم عليها",
  "Direct invites": "دعوات مباشرة",
  "Payouts & balance": "المدفوعات والرصيد",
  "Support": "الدعم",
  "Help tickets": "تذاكر المساعدة",
  "Discover Your Perfect Moment": "اكتشف لحظتك المثالية",
  "Find DJs, entertainment, venues, and everything you need to bring your event to life.":
      "اكتشف منسقي الموسيقى والترفيه والقاعات وكل ما تحتاجه لتصنع مناسبتك.",
  "Everything for Your Event": "كل ما تحتاجه لمناسبتك",
  "From equipment and décor to catering and more, find it all in one place.":
      "من التجهيزات والديكور إلى الضيافة وأكثر، كل شيء في مكان واحد.",
  "Choose. Book. Celebrate.": "اختر. احجز. واحتفل.",
  "Compare services, book with ease, and enjoy the moment you created.":
      "قارن الخدمات، واحجز بسهولة، واستمتع باللحظة التي صنعتها.",
  "Pending Admin Approval": "قيد موافقة الإدارة",
  "Approved": "معتمد",
  "Service Submitted Successfully": "تم إرسال الخدمة بنجاح",
  "Your service has been submitted and is pending admin approval.":
      "تم إرسال الخدمة بنجاح وهي الآن قيد المراجعة والموافقة من قبل الإدارة.",
  "View My Services": "عرض خدماتي",
  "Awaiting admin approval before publishing to customers":
      "في انتظار موافقة الإدارة قبل النشر للعملاء",
  "Music & DJ": "الموسيقى والـ DJ",
  "Food & Hospitality": "الأطعمة والضيافة",
  "Sound & Lighting": "الصوت والإضاءة",
  "Event Setup & Equipment": "تجهيز الفعاليات والمعدات",
  "Decor & Event Styling": "الديكور وتنسيق المناسبات",
  "Photography & Video": "التصوير والفيديو",
  "Entertainment Activities": "الترفيه والأنشطة",
  "Saudi Arabia": "المملكة العربية السعودية",
  "Riyadh": "الرياض",
  "Olaya": "العليا",
  "Building number": "رقم المبنى",
  "Enter building number": "أدخل رقم المبنى (مثال: 1234)",
  "Additional details / Notes": "تفاصيل إضافية / ملاحظات",
  "Enter additional details (e.g. apartment, floor, landmark)": "أدخل تفاصيل إضافية (مثل: رقم الشقة، الدور، معلم مميز)",
  "District / Area": "الحي / المنطقة",
  "Street address": "عنوان الشارع",
  "Enter street address": "أدخل اسم الشارع أو العنوان",
  "Selected Location": "الموقع المحدد",
  "Please select a city and area": "يرجى اختيار المدينة والحي",
  "No cities found": "لم يتم العثور على مدن",
  "No areas found": "لم يتم العثور على أحياء",
  "Please enter a valid phone number": "يرجى إدخال رقم جوال صحيح",
  "Please enter building number": "يرجى إدخال رقم المبنى",
  "Please select a city first": "يرجى اختيار المدينة أولاً",
  "No services yet": "لا توجد خدمات حالياً",
  "No items here yet": "لا توجد خدمات هنا بعد",
  "No services available yet in this category.": "لا توجد خدمات متاحة في هذه الفئة حالياً.",
  "There are no services available right now.": "لا توجد خدمات متاحة حالياً.",
  "We could not load services": "تعذر تحميل الخدمات",
  "Please check your connection and try again.": "يرجى التحقق من اتصالك والمحاولة مرة أخرى.",
  "Registration": "التسجيل",
  "What would you like to do?": "ما الذي تود القيام به؟",
  "Book services": "حجز الخدمات",
  "Offer my services": "تقديم خدماتي",
  "Sign In": "تسجيل الدخول",
  "Sign up": "إنشاء حساب",
  "Repeat Password": "تأكيد كلمة المرور",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "You must agree to the terms and conditions": "يجب الموافقة على الشروط والأحكام",
  "You must select a city and area": "يجب اختيار المدينة والحي",
  "Fixed": "ثابت",
  "Search city": "البحث عن مدينة",
  "Failed to load cities": "تعذر تحميل المدن",
  "Failed to load areas": "تعذر تحميل الأحياء",
  "No operating areas are registered for this city yet.": "لا توجد أحياء مسجلة لهذه المدينة بعد.",
  "Could not load locations. Tap retry.": "تعذر تحميل المواقع. انقر لإعادة المحاولة.",
  "Select Location": "تحديد الموقع",
  "Provider Registration": "تسجيل مزود الخدمة",
  "Join as Service Provider": "انضم كمزود خدمة",
  "Offer your talents and services on FUN MOMENT. Account verification is reviewed by administration.": "قدم مواهبك وخدماتك على FUN MOMENT. يتم تدقيق الحساب من قبل الإدارة.",
  "Provider Type": "نوع المزود",
  "Individual": "فرد",
  "Performer, Solo, Specialist": "فنان، مؤدٍ فردي، متخصص",
  "Company": "منشأة / شركة",
  "Agency, Business, Est.": "وكالة، شركة، مؤسسة",
  "Agency, Studio, Establishment": "وكالة، استوديو، مؤسسة",
  "Account Information": "معلومات الحساب",
  "Enter full name": "أدخل الاسم الكامل",
  "Please enter full name": "يرجى إدخال الاسم الكامل",
  "Enter username": "أدخل اسم المستخدم",
  "Please enter username": "يرجى إدخال اسم المستخدم",
  "Email Address": "البريد الإلكتروني",
  "Enter email address": "أدخل عنوان البريد الإلكتروني",
  "Valid email is required": "يرجى إدخال بريد إلكتروني صحيح",
  "Phone Number": "رقم الجوال",
  "Enter password (min 8 chars)": "أدخل كلمة المرور (8 أحرف كحد أدنى)",
  "Re-enter password": "أعد إدخال كلمة المرور",
  "Identity & Qualifications": "الهوية والمؤهلات",
  "National ID / Iqama Number": "رقم الهوية الوطنية / الإقامة",
  "10-digit National ID or Iqama": "رقم الهوية أو الإقامة المكون من 10 أرقام",
  "National ID / Iqama Document": "وثيقة الهوية الوطنية / الإقامة",
  "Upload a clear photo or PDF copy": "ارفع صورة واضحة أو ملف PDF",
  "Professional License Number": "رقم الرخصة المهنية / العمل الحر",
  "Optional professional/freelance permit": "وثيقة العمل الحر أو التصريح المهني (اختياري)",
  "Professional License Document": "وثيقة الرخصة المهنية",
  "Upload if applicable": "ارفع الوثيقة إن وجدت",
  "Register as Band / Ensemble": "التسجيل كفرقة موسيقية / جماعية",
  "Enable if you represent a musical band or group": "فعل هذا الخيار إذا كنت تمثل فرقة أو مجموعة موسيقية",
  "Band / Group Name": "اسم الفرقة / المجموعة",
  "Enter band name": "أدخل اسم الفرقة",
  "Number of Members": "عدد الأعضاء",
  "Minimum 2 members": "عضوان على الأقل",
  "Company & Commercial Registration": "بيانات الشركة والسجل التجاري",
  "Company / Agency Name": "اسم الشركة / المؤسسة",
  "Registered company name": "اسم المنشأة المسجل رسمياً",
  "Commercial Registration (CR) Number": "رقم السجل التجاري",
  "10-digit CR number": "رقم السجل التجاري المكون من 10 أرقام",
  "CR Certificate Document": "شهادة السجل التجاري",
  "Official CR document (PDF or image)": "وثيقة السجل التجاري الرسمية (PDF أو صورة)",
  "Contact Person Details": "بيانات مسؤول التواصل",
  "Contact Person Name": "اسم مسؤول التواصل",
  "Authorized representative": "الممثل المفوض",
  "Contact Person Email": "البريد الإلكتروني لمسؤول التواصل",
  "Contact Person Phone": "رقم جوال مسؤول التواصل",
  "Offered Service Categories": "فئات الخدمات المقدمة",
  "selected": "محدد",
  "Select all services you can provide": "حدد جميع الخدمات التي يمكنك تقديمها",
  "Unable to load categories": "تعذر تحميل الفئات",
  "Location & Operating Area": "الموقع ونطاق العمل",
  "Street, District, Building": "الشارع، الحي، المبنى",
  "Postal Code": "الرمز البريدي",
  "Postal code (optional)": "الرمز البريدي (اختياري)",
  "I agree with the terms and conditions and provider policies": "أوافق على الشروط والأحكام وسياسات مزودي الخدمة",
  "Submit Provider Application": "تقديم طلب مزود الخدمة",
  "(Optional)": "(اختياري)",
  "Optional": "اختياري",
  "Upload document (PDF / JPG / PNG)": "ارفع المستند (PDF / JPG / PNG)",
  "Replace": "استبدال",
  "Remove": "حذف",
  "Only PDF, JPG, JPEG, and PNG files are supported": "صيغ الملفات المدعومة هي PDF وJPG وJPEG وPNG فقط",
  "File size must be under 10MB": "يجب أن يكون حجم الملف أقل من 10 ميغابايت",
  "Failed to select file": "تعذر اختيار الملف",
  "Full name is required": "الاسم الكامل مطلوب",
  "Email is required": "البريد الإلكتروني مطلوب",
  "Username is required": "اسم المستخدم مطلوب",
  "Please enter a username": "يرجى إدخال اسم المستخدم",
  "Phone number is required": "رقم الجوال مطلوب",
  "Please enter your phone number": "يرجى إدخال رقم الجوال",
  "City is required": "المدينة مطلوبة",
  "Please select a city": "يرجى اختيار المدينة",
  "Area is required": "الحي مطلوب",
  "Please select an area": "يرجى اختيار الحي",
  "At least one service category is required": "يجب اختيار فئة خدمة واحدة على الأقل",
  "Please select at least one service category": "يرجى اختيار فئة خدمة واحدة على الأقل",
  "National ID / Iqama number is required": "رقم الهوية الوطنية أو الإقامة مطلوب",
  "Please enter your National ID or Iqama number": "يرجى إدخال رقم الهوية الوطنية أو الإقامة",
  "National ID document is required": "وثيقة الهوية الوطنية أو الإقامة مطلوبة",
  "Please upload your National ID or Iqama document": "يرجى رفع وثيقة الهوية أو الإقامة",
  "Document must be PDF, JPG, JPEG, or PNG": "يجب أن يكون الملف بصيغة PDF أو JPG أو JPEG أو PNG",
  "National ID must be a PDF, JPG, or PNG file": "يجب أن تكون وثيقة الهوية بصيغة PDF أو JPG أو PNG",
  "License must be PDF, JPG, JPEG, or PNG": "يجب أن تكون الرخصة بصيغة PDF أو JPG أو JPEG أو PNG",
  "License must be a PDF, JPG, or PNG file": "يجب أن تكون الرخصة بصيغة PDF أو JPG أو PNG",
  "Band / Group name is required": "اسم الفرقة أو المجموعة مطلوب",
  "Please enter your band or group name": "يرجى إدخال اسم الفرقة أو المجموعة",
  "Band must have at least 2 members": "يجب أن تضم الفرقة عضوين على الأقل",
  "Company name is required": "اسم المنشأة مطلوب",
  "Please enter the registered company name": "يرجى إدخال اسم المنشأة المسجل",
  "Commercial Registration (CR) number is required": "رقم السجل التجاري مطلوب",
  "Please enter the CR number": "يرجى إدخال رقم السجل التجاري",
  "CR certificate document is required": "شهادة السجل التجاري مطلوبة",
  "Please upload the CR document": "يرجى رفع وثيقة السجل التجاري",
  "CR document must be PDF, JPG, JPEG, or PNG": "يجب أن تكون وثيقة السجل التجاري بصيغة PDF أو JPG أو JPEG أو PNG",
  "CR document must be a PDF, JPG, or PNG file": "يجب أن تكون وثيقة السجل التجاري بصيغة PDF أو JPG أو PNG",
  "Contact person name is required": "اسم مسؤول التواصل مطلوب",
  "Please enter the contact person name": "يرجى إدخال اسم مسؤول التواصل",
  "Contact person email is required": "البريد الإلكتروني لمسؤول التواصل مطلوب",
  "Please enter the contact person email": "يرجى إدخال البريد الإلكتروني لمسؤول التواصل",
  "Contact person phone is required": "رقم جوال مسؤول التواصل مطلوب",
  "Please enter the contact person phone": "يرجى إدخال رقم جوال مسؤول التواصل",
  "Account already created. Please verify your email.": "تم إنشاء الحساب بالفعل. يرجى تأكيد بريدك الإلكتروني.",
  "Registration successful. Please verify your email.": "تم التسجيل بنجاح. يرجى تأكيد بريدك الإلكتروني.",
  "Registration failed": "فشل التسجيل",
  "Validation failed. Please check your data.": "فشل التحقق. يرجى مراجعة البيانات المدخلة.",
  "Registration request timed out. Please check your connection and try again.": "انتهت مهلة طلب التسجيل. يرجى التحقق من الاتصال والمحاولة مجدداً.",
  "Verify Code": "تأكيد الرمز",
  "Please enter the 4 digit code": "يرجى إدخال الرمز المكون من 4 أرقام",
  "Did not receive": "لم يصلك الرمز؟",
  "OTP sent successfully": "تم إرسال رمز التحقق بنجاح",
  "Verification code is missing. Please tap \"Send again\".": "رمز التحقق مفقود. يرجى النقر على \"إعادة الإرسال\".",
  "Verification timed out. Please try again.": "انتهت مهلة التحقق. يرجى المحاولة مرة أخرى.",
  "Network error: Unable to reach email service": "خطأ في الشبكة: تعذر الوصول إلى خدمة البريد",
  "Connection error during verification. Please try again.": "خطأ في الاتصال أثناء التحقق. يرجى المحاولة مرة أخرى.",
  "Network connection failed. Please check your internet and try again.": "فشل الاتصال بالشبكة. يرجى التحقق من اتصالك والمحاولة مجدداً.",
  "The email has already been taken.": "البريد الإلكتروني مستخدم بالفعل.",
  "The username has already been taken.": "اسم المستخدم مستخدم بالفعل.",
  "The phone has already been taken.": "رقم الجوال مستخدم بالفعل.",
  "The password must be at least 8 characters.": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.",
  "Notifications": "الإشعارات",
  "Mark all read": "تحديد الكل كمقروء",
  "No notifications yet": "لا توجد إشعارات حتى الآن",
  "Updates about your bookings and orders will appear here": "ستظهر التحديثات الخاصة بحجوزاتك وطلباتك هنا",
  "New Booking Alert": "تنبيه حجز جديد",
  "Booking Confirmed": "تم تأكيد الحجز",
  "Booking Cancelled": "تم إلغاء الحجز",
  "Booking Completed": "اكتمل الحجز",
  "Payment Confirmed": "تم تأكيد الدفع",
  "Booking Update": "تحديث الحجز",
  "PayTabs": "بي تابس (PayTabs)",
  "Payment successfully verified!": "تم التحقق من الدفع بنجاح!",
  "Payment failed": "فشلت عملية الدفع",
  "No categories yet": "لا توجد فئات حتى الآن",
  "Categories will appear here when the backend has records.": "ستظهر الفئات هنا بمجرد توفرها في النظام.",
  "Top Booked Services": "الخدمات الأكثر حجزاً",
  "View More": "عرض المزيد",
  "Booking Submitted": "تم تقديم الحجز",
  "Enter your name": "أدخل اسمك",
  "Please enter a valid email": "يرجى إدخال بريد إلكتروني صحيح",
  "No payment methods available": "لا تتوفر طرق دفع حالياً",
  "Please check back later or contact customer support.": "يرجى المحاولة لاحقاً أو التواصل مع خدمة العملاء.",
  "Previous Week": "الأسبوع السابق",
  "Next Week": "الأسبوع التالي",
  "Scheduling for:": "الجدولة لـ:",
  "Sub total": "المجموع الفرعي",
  "Extras": "إضافات",
  "My Availability": "أوقات التوفر",
  "Chat": "المحادثة",
  "Please enter order id": "يرجى إدخال رقم الطلب",
  "Please enter your email or username": "يرجى إدخال بريدك الإلكتروني أو اسم المستخدم",
  "Please enter a valid password": "يرجى إدخال كلمة مرور صحيحة",
  ...saudiLocationStrings,
};

