// Auto-generated authoritative Saudi location strings
// Sourced from official Saudi National Address / SPL geography
const Map<String, String> saudiLocationStrings = {
  "'Inak": "عنك",
  "1 C": "حي ج1",
  "14th Brigade Housing": "سكن مجموعة اللواء الرابع عشر",
  "1st Industrial": "حي الصناعية الاولى",
  "1st Industrial Area": "المنطقة الصناعية الاولى",
  "2 C": "حي ج2",
  "2nd Industrial": "حي الصناعية الثانية",
  "2nd Industrial Area": "المنطقة الصناعية الثانية",
  "2nd Industrial City": "المدينة الصناعية الثانية",
  "3rd Industrial Area": "المنطقة الصناعية الثالثة",
  "3rd Industrial City": "المدينة الصناعية الثالثة",
  "4 C": "حي ج4",
  "5 C": "حي ج5",
  "Aba Al Ablan 1": "حي أبا العبلان1",
  "Aba Al Ablan 2": "حي أبا العبلان2",
  "Aba Al Khareet": "حي أبا الخريـت",
  "Aba Al Rashash": "حي ابا الرشاش",
  "Aba Al Saud": "حي أبا السعود",
  "Abdullah Al Eyafi (Al Eyafi)": "عبدالله العيافي (العيافي)",
  "Abha": "ابها",
  "Abhur Al Janubiyah": "حي ابحر الجنوبية",
  "Abhur Ash Shamaliyah": "حي ابحر الشمالية",
  "Ableya": "حي عبلية",
  "Abruq Ar Rughamah": "حي ابرق الرغامة",
  "Abu Al Hasa": "بلدة أبو الحصى",
  "Abu Al Maqrah": "ابوالمقره",
  "Abu Alkarsh": "ابو الكرش",
  "Abu Altuyur": "ابو الطيور",
  "Abu Arish": "ابو عريش",
  "Abu As Sala": "ابو السلع",
  "Abu Ath Thoor": "بلدة أبو ثور",
  "Abu Burayqa": "حي ابو بريقاء",
  "Abu Danqur": "ابو دنقور",
  "Abu Hareef": "حي ابوحريف",
  "Abu Jaalah": "حي أبو جعالة",
  "Abu Kabir": "حي ابو كبير",
  "Abu Main": "حي ابو معن",
  "Abu Musa Al Ashari": "حي ابو موسى الاشعري",
  "Abu Musa Alashary": "حي ابو موسى الاشعري",
  "Abu Sahbal 1st": "حي بو سحبل الأول",
  "Abu Sahbal 3rd": "حي بو سحبل الثاني",
  "Abu Salim": "حي ابو سليم",
  "Abu Shajarah": "حي ابو شجرة",
  "Abu Shuayb": "حي أبو شعيب",
  "Abu Sidr": "حى ابو سدر",
  "Abu Urwah": "حي أبو عروة",
  "Abumarkha": "حي ابومرخة",
  "Abyar Al Mashi": "حي ابيار الماشي",
  "Academic Quarter": "الحي الأكاديمي",
  "Ad Dabab": "حي الضباب",
  "Ad Dababiyyah": "حي الدبابية",
  "Ad Daghmiyah": "حي الدغمية",
  "Ad Dahi": "حي الضاحي",
  "Ad Dahiah": "حي الضاحية",
  "Ad Dahlah": "حي الدحلة",
  "Ad Danah": "حي الدانة",
  "Ad Danah Al Janubiyah": "حي الدانة الجنوبية",
  "Ad Danah Ash Shamaliyah": "حي الدانة الشمالية",
  "Ad Dar": "حي الدرع",
  "Ad Darib": "حي الضريب",
  "Ad Dawair": "حي الدوائر",
  "Ad Dawasir": "حي الدواسر",
  "Ad Dawhah": "حي الدوحة",
  "Ad Dawhah Al Janubiyah": "حي الدوحة الجنوبية",
  "Ad Dawhah Ash Shamaliyah": "حي الدوحة الشمالية",
  "Ad Daywan": "حي الديوان",
  "Ad Difa": "حي الدفاع",
  "Ad Dilam": "الدلم",
  "Ad Dir'iyah": "الدرعية",
  "Ad Dirah": "حي الديرة",
  "Ad Dirah Al Qadimah": "حي الديرة القديمة",
  "Ad Dirs": "حي الضرس",
  "Ad Diyafah": "حي الضيافة",
  "Ad Doij": "حي الدويج",
  "Ad Duf": "حي الدف",
  "Ad Duraydi": "حي الدريدي",
  "Ad Durrah": "حي الدرة",
  "Ad Duwadimi": "الدوادمي",
  "Ad Duwaikhilah": "حي الدويخلة",
  "Ad Duwaimah": "حي الدويمة",
  "Adh Dhahrah": "حي الظهرة",
  "Adh Dhilal": "حي الظلال",
  "Afif": "عفيف",
  "Ahad": "حي أحد",
  "Ahad Al Musarihah": "احد المسارحة",
  "Ahad Rifaydah": "احد رفيده",
  "Air Defense Forces": "حي قوات الدفاع الجوي",
  "Airforce Housing": "سكن القاعدة الجوية",
  "Airport": "المطار",
  "Aja": "حي اجا",
  "Ajyad": "حي اجياد",
  "Ajyal": "أجيال",
  "Akhbab": "حي الاخباب",
  "Al 'Aridah": "العارضة",
  "Al 'Ulayya": "حي العليا",
  "Al 'Uwayqiliyah": "العويقلية",
  "Al Aan": "حي العان",
  "Al Aarmiah 1": "حي العارمية 1",
  "Al Aarmiah 2": "حي العارمية 2",
  "Al Abdaliyah": "حي العبدلية",
  "Al Abeer": "حي العبير",
  "Al Abraqeen": "حي الابرقين",
  "Al Absiah": "حي العبسة",
  "Al Adalah": "حي العدالة",
  "Al Adamah": "حي العدامة",
  "Al Adari'": "الأضارع",
  "Al Addayah": "العداية",
  "Al Adel": "حي العدل",
  "Al Adhra": "حي العذراء",
  "Al Adl": "حي العدل",
  "Al Adwah": "حي العدوة",
  "Al Afrah": "حي الافراح",
  "Al Aghar": "حي الأغر",
  "Al Ahsa": "حي الاحساء",
  "Al Ahsa Airport": "مطار الأحساء",
  "Al Ain": "حي العين",
  "Al Ajaweed": "حي الاجاويد",
  "Al Ajwad": "حي الاجواد",
  "Al Akha": "حي الاخاء",
  "Al Akhdar": "حي الاخضر",
  "Al Alam": "حي العلم",
  "Al Alawat": "حي العلوات",
  "Al Aliyah": "حي العالية",
  "Al Allawah": "حي العلاوة",
  "Al Amal": "حي الامل",
  "Al Amamrah": "حي العمامرة",
  "Al Amanah": "حي الأمانه الاداري",
  "Al Amar": "حي العمار",
  "Al Amarah": "حي الامارة",
  "Al Amaridah": "العمارده",
  "Al Amariyah": "حي العمارية",
  "Al Amir Fawaz Al Janouby": "حي الامير فواز الجنوبى",
  "Al Amir Fawaz Ash Shamaly": "حي الامير فواز الشمالى",
  "Al Ammajiyah": "حي العماجية",
  "Al Ammariyah": "حي العمارية",
  "Al Amwaj": "حي الامواج",
  "Al Anabis": "حي العنابس",
  "Al Anahi": "حي الاناهي",
  "Al Anam City": "مدينة الانعام",
  "Al Andalus": "حي الاندلس",
  "Al Anqari": "حي العنقري",
  "Al Anud": "حي العنود",
  "Al Anwar": "حي الانوار",
  "Al Aqar": "بلدة العقار",
  "Al Aqeeq": "حي العقيق",
  "Al Aqiq": "حي العقيق",
  "Al Aqishiyah": "حي العقيشية",
  "Al Aqoul": "حي العاقول",
  "Al Aqrabiyah": "حي العقربية",
  "Al Arak": "حي الاراك",
  "Al Aramiyah": "قرية العرامية",
  "Al Ardah": "العرضه",
  "Al Ardhiyah Al Shimaliyah": "العرضية الشمالية",
  "Al Arid": "حي العارض",
  "Al Arin": "حي العرين",
  "Al Arish": "حي العريش",
  "Al Ariydh": "حي العريض",
  "Al Arjeen": "العرجين",
  "Al Artawiyah": "الارطاوية",
  "Al Asalah": "حي الاصالة",
  "Al Asdaf": "حي الاصداف",
  "Al Aseelah": "حي العسيلة",
  "Al Asemah": "حي العاصمة",
  "Al Asfar": "حي الاصفر",
  "Al Ashah": "العشة",
  "Al Asheyrah": "حي العشيرة",
  "Al Ashrafiyah": "حي الاشرفية",
  "Al Asimah": "حي العاصمة",
  "Al Asla": "حي العسلاء",
  "Al Aswaq": "حي الأسواق",
  "Al Asyah": "الاسياح",
  "Al Athaybah": "حي الاثايبة",
  "Al Athir": "حي الأثير",
  "Al Athlah": "الأثلة",
  "Al Atlal": "حي الاطلال",
  "Al Aujam": "حي الاوجام",
  "Al Awadhyah": "بلدة العوضية",
  "Al Awal Dist. Al Awal": "الحي الاول",
  "Al Awali": "حي العوالي",
  "Al Awaly": "حي العوالي",
  "Al Awamiyah": "حي العوامية",
  "Al Awniyah": "حي العونية",
  "Al Azhar": "حي الازهار",
  "Al Aziziyah": "حي العزيزية",
  "Al Aziziyah 1st": "حي العزيزية الأول",
  "Al Aziziyah 2nd": "حي العزيزية الثاني",
  "Al Aziziyah Al Jadidah": "حي العزيزيه الجديده",
  "Al Aziziyah Al Qadimah": "حي العزيزية القديمة",
  "Al Bada": "حي البدع",
  "Al Badai'": "البدائع",
  "Al Badayi": "حي البدائع",
  "Al Badi": "حي البديع",
  "Al Badi Al Gharbi": "حي البديع الغربي",
  "Al Badi Ash Sharqi": "حي البديع الشرقي",
  "Al Badiah": "حي البديعة",
  "Al Badiyah": "حي البادية",
  "Al Badnah": "حي البدنة",
  "Al Badr": "حي البدر",
  "Al Badriyah": "حي البدرية",
  "Al Baghdadiyah Al Gharbiyah": "حي البغدادية الغربية",
  "Al Baghdadiyah Ash Sharqiyah": "حي البغدادية الشرقية",
  "Al Bahah": "الباحة",
  "Al Bahar": "حي البحر",
  "Al Bahari": "حي البحاري",
  "Al Baher": "حي الباهر",
  "Al Bahir": "الباحر",
  "Al Bahr": "حي البحر",
  "Al Baida": "حي البيضاء",
  "Al Balad": "حي البلد",
  "Al Balad Al Qadimah": "حي البلد القديمة",
  "Al Baladiah": "حي البلدية",
  "Al Baladiyah": "حي البلدية",
  "Al Balda Al Qadimah": "حي البلدة القديمة",
  "Al Balqa": "حي البلقاء",
  "Al Banafsaj": "حي البنفسج",
  "Al Bandar": "حي البندر",
  "Al Bandariyah": "حي البندرية",
  "Al Baraam": "حي البراعم",
  "Al Barakah": "حي البركة",
  "Al Bariyah": "حي البرية",
  "Al Bark": "حي البارك",
  "Al Barqa": "حي البرقاء",
  "Al Basatin": "حي البساتين",
  "Al Basatin Administrative Eastern": "حي البساتين الاداري الشرقي",
  "Al Basatin Administrative Western": "حي البساتين الاداري الغربي",
  "Al Bashaer": "حي البشائر",
  "Al Basirah": "حي البصيرة",
  "Al Basrah": "حي البصرة",
  "Al Batha": "حي البطحاء",
  "Al Bathnah": "حي البثنة",
  "Al Batin": "حي الباطن",
  "Al Batinah": "الباطنه",
  "Al Battaliyah": "بلدة البطالية",
  "Al Bawadi": "حي البوادي",
  "Al Bayan": "حي البيان",
  "Al Bayatirah": "حي البياطرية",
  "Al Bhira": "حي البحيره",
  "Al Bibyan": "حي البيبان",
  "Al Bijadiyah": "البجادية",
  "Al Bilad": "حي البلاد",
  "Al Biqa": "حي البقاع",
  "Al Biyah": "حي البيعة",
  "Al Blaida": "حي البليدا",
  "Al Buaiten": "حي البويطن",
  "Al Budur": "حي البدور",
  "Al Buhayrah": "حي البحيرة",
  "Al Buhayrat": "حي البحيرات",
  "Al Bukayriyah": "البكيرية",
  "Al Buraydah": "حي البريدة",
  "Al Burj": "حي البرج",
  "Al Burouj": "حي البروج",
  "Al Burud": "حي البرود",
  "Al Busairah": "حي البصيرة",
  "Al Bustan": "حي البستان",
  "Al Butaiha": "حي البطيحا",
  "Al Dabab": "حي الضباب",
  "Al Dagharir": "حي الدغارير",
  "Al Daheeqi": "الدحيقي",
  "Al Dahna": "حي الدهناء",
  "Al Dahou": "حي الدحو",
  "Al Daika": "حي الدعيكة",
  "Al Dalwah": "بلدة الدالوة",
  "Al Dana": "حي الدانة",
  "Al Danah": "حي الدانة",
  "Al Dar Al Baida": "حي الدار البيضاء",
  "Al Darah West": "حي غرب الدارة",
  "Al Dawahishah": "الدواحشه",
  "Al Dawayhi": "حي الضويحي",
  "Al Deriyah": "حي الدرعية",
  "Al Dhabt": "حي الضبط",
  "Al Dhabyah": "حي الظبية",
  "Al Dhahab": "حي الذهب",
  "Al Dhahira": "حي الظهيره",
  "Al Dhahirah": "حي الظاهرة",
  "Al Dhahra West": "حي غرب الظهره",
  "Al Dhamiria": "حي الضميرية",
  "Al Dhanbh": "حي الذنبه",
  "Al Dhubbat": "حي الضباط",
  "Al Dhurfah": "حي الظرفة",
  "Al Difa": "حي الدفاع",
  "Al Difaa": "حي الدفاع",
  "Al Dil": "حي الضلع",
  "Al Dirah": "حي الديرة",
  "Al Diriyah": "حي الدرعية",
  "Al Diyabiyah": "حي الذيابية",
  "Al Doha": "حي الدوحة",
  "Al Dohah": "حي الدوحة",
  "Al Dubiyah": "حي الدوبية",
  "Al Duraihemiyah": "حي الدريهمية",
  "Al Estrahat": "حي الاستراحات",
  "Al Estrahat Al Awsat": "حي الاستراحات الأوسط",
  "Al Estrahat Al Gharbi": "حي الاستراحات الغربي",
  "Al Estrahat Al Sharqi": "حي الاستراحات الشرقي",
  "Al Eyun": "حي العيون",
  "Al Ezdihar": "حي الازدهار",
  "Al Fadel": "حي الفضل",
  "Al Fadeylah": "حي الفضيلة",
  "Al Fahd": "حي الفهد",
  "Al Faisal": "حي الفيصل",
  "Al Faisaliyah": "حي الفيصلية",
  "Al Faisaliyah 1st": "حي الفيصلية الأول",
  "Al Faisaliyah 2nd": "حي الفيصلية الثاني",
  "Al Fakamah": "حي الفخامة",
  "Al Fakhiriyah": "حي الفاخرية",
  "Al Fakhriyah": "حي الفاخرية",
  "Al Fal": "حي الفل",
  "Al Falah": "حي الفلاح",
  "Al Falaj": "حي الفلج",
  "Al Fanar": "حي الفنار",
  "Al Faqrah": "الفقره",
  "Al Fara": "حي الفرعة",
  "Al Farah": "حي الفرعة",
  "Al Fardus": "حي الفردوس",
  "Al Fareah": "حي الفريعة",
  "Al Farnisiyyah Ash Sharqiyyah": "حي الفرنيسية الشرقية",
  "Al Farooq": "حي الفاروق",
  "Al Farouk": "حي الفاروق",
  "Al Farouq": "حي الفاروق",
  "Al Fath": "حي الفتح",
  "Al Faw": "حي الفاو",
  "Al Fayha": "حي الفيحاء",
  "Al Fayziyah": "حي الفايزية",
  "Al Ferdous": "حي الفردوس",
  "Al Fiqarah": "الفقرة",
  "Al Firdaws": "حي الفردوس",
  "Al Fisalah Wal Dagharih": "الفصاله والدغاريه",
  "Al Frosyah": "حي الفروسية",
  "Al Fudul": "بلدة الفضول",
  "Al Fuhaid": "حي الفهيد",
  "Al Furaysh": "حي الفريش",
  "Al Furqan": "حي الفرقان",
  "Al Fursan": "حي الفرسان",
  "Al Futah": "حي الفوطة",
  "Al Ghabah": "حي الغابة",
  "Al Ghadeer": "حي الغدير",
  "Al Ghadir": "حي الغدير",
  "Al Ghannamiyah": "حي الغنامية",
  "Al Gharbi": "الحي الغربي",
  "Al Gharbiyyah": "حي الغربية",
  "Al Gharibiya": "حي الغريبية",
  "Al Gharra": "حي الغراء",
  "Al Gharraa": "الغراء",
  "Al Ghat": "الغاط",
  "Al Ghazalah": "حي الغزالة",
  "Al Ghazwah": "حى الغزوة",
  "Al Ghtght": "حي الغطغط",
  "Al Ghumayr": "حي الغمير",
  "Al Ghurub": "حي الغروب",
  "Al Ghusainiah": "حي الغصينية",
  "Al Ghuwayla B": "حي الغويلا ب",
  "Al Ghuzlani": "حي الغزلاني",
  "Al Goth": "حي الغوث",
  "Al Hada": "حي الهدا",
  "Al Hadaa": "حي الهداء",
  "Al Hadabah": "حي الهضبة",
  "Al Hadaek": "حي الحدائق",
  "Al Hadidiyah": "حي الحديدية",
  "Al Hadiqah": "حي الحديقة",
  "Al Hadn": "حي الحضن",
  "Al Hadra": "حي الهدراء",
  "Al Haer": "حي الحائر",
  "Al Hafil": "حي الحفل",
  "Al Hafira Al Gharbi": "حي الحفيرة الغربي",
  "Al Hafira Al Sharqi": "حي الحفيرة الشرقي",
  "Al Hafnah": "حي الحفنة",
  "Al Hafuf": "الهفوف",
  "Al Hafya": "حي الحفيا",
  "Al Hajariah": "الهجاريه",
  "Al Hajeb": "حي الحاجب",
  "Al Hajlah": "حي الهجلة",
  "Al Halah At Taliyah": "حي الحلة الطالعية",
  "Al Halaliyah": "حي الهلالية",
  "Al Halilah": "بلدة الحليلة",
  "Al Halqah Al Gharbia": "حي الحلقة الغربية",
  "Al Halqah Asharqiyyah": "حي الحلقة الشرقية",
  "Al Hamadaniyah": "حي الحمدانية",
  "Al Hamra": "حي الحمراء",
  "Al Hamra 1st": "حي الحمراء الأول",
  "Al Hamra 2nd": "حي الحمراء الثاني",
  "Al Hamra 3rd": "حي الحمراء الثالث",
  "Al Hamra Umm Al Jud": "حي الحمراء وام الجود",
  "Al Hanabijah": "حي الحنابجة",
  "Al Hano": "حي الحنو",
  "Al Harabi": "حي الحرابى",
  "Al Harajah": "الحرجة",
  "Al Haram": "حي الحرم",
  "Al Haram Al Sharif": "الحرم الشريف",
  "Al Haramain": "حي الحرمين",
  "Al Haras Al Watani": "حي الحرس الوطني",
  "Al Harazat": "حي الحرازات",
  "Al Hariq": "الحريق",
  "Al Harir Al Sharqi": "حي الهرير الشرقى",
  "Al Harir Western": "حي الهرير الغربى",
  "Al Harthiyah": "حي الحارثية",
  "Al Hasamah": "حي الحصامة",
  "Al Hawamidah Jahish": "الحوامضه جحيش",
  "Al Hawra": "حي الحوراء",
  "Al Hayathim": "الهياثم",
  "Al Hayirah": "حي الحايرة",
  "Al Haylah Al Gharbi": "حي الحيلة الغربي",
  "Al Haylah Ash Sharqi": "حي الحيلة الشرقي",
  "Al Hazaiyah": "حي الهزاعية",
  "Al Hazm": "حي الحزم",
  "Al Hazm Northern": "حي الحزم الشمالي",
  "Al Hazm Southern": "حي الحزم الجنوبي",
  "Al Hejin": "حي الهجن",
  "Al Helali": "حي الهلالي",
  "Al Hidaya": "حي الهداية",
  "Al Hijaz": "حي الحجاز",
  "Al Hijrah": "حي الهجرة",
  "Al Hilah": "حي الحلة",
  "Al Hilal": "حي الهلال",
  "Al Hilaliyah": "الهلالية",
  "Al Hilwah": "الحلوة",
  "Al Hinakiyah": "الحناكية",
  "Al Hindawiyah": "حي الهنداوية",
  "Al Hisa": "حى الحساء",
  "Al Hiwaya": "الحواية",
  "Al Hizam Adh Dhahabi": "حي الحزام الذهبي",
  "Al Hizam Al Akhdar": "حي الحزام الاخضر",
  "Al Hizam Ash Sharqi": "حي الحزام الشرقي",
  "Al Hotah": "قرية الحوطة",
  "Al Hoymel": "حي ال هويمل",
  "Al Huda": "حي الهدا",
  "Al Hufayrah": "حي الحفيرة",
  "Al Hufuf": "حي الهفوف",
  "Al Hujjaj": "حي الحجاج",
  "Al Hujun": "حي الحجون",
  "Al Humar": "حي الحمر",
  "Al Humaydah": "حي الحميضه",
  "Al Humaydah South": "حي جنوب الحميضه",
  "Al Humaylah": "حي ال هميلة",
  "Al Humayrat": "حي الحميرات",
  "Al Husain": "حي الحسين",
  "Al Husayn": "حي الحصين",
  "Al Hushaibriyah": "الحشيبرية",
  "Al Hussaini": "حي الحسيني",
  "Al Hussam": "حي الحسام",
  "Al Hutah": "حي الحوطة",
  "Al Huwaya": "حي الحوية",
  "Al Huwaylat": "حي الحويلات",
  "Al Huzaimiyah": "حي الحزيمية",
  "Al Huzaymiyyah": "حي الحزيمية",
  "Al Idari": "حي الادارى",
  "Al Idhaah": "حي الاذاعة",
  "Al Idhaah North": "حي شمال الاذاعة",
  "Al Ihn": "حي العهن",
  "Al Ihtifalat": "حي الاحتفالات",
  "Al Irq Al Janubi": "حي العرق الجنوبي",
  "Al Irq Ash Shamali": "حي العرق الشمالي",
  "Al Isawiyah": "العيساوية",
  "Al Ishrafiyah": "حي الاشرافية",
  "Al Iskan": "حي الإسكان",
  "Al Iskan 1st": "حي الإسكان الأول",
  "Al Iskan 2nd": "حي الإسكان الثاني",
  "Al Iskan Al Janubi": "حي الإسكان الجنوبي",
  "Al Iskan Al Khairy": "حي الاسكان الخيرى",
  "Al Iskan Northren": "حي الاسكان الشمالي",
  "Al Itisalat": "حي الاتصالات",
  "Al Itsalat": "حي الإتصالات",
  "Al Izdihar": "حي الازدهار",
  "Al Izz": "حي العز",
  "Al Ja Hospital": "حي المستشفى الجا",
  "Al Jabal": "حي الجبل",
  "Al Jabhan": "حي الجبهان",
  "Al Jabirah": "حي الجابرة",
  "Al Jabriyah": "حي الجابرية",
  "Al Jadid": "حي الجديد",
  "Al Jadidah": "حي الجديدة",
  "Al Jaeawunah": "الجعاونه",
  "Al Jafer Northern": "حي الجفر الشمالي",
  "Al Jaffuniyyah": "حي الجفونية",
  "Al Jafijif": "حي الجفيجف",
  "Al Jafr": "بلدة الجفر",
  "Al Jal": "حي الجال",
  "Al Jalawiyah": "حي الجلوية",
  "Al Jaldah": "حي الجلده",
  "Al Jamawat": "حي الجماوات",
  "Al Jamiah": "حي الجامعة",
  "Al Jamiah Al Awsat": "حي الجامعة الاوسط",
  "Al Jamiah Al Gharbi": "حي الجامعة الغربي",
  "Al Jamiah Al Sharqi": "حي الجامعة الشرقي",
  "Al Jamie": "حي الجامعي",
  "Al Jamieyah": "الجامعية",
  "Al Jamiyin": "حي الجامعيين",
  "Al Jammalah": "الجمالة",
  "Al Janadriyah": "حي الجنادرية",
  "Al Jandal": "حي الجندل",
  "Al Janub": "حي الجنوب",
  "Al Jar": "حي الجار",
  "Al Jaradiyah": "حي الجرادية",
  "Al Jarah Al Qadiumah": "الجاره القديمه",
  "Al Jarboeyyah": "الجربوعية",
  "Al Jardah": "حي الجردة",
  "Al Jarn": "بلدة الجرن",
  "Al Jarradiyah": "حي الجرادية",
  "Al Jarrari": "حي الجراري",
  "Al Jarudiyah": "حي الجارودية",
  "Al Jassah": "حي الجصة",
  "Al Jawa": "الجوى",
  "Al Jawahir": "حي الجواهر",
  "Al Jawhara": "حي الجوهرة",
  "Al Jawharah": "حي الجوهرة",
  "Al Jazeerah": "حي الجزيرة",
  "Al Jazirah": "حي الجزيرة",
  "Al Jazur": "حي الجزر",
  "Al Jidiayn": "الجديين",
  "Al Jish": "الجش",
  "Al Jishah": "بلدة الجشة",
  "Al Jisr": "حي الجسر",
  "Al Jubail": "بلدة الجبيل",
  "Al Jud": "حي الجود",
  "Al Judr": "حي الجدر",
  "Al Judr Al Gharbi": "حي الجدر الغربي",
  "Al Judr Al Sharqi": "حي الجدر الشرقي",
  "Al Jufaidariyah": "حي الجفيدرية",
  "Al Jumah": "حي الجمعة",
  "Al Jumaimah": "حي الجميمة",
  "Al Jumayma": "حي الجميماء",
  "Al Jummayzah": "حي الجميزة",
  "Al Jumum": "الجموم",
  "Al Juraif": "حي الجريف",
  "Al Jurbah": "حي الجربة",
  "Al Jurdiyyah": "حي الجردية",
  "Al Juzu Al Shamali": "حي الجزء الشمالي",
  "Al Kada": "حي الغضا",
  "Al Kakiyah": "حي الكعكية",
  "Al Kalabah": "الكلبه",
  "Al Kandarah": "حي الكندرة",
  "Al Karamah": "حي الكرامة",
  "Al Kawthar": "حي الكوثر",
  "Al Khabib": "حي الخبيب",
  "Al Khabra Al Qadima": "حي الخبراء القديمة",
  "Al Khabra'": "الخبراء",
  "Al Khadhra": "حى الخضراء",
  "Al Khadra": "حي الخضراء",
  "Al Khadra Al Qadimah": "حي الخضراء القديمة",
  "Al Khadraa": "الخضراء",
  "Al Khafji": "الخفجي",
  "Al Khair": "حي الخير",
  "Al Khaleej": "حي الخليج",
  "Al Khaleej Eastern": "حي الخليج الشرقي",
  "Al Khaleej Wesrtern": "حي الخليج الغربي",
  "Al Khalid": "حي الخالد",
  "Al Khalidiyah": "حي الخالدية",
  "Al Khalidiyah Al Janubiyah": "حي الخالدية الجنوبية",
  "Al Khalidiyah Ash Shamaliyah": "حي الخالدية الشمالية",
  "Al Khalij": "حي الخليج",
  "Al Khamashiyah": "حي الخماشية",
  "Al Khamasin": "حي الخماسين",
  "Al Khamasin Al Shamali": "حي الخماسين الشمالي",
  "Al Khamisah": "حي الخامسة",
  "Al Khansa": "حي الخنساء",
  "Al Kharisha": "الخريشاء",
  "Al Kharj": "الخرج",
  "Al Kharj Industrial City": "المدينة الصناعية بالخرج",
  "Al Khasha": "حي الخشع",
  "Al Khatim": "حي الخاتم",
  "Al Khatrashiyah": "حي الخترشية",
  "Al Khawajih": "الخواجيه",
  "Al Khawarah": "الخواره",
  "Al Khawr": "حي الخور",
  "Al Khazzan": "حى الخزان",
  "Al Khisab": "حي الخصاب",
  "Al Khobar": "الخبر",
  "Al Khobara": "حي الخبراء",
  "Al Khomrah": "حي الخمرة",
  "Al Khubar Al Janubiyah": "حي الخبر الجنوبية",
  "Al Khubar Ash Shamaliyah": "حي الخبر الشمالية",
  "Al Khudar": "حي الخضر",
  "Al Khudud": "حي الخدود",
  "Al Khuraa": "حي الخرعاء",
  "Al Khuraymi": "حي الخريمي",
  "Al Khurmah": "الخرمة",
  "Al Khuwaildiyah": "حي الخويلدية",
  "Al Khuzama": "حي الخزامى",
  "Al Khyam": "حي الخيام",
  "Al Kilabiyah": "بلدة الكلابية",
  "Al Kilabiyah Housing": "حي اسكان الكلابية",
  "Al Koot": "حي الكوت",
  "Al Kurnaish": "حي الكورنيش",
  "Al Kuthriah": "حي الخضرية",
  "Al Lakhabsia": "اللخبصية",
  "Al Laqitah": "حي اللقيطة",
  "Al Lith": "الليث",
  "Al Loaloa": "حي اللؤلؤ",
  "Al Lualu": "حي اللؤلؤ",
  "Al Lubdah": "حي اللبدة",
  "Al Ludam Al Janubi": "حي اللدام الجنوبي",
  "Al Ludam Al Shamali": "حي اللدام الشمالي",
  "Al Lujain": "حي اللجين",
  "Al Lulu": "حي اللؤلؤ",
  "Al Luluah": "حي اللؤلؤة",
  "Al Lusayb": "حي اللسيب",
  "Al Luwaymi": "حي اللويمي",
  "Al Maabdah": "حي المعابدة",
  "Al Maamir": "حي المعامر",
  "Al Maamrah": "حي المعامرة",
  "Al Maarid": "حي المعارض",
  "Al Maatala": "حي المعتلا",
  "Al Mabarakiyah": "حي المباركية",
  "Al Mabna Al Janubi": "حي المبنى الجنوبي",
  "Al Mabna Al Shamali": "حي المبنى الشمالي",
  "Al Mabuth": "حي المبعوث",
  "Al Madaen": "حي المدائن",
  "Al Madani": "حي المدني",
  "Al Madarat Subdivision Plan": "مخطط المدارات",
  "Al Madaris": "حي المدارس",
  "Al Madinah": "حي المدينة",
  "Al Madinah Al Jadidah": "حي المدينة الجديدة",
  "Al Madinah Al Munawwarah": "حي المدينة المنورة",
  "Al Mafrahat": "حى المفرحات",
  "Al Magassah": "حي المجصة",
  "Al Magda": "حي المقضى",
  "Al Magharbah": "المغاربة",
  "Al Maha": "حي المها",
  "Al Mahamid": "حي المحاميد",
  "Al Mahar": "حي المحار",
  "Al Mahash": "حي المحاش",
  "Al Mahasih": "المحاصيه",
  "Al Mahattah": "حي المحطة",
  "Al Mahdiyah": "حي المهدية",
  "Al Mahjar": "حي المحجر",
  "Al Mahrajan A": "حي المهرجان أ",
  "Al Mahrajan B": "حي المهرجان ب",
  "Al Maizalah": "حي المعيزلة",
  "Al Majami": "حي المجامع",
  "Al Majardah": "المجاردة",
  "Al Majd": "حي المجد",
  "Al Majidiyah": "حي المجيدية",
  "Al Majma'ah": "المجمعة",
  "Al Malaz": "حي الملز",
  "Al Malik": "حي الملك",
  "Al Mallah": "حي الملاح",
  "Al Malqa": "حي الملقا",
  "Al Malqah": "حي الملقاه",
  "Al Mamurah": "حي المعمورة",
  "Al Manakh": "حي المناخ",
  "Al Manakhah": "حي المناخة",
  "Al Manar": "حي المنار",
  "Al Manarat": "حي المنارات",
  "Al Manfuhah": "حي المنفوحة",
  "Al Manhal": "حي المنهل",
  "Al Mansur": "حي المنصور",
  "Al Mansurah": "حي المنصورة",
  "Al Mansuriyah": "حي المنصورية",
  "Al Manzam": "حي المنزم",
  "Al Maqaiid": "حي المقاعد",
  "Al Marah": "بلدة المراح",
  "Al Marath": "حي المراث",
  "Al Marbidia": "حي المربدية",
  "Al Marjan": "حي المرجان",
  "Al Marjaniyah": "حي المرجانية",
  "Al Markab": "حي المركب",
  "Al Markaz": "بلدة المركز",
  "Al Markazia": "حي المركزية",
  "Al Marmuthah": "المرموثة",
  "Al Marmuthah Ash Shamaliyah": "المرموثة الشمالية",
  "Al Marqab": "حي المرقب",
  "Al Marwah": "حي المروة",
  "Al Masani": "حي المصانع",
  "Al Masarah": "حي المسرة",
  "Al Masbah": "حي المسبعة",
  "Al Maseef": "حي المصيف",
  "Al Mashair": "حي المشاعر",
  "Al Mashriq": "حي المشرق",
  "Al Mashtal": "حي المشتل",
  "Al Masiaf": "حي المصيف",
  "Al Masif": "حي المصيف",
  "Al Masif 1": "حي المصيف الاول",
  "Al Maslakh": "حي المسلخ",
  "Al Masmat": "حي المسماة",
  "Al Masudi": "حي المسعودي",
  "Al Masudiyah": "حي المسعودية",
  "Al Masyaf": "حي المصايف",
  "Al Matar": "حي المطار",
  "Al Matar Subdivision Plan": "مخطط المطار",
  "Al Mathaf": "حي المتحف",
  "Al Mathar": "حي المعذر",
  "Al Mathawiyah": "حي المثوية",
  "Al Mathnah": "حي المثناه",
  "Al Matl": "حي المطل",
  "Al Matr": "حي المطر",
  "Al Matrafiyah": "حي المطرفية",
  "Al Mawfijah": "حي الموفجة",
  "Al Mawj": "حي الموج",
  "Al Mawta": "حي الموطا",
  "Al Mazari": "حي المزارع",
  "Al Mazawi": "بلدة المزاوي",
  "Al Mazrooa 1st": "حي المزروع الاول",
  "Al Mazrooa 2nd": "حي المزروع الثاني",
  "Al Mazruiyah": "حي المزروعية",
  "Al Merqab": "حي المرقاب",
  "Al Midan": "حي الميدان",
  "Al Midhnab": "المذنب",
  "Al Mihan": "حي المهن",
  "Al Mihaniyin": "حي المهنيين",
  "Al Miqdam": "بلدة المقدام",
  "Al Mirqab": "حي المرقاب",
  "Al Misadiyah": "حي المساعدية",
  "Al Misfalah": "حي المسفلة",
  "Al Misfat": "حي المصفاة",
  "Al Mishael": "حي المشاعل",
  "Al Misk": "حي المسك",
  "Al Mizab": "حي الميزاب",
  "Al Montazah": "حي المنتزة",
  "Al Moulysaa": "حي المليساء",
  "Al Muallimeen": "حي المعلمين",
  "Al Muaqilah": "حي المعاقلة",
  "Al Muatala": "حي المعتلاء",
  "Al Muatala Al Janubi": "حي المعتلاء الجنوبي",
  "Al Muayzeleh": "حي المعيزيله",
  "Al Mubarakiyah": "حي المباركية",
  "Al Mubarkiah": "حي المباركية",
  "Al Mubarraz": "حي المبرز",
  "Al Mudairy": "المديري",
  "Al Mudhbah": "حي المضباع",
  "Al Mudwiah": "حي المدوية",
  "Al Muftahah": "حي المفتاحة",
  "Al Mughaisilah": "حي المغيسلة",
  "Al Mughams": "حي المغمس",
  "Al Mughrazat": "حي المغرزات",
  "Al Muhammadiyah": "حي المحمدية",
  "Al Muhandisin": "حي المهندسين",
  "Al Muhdaj": "حي المهدج",
  "Al Mukheem": "حي المخيم",
  "Al Mulaylih": "حي المليليح",
  "Al Mulha 1": "حي الملحة 1",
  "Al Mulha 2": "حي الملحة 2",
  "Al Munaizilah": "حي المنيزله",
  "Al Munaizlah": "بلدة المنيزلة",
  "Al Mundasa": "حي المندسة",
  "Al Munisiyah": "حي المونسية",
  "Al Muntazah": "حي المنتزه",
  "Al Muntazah Al Gharbi": "حي المنتزه الغربي",
  "Al Muntazah Ash Sharqi": "حي المنتزه الشرقي",
  "Al Muntazahat": "حي المنتزهات",
  "Al Munyfiyah": "حي المنيفية",
  "Al Muqabil": "حي المقابل",
  "Al Muqayti": "حي المقيطع",
  "Al Murabba": "حي المربع",
  "Al Murabba Al Khadamy": "المربع الخدمي",
  "Al Muraikabat": "حي المريكبات",
  "Al Muraikhiyah": "حي المريخية",
  "Al Muraiqeb": "حي المريقب",
  "Al Muraydisiyyah": "حي المريديسية",
  "Al Murjan": "حي المرجان",
  "Al Mursalat": "حي المرسلات",
  "Al Mursi": "حي المرسي",
  "Al Murtafat": "حي المرتفعات",
  "Al Muruj": "حي المروج",
  "Al Muruj 1": "حي المروج الاول",
  "Al Muruj 2": "حي المروج الثاني",
  "Al Muruj 3": "حي المروج الثالث",
  "Al Muruj Eastern": "حي المروج الشرقي",
  "Al Muruj Northern": "حي المروج الشمالي",
  "Al Muruj Southern": "حي المروج الجنوبي",
  "Al Muruj Wesrtern": "حي المروج الغربي",
  "Al Musa Subdivision Plan": "مخطط الموسى",
  "Al Musaidiyah": "حي المساعدية",
  "Al Mushayrif": "حي المشيريف",
  "Al Musherfah": "حي مشيرفة",
  "Al Mustaqbal": "حي المستقبل",
  "Al Mustashfa": "حي المستشفي",
  "Al Mustashfa Al Askari": "حي المستشفى العسكري",
  "Al Mustashfi": "حي المستشفي",
  "Al Mutalla": "حي المطلع",
  "Al Mutamarat": "حي المؤتمرات",
  "Al Mutanazahat": "حي المتنزهات",
  "Al Mutarid": "حي المعترض",
  "Al Mutarida": "حي المعترضة",
  "Al Mutawakil": "حي المتوكل",
  "Al Mutayrifi": "بلدة المطيرفي",
  "Al Mutayrifi Al Garbi": "حي المطيرفي الغربي",
  "Al Muthalath": "حي المثلث",
  "Al Muthanna": "حي المثناه",
  "Al Muutarid": "حي المعترض",
  "Al Muzaabar": "حي المزعبر",
  "Al Muzahimiyah": "المزاحمية",
  "Al Muzairah": "حي المزيرعة",
  "Al Muzayiyn": "حي المزيين",
  "Al Naathel": "حي النعاثل",
  "Al Nada": "حي الندى",
  "Al Nadheem": "حي النظيم",
  "Al Nadwah": "حي الندوة",
  "Al Naeamia": "النعامية",
  "Al Nafel": "حي النفل",
  "Al Nafl": "حي النفل",
  "Al Nahdah": "حي النهضة",
  "Al Naim": "حي النعيم",
  "Al Nakhbah": "حي النخبة",
  "Al Nakheel": "حي النخيل",
  "Al Nakheel Northern": "حي النخيل الشمالي",
  "Al Nakheel Southern": "حي النخيل الجنوبي",
  "Al Nakhil": "حي النخيل",
  "Al Nakhil Al Gharbi": "حي النخيل الغربي",
  "Al Nakhil Al Sharqi": "حي النخيل الشرقي",
  "Al Namudhajiyah": "حي النموذجية",
  "Al Naqiea": "حي النقيعه",
  "Al Narjis": "حي النرجس",
  "Al Naseem": "حي النسيم",
  "Al Nasfah": "حي الناصفه",
  "Al Nasiriyah": "حي الناصرية",
  "Al Natouf": "حى النطوف",
  "Al Nawah": "حي النواة",
  "Al Nijabah Wal Jahajih": "النجابه و الجحاجح",
  "Al Noor": "حي النور",
  "Al Nur": "حي النور",
  "Al Nuwaisifah": "النويصفة",
  "Al Nuwayemah": "حي النويعمة",
  "Al Nuzha": "حي النزهة",
  "Al Nuzhah": "حي النزهة",
  "Al Olab": "حي العلب",
  "Al Olaya": "حي العليا",
  "Al Omaraa": "حي الأمراء",
  "Al Orjwan Eastern": "حي الارجوان الشرقي",
  "Al Orjwan Wesrtern": "حي الارجوان الغربي",
  "Al Oud": "حي العود",
  "Al Oyon Southern": "حي العيون الشمالية",
  "Al Oyoun": "حي العيون",
  "Al Qaa": "حي القاع",
  "Al Qaa Al Barid": "حي القاع البارد",
  "Al Qabil": "حي القابل",
  "Al Qadih": "حي القديح",
  "Al Qadirah": "حي القديرة",
  "Al Qadisiyah": "حي القادسية",
  "Al Qadisiyah 1": "حي القادسية الاول",
  "Al Qadisiyah 2": "حي القادسية الثاني",
  "Al Qafilah": "حي القافلة",
  "Al Qairawan": "حي القيروان",
  "Al Qalah": "حي القلعة",
  "Al Qarah": "بلدة القارة",
  "Al Qararah And An Naqa": "حي القرارة والنقا",
  "Al Qaren": "بلدة القرين",
  "Al Qari": "حي القري",
  "Al Qasab": "القصب",
  "Al Qasadah": "القصاده",
  "Al Qashlah": "حي القشلة",
  "Al Qassima": "حي القسيمة",
  "Al Qasum": "حي القسوم",
  "Al Qaswa": "حي القصواء",
  "Al Qatif": "القطيف",
  "Al Qawaea": "القواعة",
  "Al Qawz": "حي القوز",
  "Al Qayam Al Aala": "حي القيم الأعلى",
  "Al Qayam Al Asfal": "حي القيم الأسفل",
  "Al Qayrawan": "حي القيروان",
  "Al Qaysumah": "القيصومة",
  "Al Qazaz": "حي القزاز",
  "Al Qeer": "آل قير",
  "Al Qiblatayn": "حي القبلتين",
  "Al Qifayfah": "حي القفيفة",
  "Al Qirawan": "حي القيروان",
  "Al Qitar": "حي القطار",
  "Al Qouzeen": "حي القوزين",
  "Al Qryniah": "حي القرينية",
  "Al Quds": "حي القدس",
  "Al Quds Eastern": "حي القدس الشرقي",
  "Al Quds Wesrtern": "حي القدس الغربي",
  "Al Qumariyyah": "حي القمرية",
  "Al Qumish": "حي القميش",
  "Al Qunfidhah": "القنفذة",
  "Al Quoziyah": "القوزية",
  "Al Qura": "حي القرى",
  "Al Quraiyat": "حي القريات",
  "Al Qurayyat": "القريات",
  "Al Qus": "حي القوس",
  "Al Qusayah": "حي القصيعة",
  "Al Qusor": "حي القصور",
  "Al Qusur": "حي القصور",
  "Al Qutbiyyah": "حي القطبية",
  "Al Quwaiz": "حي القويز",
  "Al Quway'iyah": "القويعية",
  "Al Rabea": "الحي الرابع",
  "Al Rabiyah": "حي الرابية",
  "Al Rabwah": "حي الربوة",
  "Al Radifah": "حي الرديفة",
  "Al Raed": "حي الرائد",
  "Al Rafie": "الرافعي",
  "Al Rafiea": "حي الرفيعة",
  "Al Rajai": "حي الرجع",
  "Al Rajhi Subdivision Plan": "مخطط الراجحي",
  "Al Rajie": "الرجيع",
  "Al Raqi": "حي الراقي",
  "Al Rashidiyah": "حي الراشدية",
  "Al Rawabi": "حي الروابي",
  "Al Rawama": "حي الرواما",
  "Al Rawasee": "حي الرواسي",
  "Al Rawdah": "حي الروضة",
  "Al Rawdha": "حي الروضة",
  "Al Rayah": "حي الراية",
  "Al Rayan": "حي الريان",
  "Al Rayan Al Gharbi": "حي الريان الغربي",
  "Al Rayan Al Sharqi": "حي الريان الشرقي",
  "Al Rayaniyah": "حي الريعانية",
  "Al Rayyan": "حي الريان",
  "Al Rehab": "حي الرحبة",
  "Al Rif": "حي الريف",
  "Al Rimal": "حي الـرمال",
  "Al Rimayah": "حي الرماية",
  "Al Risalah": "حي الرسالة",
  "Al Rooqiyah": "حي الروقية",
  "Al Ruwaidaf": "حي الرويدف",
  "Al Ruwaikibah": "حي الرويكبة",
  "Al Ruwaysa": "حي الرويساء",
  "Al Ruzayqiyah": "حي الرزيقية",
  "Al Saadah": "حي السعادة",
  "Al Sabaa": "حي أم السباع",
  "Al Sabakhah": "السبخة",
  "Al Sabghan": "حي الصبغان",
  "Al Sadr": "حي الصدر",
  "Al Safa": "حي الصفا",
  "Al Safat": "حي الصفاة",
  "Al Safat 1": "حي الصفاه الاول",
  "Al Safat 2": "حي الصفاه الثاني",
  "Al Safh": "حي الصفح",
  "Al Safhah": "حي الصفحة",
  "Al Safwah": "حي الصفوة",
  "Al Sahab": "حي السحاب",
  "Al Sahafah": "حي الصحافة",
  "Al Sahl": "حي السهل",
  "Al Sahluj": "حى الصهلوج",
  "Al Sahnah": "حي الصحنة",
  "Al Sahwa": "حى الصهوة",
  "Al Salam": "حي السلام",
  "Al Salmaniyah": "حي السلمانية",
  "Al Salmaniyah 1st": "حي السلمانية الأول",
  "Al Salmaniyah 2nd": "حي السلمانية الثاني",
  "Al Salmaniyah 3rd": "حي السلمانية الثالث",
  "Al Salmaniyah 4th": "حي السلمانية الرابع",
  "Al Samh": "حي السمح",
  "Al Samikh": "الصامخ",
  "Al Samriyah": "حي السمرية",
  "Al Sarhiyah": "حي السرحية",
  "Al Saruriyah": "السروريه",
  "Al Sawaiq": "حي السويق",
  "Al Sawaiqa": "حي السويقة",
  "Al Sawalimah": "السوالمه",
  "Al Sawari": "حي الصواري",
  "Al Shaakhir": "الشاخر",
  "Al Shabhan": "حي الشبهان",
  "Al Shaeafah": "الشعافه",
  "Al Shaeifan": "حي الشعيفان",
  "Al Shagaibiyah": "حي الشغيبية",
  "Al Shamali": "حي الشمالي",
  "Al Shamalia": "حي الشمالية",
  "Al Shamas": "حي الشماس",
  "Al Shamuh": "الشمه",
  "Al Sharafiyah": "حي الشرفية",
  "Al Sharayie": "حي الشرائع",
  "Al Sharqiyyah": "حي الشرقية",
  "Al Shati": "حي الشاطئ",
  "Al Shatiniyyah": "حي الشتينية",
  "Al Shawahiyah": "الشواهية",
  "Al Shawajirat Wal Jarabiyah": "الشواجرة والجرابية",
  "Al Shiarah": "الشعاره",
  "Al Shifa": "حي الشفا",
  "Al Shinanah Al Janubiyah": "حي الشنانة الجنوبية",
  "Al Shinanah Ash Shamaliyyah": "حي الشنانة الشمالية",
  "Al Shiqafah Wal Musawafa": "الشقافه والمصاوفة",
  "Al Shlal": "حي الشلال",
  "Al Shohda": "حي الشهداء",
  "Al Sholah": "حي الشعلة",
  "Al Shorouk": "حي الشروق",
  "Al Shorouq": "حي الشروق",
  "Al Shuaba": "حي الشعبة",
  "Al Shuaibah": "حي الشعيبة",
  "Al Shumaisi": "حي الشميسي",
  "Al Shumua": "حي الشموع",
  "Al Shurafa": "حي الشرفا",
  "Al Shurafa Industrial": "حي صناعية الشرفا",
  "Al Shurofiyah": "حي الشروفية",
  "Al Shuwaidhi": "حي الشويضي",
  "Al Siana": "حي الصيانة",
  "Al Sidrah": "حي السدرة",
  "Al Silm": "حي السلم",
  "Al Silm Al Qadim": "حى السلم القديم",
  "Al Sinaiyah": "حي الصناعية",
  "Al Subh": "حي الصبح",
  "Al Sulaimaniyah": "حي السليمانية",
  "Al Sulay": "حي السلي",
  "Al Sulaymaniyah": "حي السليمانية",
  "Al Sulimaniyah": "حي السليمانية",
  "Al Sultanah": "حي السلطانة",
  "Al Sultanih": "حي السلطانيه",
  "Al Sumayri": "حي السميري",
  "Al Suquriyyah": "حي الصقورية",
  "Al Suraif": "حي الصريف",
  "Al Suwaidi": "حي السويدي",
  "Al Taawun": "حي التعاون",
  "Al Tadamun": "حي التضامن",
  "Al Talaah": "حي التلعة",
  "Al Talal": "حي التلال",
  "Al Talayah": "حي الطالعية",
  "Al Tamim Wal Salihiyyah": "حي ال تميم و الصالحية",
  "Al Taqniyah": "حي التقنية",
  "Al Tawyah": "حي الطوية",
  "Al Teseen": "حي التسعين",
  "Al Thalith": "الحي الثالث",
  "Al Thani": "الحي الثاني",
  "Al Thilaima": "حي الثليما",
  "Al Thulaythiyah": "حي الثليثية",
  "Al Turaif": "حي الطريف",
  "Al Turaifi": "حي الطريفي",
  "Al Turshiah": "حي الطرشية",
  "Al Tuwaifah": "الطويفح",
  "Al Tuwaythir": "حي التويثير",
  "Al Ubaylah": "حي العبيلة",
  "Al Ufuq": "حي الافق",
  "Al Ujaybah": "حي العجيبة",
  "Al Ukayshiyah": "حي العكيشية",
  "Al Ukhdud": "حي الاخدود",
  "Al Ula": "العلا",
  "Al Ummal": "حي العمال",
  "Al Umrah Al Jadidah": "حي العمرة الجديدة",
  "Al Umran": "العمران",
  "Al Umran Eastern": "قرية العمران الشرقية",
  "Al Umran Southern": "قرية العمران الجنوبي",
  "Al Umran Western": "قرية العمران الغربية",
  "Al Uqdah": "حي العقدة",
  "Al Uraija": "حي العريجاء",
  "Al Uraimah": "حي ال عريمة",
  "Al Uraymdi": "حي العريمضي",
  "Al Uraysah": "حي العريسة",
  "Al Urj Al Aala": "حي العرج الأعلى",
  "Al Urj Al Asfal": "حي العرج الأسفل",
  "Al Urubah": "حي العروبة",
  "Al Usayfirin": "حي الاصيفرين",
  "Al Usaylah": "حي العسيلة",
  "Al Usayli": "حي العصيلي",
  "Al Usbah": "حي العصبة",
  "Al Ushayriyyah": "حي العشيرية",
  "Al Utaybiyah": "حي العتيبية",
  "Al Uthmaniyah": "حي العثمانية",
  "Al Uud": "حي العود",
  "Al Uwaimir": "حي آل عويمر",
  "Al Uwaimiriyah": "حي العويمرية",
  "Al Uwaymiriyah": "حي العويمرية",
  "Al Uyainah": "العيينة",
  "Al Uyun": "العيون",
  "Al Waad": "حي الوعد",
  "Al Wadi": "حي الوادي",
  "Al Wadiah": "حي الوديعه",
  "Al Wafa": "حي الوفاء",
  "Al Wahah": "حي الواحة",
  "Al Wahah Medical": "حي الواحة الطبية",
  "Al Wahlan": "حي الوهلان",
  "Al Wajh": "الوجه",
  "Al Wakf": "حي الوقف",
  "Al Walamin": "حي الولامين",
  "Al Waqba": "حي الوقبة",
  "Al Waqwaq": "حي الوقواق",
  "Al Wardatain": "حي الوردتين",
  "Al Wasadah": "حي الوسادة",
  "Al Wasaif": "حي الوصايف",
  "Al Wasam": "حي الوسام",
  "Al Waseel": "حي الوصيل",
  "Al Washha": "حي الوشحاء",
  "Al Washm": "حي الوشم",
  "Al Wasit": "حي الواسط",
  "Al Wasitah": "حي الوسيطة",
  "Al Wasl": "حي الوصل",
  "Al Waziran": "حي الوزران",
  "Al Waziriyah": "حي الوزيريه",
  "Al Wazyah": "بلدة الوزية",
  "Al Weaam": "حي الوئام",
  "Al Wisham": "حي الوشام",
  "Al Wizarat": "حي الوزارات",
  "Al Woroud": "حي الورود",
  "Al Wurud": "حي الورود",
  "Al Wurud 1": "حي الورود 1",
  "Al Wurud 1st": "حي الورود الأول",
  "Al Wurud 2nd": "حي الورود الثاني",
  "Al Wurud 3rd": "حي الورود الثالث",
  "Al Wusayta": "حي الوسيطا",
  "Al Wusta": "حي الوسطة",
  "Al Yamam": "حي اليمام",
  "Al Yamamah": "حي اليمامة",
  "Al Yaqoot": "حي الياقوت",
  "Al Yaqut": "حي الياقوت",
  "Al Yarmok": "حي اليرموك",
  "Al Yarmouk": "حي اليرموك",
  "Al Yarmuk": "حي اليرموك",
  "Al Yasmeen": "حي الياسمين",
  "Al Yasmin": "حي الياسمين",
  "Al Yusr": "حي اليسر",
  "Al Zaafran": "حي الزعفران",
  "Al Zaher": "حي الزاهر",
  "Al Zahour": "حي الزهور",
  "Al Zahra": "حي الزهراء",
  "Al Zahrah": "حي الزهرة",
  "Al Zahur": "حي الزهور",
  "Al Zaqlah": "الزقله",
  "Al Zawiyah": "حي الزاوية",
  "Al Zayni": "الزيني",
  "Al Zaytun": "حي الزيتون",
  "Al Ziniyah": "الزينيه",
  "Al Zuaibah": "حي الزعيبة",
  "Al Zuhur": "حي الزهور",
  "Al Zuwayra": "حي الزويراء",
  "Albatih": "البطيح",
  "Aleabduh": "العبده",
  "Aleasiluh": "العسيله",
  "Aleawajimuh": "العواجمه",
  "Alghawbia Agricultural Area": "منطقة الغويبة الزراعية",
  "Alhadwaa": "الهدوى",
  "Alhajarayn": "الحجرين",
  "Alhaqawih": "الحقاويه",
  "Alharaf": "الحرف",
  "Alhasat": "الحصاة",
  "Alhimdih": "الحمضيه",
  "Alkah": "حي علقة",
  "Alkawmuh": "الكومه",
  "Alkhawaliduh": "الخوالده",
  "Almajdiruh": "المجديره",
  "Alnzlh": "النزلـــه",
  "Alqrahin": "حي القراحين",
  "Alsanif": "الصنيف",
  "Alsidaduh": "السداده",
  "Alt Arashah": "الطراشه",
  "Alwurud": "حي الورود",
  "Alzaydiuh": "الزيديه",
  "An Nabhaniyah": "النبهانية",
  "An Nabiyah": "حي النابية",
  "An Nada": "حي الندى",
  "An Nadheem": "حي النظيم",
  "An Nafl": "حي النفل",
  "An Nahdah": "حي النهضة",
  "An Naim": "حي النعيم",
  "An Naimiyah": "حي الناعمية",
  "An Najah": "حي النجاح",
  "An Najmah": "حي النجمة",
  "An Namas": "النماص",
  "An Namudhajiyah": "حي النموذجية",
  "An Naqa": "حي النقع",
  "An Naqabah": "حي النقابة",
  "An Naql": "حي النفل",
  "An Naqrah": "حي النقرة",
  "An Naqrah Qafar": "حي النقرة قفار",
  "An Narjis": "حي النرجس",
  "An Nasb": "حي النصب",
  "An Naseem": "حي النسيم",
  "An Nasifah": "حي الناصفة",
  "An Nasirah": "حي الناصرة",
  "An Nasiyah": "حي النيصية",
  "An Nasriyah": "حي الناصرية",
  "An Nawras": "حي النورس",
  "An Nawwariyah": "حي النوارية",
  "An Nayfiyah": "حي النايفية",
  "An Nazlah Al Yamaniyah": "حي النزلة اليمانية",
  "An Nazlah Ash Sharqiyah": "حي النزلة الشرقية",
  "An Ngma": "حي الـنقـمى",
  "An Nofoad": "حي النفود",
  "An Noor": "حي النور",
  "An Nu'ayriyah": "النعيرية",
  "An Nujayl": "حي النجيل",
  "An Nuqailiah": "حي النقيلية",
  "An Nur": "حي النور",
  "An Nuzhah": "حي النزهة",
  "Anak": "حي عنك",
  "Aqraba": "حي عقرباء",
  "Ar Rabah": "حي الربعة",
  "Ar Rabeiyah": "حي الربيعية",
  "Ar Rabiah": "حي الرابعة",
  "Ar Rabie": "حي الربيع",
  "Ar Rabiyah": "حي الرابية",
  "Ar Rabwah": "حي الربوة",
  "Ar Radifah Wal Rafeiyah": "حي الرديفة والرافعية",
  "Ar Rafayie": "حي الرفايع",
  "Ar Rafiah": "حي الرفيعة",
  "Ar Rahmah": "حي الرحمة",
  "Ar Rahmaniyah": "حي الرحمانية",
  "Ar Raid": "حي الرائد",
  "Ar Raihan": "حي الريحان",
  "Ar Raja": "حي الرجاء",
  "Ar Rakah Al Janubiyah": "حي الراكة الجنوبية",
  "Ar Rakah Ash Shamaliyah": "حي الراكة الشمالية",
  "Ar Rakubah": "حي الركوبة",
  "Ar Ramthyah": "حي الرمثية",
  "Ar Ranuna": "حي الرانوناء",
  "Ar Rasf": "حي الرصف",
  "Ar Rashidiyah": "حي الراشدية",
  "Ar Rashidiyyah": "حي الراشدية",
  "Ar Rashidyah 1st": "حي الراشدية الأول",
  "Ar Rashidyah 2nd": "حي الراشدية الثاني",
  "Ar Rashidyah 3rd": "حي الراشدية الثالث",
  "Ar Rasras 1": "حي الرصراص 1",
  "Ar Rasras 2": "حي الرصراص 2",
  "Ar Rass": "الرس",
  "Ar Ratibah": "حي الرتبة",
  "Ar Rawabi": "حي الروابي",
  "Ar Rawdah": "حي الروضة",
  "Ar Rawdah 1": "حي الروضه 1",
  "Ar Rawdah Al Janubiyyah": "حي الروضة الجنوبية",
  "Ar Rawdah Ash Shamaliyyah": "حي الروضة الشمالية",
  "Ar Rawdhah": "حي الروضة",
  "Ar Rawghani": "حي الروغاني",
  "Ar Rawnah": "الرونة",
  "Ar Rayaan": "حي الريان",
  "Ar Rayah": "حي الراية",
  "Ar Rayan": "حي الريان",
  "Ar Rayn": "الرين",
  "Ar Rayn Al Aala": "حي الرين الاعلى",
  "Ar Rayn Al Qadim": "حي الرين القديم",
  "Ar Rayyan": "حي الريان",
  "Ar Refah Northern": "حي الرفعة الشمالية",
  "Ar Refah Southern": "حي الرفعة الجنوبية",
  "Ar Rekaz": "حي الركاز",
  "Ar Rida": "حي الرضا",
  "Ar Rif": "حي الريف",
  "Ar Rifaa": "حي الرفاع",
  "Ar Rimal": "حي الرمال",
  "Ar Rimmah": "حي الرمة",
  "Ar Riyadh": "حي الرياض",
  "Ar Riyadh 1st": "حي الرياض الاول",
  "Ar Riyadh 2nd": "حي الرياض الثاني",
  "Ar Riyadh 3rd": "حي الرياض الثالث",
  "Ar Riyadh 4th": "حي الرياض الرابع",
  "Ar Riyadi": "حي الرياضى",
  "Ar Riyan": "حي الريان",
  "Ar Ruddaf": "حي الردف",
  "Ar Rukiyah": "حي الركية",
  "Ar Rumanah": "حي الرمانة",
  "Ar Rumaylah": "قرية الرميلة",
  "Ar Runah": "حي الرونه",
  "Ar Ruqaiqah": "حي الرقيقة",
  "Ar Rusayfah": "حي الرصيفة",
  "Ar Ruwad": "حي الرواد",
  "Ar Ruwaida": "حي الرويضة",
  "Ar Ruwaihah": "حي الرويحة",
  "Ar Ruwais": "حي الرويس",
  "Ar Ruwaydah": "الرويضة",
  "Aramco": "حي ارامكو",
  "Aramco Property": "محجوزات ارمكو",
  "Arar": "عرعر",
  "As Saadah": "حي السعادة",
  "As Sabaiykh": "بلدة الصبايخ",
  "As Sabat": "بلدة السباط",
  "As Sabbakh": "حي الصباخ",
  "As Sabil": "حي السبيل",
  "As Sabkhah": "حي السبخة",
  "As Sabuh": "حي الصبوح",
  "As Sad": "حي السد",
  "As Sadad": "حي السداد",
  "As Sadafah": "حي الصدفة",
  "As Sadah": "حي السادة",
  "As Sadd": "حي السد",
  "As Sadiliyah": "حي السادلية",
  "As Sadiqiyah": "حي الصادقية",
  "As Sadr": "الصدر",
  "As Safa": "حي الصفا",
  "As Safa 1st": "حي الصفا الاول",
  "As Safa 2nd": "حي الصفا الثاني",
  "As Safa 3rd": "حي الصفا الثالث",
  "As Safa 4th": "حي الصفا الرابع",
  "As Safra": "حي الصفراء",
  "As Safraa": "حي الصفراء",
  "As Sahab": "حي السحاب",
  "As Sahabin Al Janubi": "حي السحابين الجنوبي",
  "As Sahabin Ash Shamali": "حي السحابين الشمالي",
  "As Sahafah": "حي الصحافة",
  "As Sahifah": "حي الصحيفة",
  "As Sahil": "حي الساحل",
  "As Sahlah": "حي السهلة",
  "As Saif": "حي السيف",
  "As Saifa": "حي السيفة",
  "As Sail Al Kabeer": "حي السيل الكبير",
  "As Sakb": "حي السكب",
  "As Salam": "حي السلام",
  "As Salam 1st": "حي السلام الأول",
  "As Salam 2nd": "حي السلام الثاني",
  "As Salamah": "حي السلامة",
  "As Salhiyah": "حي الصالحية",
  "As Salihiyah": "حي الصالحية",
  "As Salman": "حي السلمان",
  "As Salmiya": "حي السالمية",
  "As Samad": "حي الصمد",
  "As Samari": "حي السماري",
  "As Samir": "حي السامر",
  "As Samra": "حي السمراء",
  "As Sanabel": "حي السنابل",
  "As Saqar": "حي الصقًار",
  "As Sarawat": "حي السروات",
  "As Sarur": "حي السرور",
  "As Saudia": "حي السعودية",
  "As Sawaer": "حي الصواير",
  "As Sawari": "حي الصواري",
  "As Saydan": "حي السعيدان",
  "As Sayyadih": "حي الصيادية",
  "As Sediq": "حي الصديق",
  "As Sieh": "حي السيح",
  "As Sih": "حي السيح",
  "As Silah": "حي السلاح",
  "As Silayyib Al Gharbi": "حي الصليب الغربي",
  "As Silayyib Ash Sharqi": "حي الصليب الشرقي",
  "As Sinaiiyah": "حي الصناعية",
  "As Sinaiyah": "حي الصناعية",
  "As Sororyah": "حي السرورية",
  "As Suda": "حي السودة",
  "As Sudah": "السودة",
  "As Sufun": "حي السفن",
  "As Suhaimiyah": "حي السحيمية",
  "As Suhaymiyyah": "حي السحيمية",
  "As Sukhayrat": "حي الصخيرات",
  "As Sulaimaniyah": "حي السليمانية",
  "As Sulaymaniyah": "حي السليمانية",
  "As Sulayyil": "السليل",
  "As Sulimaniyah": "حي السليمانية",
  "As Sunaidah": "حي السنيدية",
  "As Sunbulah": "حي السنبلة",
  "As Suq": "حي السوق",
  "As Suq Al Qadim": "حي السوق القديم",
  "As Suqur": "حي الصقور",
  "As Suqya": "حي السقيا",
  "As Suwaidirah": "حي صويدرة",
  "As Suwaydra": "حي الصويدرة",
  "As Suwayfilah": "حي السويفلة",
  "As Suways": "حي السويس",
  "As Swaryee": "حي الصوارى",
  "As Syayrah": "قرية السيايرة",
  "Asfan": "حي أصفان",
  "Ash Shafaq": "حي الشفق",
  "Ash Shafiyah": "حي الشافية",
  "Ash Shaharin": "بلدة الشهارين",
  "Ash Shahba": "حي الشهباء",
  "Ash Shahd": "حي الشهد",
  "Ash Shakah": "حي الشاقة",
  "Ash Shalhub": "حي الشلهوب",
  "Ash Shamal": "حي الشمال",
  "Ash Shamasiyyah": "حي الشماسيه",
  "Ash Shamel": "حي الشامل",
  "Ash Shamiyah": "حي الشامية",
  "Ash Shamli": "الشملي",
  "Ash Shammas": "حي الشماس",
  "Ash Shaqiq Eastern": "بلدة الشقيق الشرقية",
  "Ash Shaqiq Western": "بلدة الشقيق الغربية",
  "Ash Shara Northern": "حي الشراع الشمالي",
  "Ash Shara Southern": "حي الشراع الجنوبي",
  "Ash Sharafiyah": "حي الشرفية",
  "Ash Sharia": "حي الشرائع",
  "Ash Shariah": "حي الشريعة",
  "Ash Sharq": "حي الشرق",
  "Ash Sharqiyyah": "حي الشرقية",
  "Ash Shatha": "حي الشذا",
  "Ash Shati": "حي الشاطئ",
  "Ash Shati Al Gharbi": "حي الشاطئ الغربي",
  "Ash Shati Ash Sharqi": "حي الشاطئ الشرقي",
  "Ash Shawqiyah": "حي الشوقية",
  "Ash Shayrami": "حي الشيرمي",
  "Ash Shefaa": "حي الشفا",
  "Ash Sheraa": "حي الشراع",
  "Ash Shibilyah": "حي الشبيلية",
  "Ash Shifa": "حي الشفاء",
  "Ash Shihabiyah": "حي الشهابية",
  "Ash Shimasiyah": "الشماسية",
  "Ash Shinan": "الشنان",
  "Ash Shiqah": "حي الشقة",
  "Ash Shiyukh": "حي الشيوخ",
  "Ash Shrouk": "حي الشروق",
  "Ash Shuaib": "حي الشعيب",
  "Ash Shubaikah": "حي الشبيكة",
  "Ash Shuhada": "حي الشهداء",
  "Ash Shulah": "حي الشعلة",
  "Ash Shura": "حي الشورى",
  "Ash Shuraybat": "حي الشريبات",
  "Ash Shuruq": "حي الشروق",
  "Ash Shuruq Administrative": "حي الشروق الاداري",
  "Ash Shweikah": "حي الشويكة",
  "Asharai": "حي الشرائع",
  "Ashayra": "حي عشيرة",
  "Ashuhada Aljanubiyyah": "حي الشهداء الجنوبية",
  "Ashuhada Alshamaliyyah": "حي الشهداء الشمالية",
  "Assafarat": "حي السفارات",
  "At Taalim": "حي التعليم",
  "At Taawun": "حي التعاون",
  "At Tafeer": "حي الطفير",
  "At Tahemah": "بلدة التهيمية",
  "At Tahkim": "حي التحكيم",
  "At Tahliyah": "حي التحلية",
  "At Tahliyyah": "حي التحلية",
  "At Taif": "الطائف",
  "At Talaah": "حي الطلعة",
  "At Talal": "حي التلال",
  "At Talim": "حي التعليم",
  "At Tamor": "حي التمور",
  "At Tandabawi": "حي الطندباوي",
  "At Tanim": "حي التنعيم",
  "At Taqadom": "حي التقدم",
  "At Taqwa": "حي التقوى",
  "At Tarbil": "بلدة الطريبيل",
  "At Tarf": "بلدة الطرف",
  "At Tarwiyah": "حي التروية",
  "At Tashalih": "حي التشاليح",
  "At Tashlih": "حي التشليح",
  "At Tawbi": "حي التوبي",
  "At Taysir": "حي التيسير",
  "At Tif": "حي الطف",
  "At Tijari": "حي التجاري",
  "At Tubayshi": "حي الطبيشي",
  "At Tuwair": "حي الطوير",
  "Ath Thaalibah": "حي الثعالبة",
  "Ath Thaghr": "حي الثغر",
  "Ath Thuqbah": "حي الثقبة",
  "Ath Thuraiya": "حي الثريا",
  "Athaqafah": "حي الثقافة",
  "Atud": "حي عتود",
  "Auto Shredder": "حي تشليح السيارات",
  "Awdah": "حي عودة",
  "Ayn Al Khif": "حي عين الخيف",
  "Ayn Al Nawa": "حي عين النوى",
  "Ayn Marjan": "حي عين مرجان",
  "Ayn Musa": "حي عين موسى",
  "Ayn Najm": "حي عين نجم",
  "Ayn Shams": "حي عين شمس",
  "Az Zahir": "حي الزاهر",
  "Az Zahra": "حي الزهراء",
  "Az Zahrah": "حي الزهرة",
  "Az Zarah": "حي الزارة",
  "Az Zarqa": "حي الزرقاء",
  "Az Zaytun": "حي الزيتون",
  "Az Zibarah": "حي الزبارة",
  "Az Zomorod": "حي الزمرد",
  "Az Zour": "حي الزور",
  "Az Zugaibah": "حي الزغيبة",
  "Az Zuhur": "حي الزهور",
  "Az Zulfi": "الزلفي",
  "Az Zumorud": "حي الزمرد",
  "Bab As Sab": "حي باب الساب",
  "Bab Madinah Ash Shamal": "حي باب الشمال",
  "Badai Al Hawamilah": "بدائع الهواملة",
  "Badanah": "حي بدنة",
  "Badhaah": "حي بضاعة",
  "Badiah Al Basri": "حي بديعة البصري",
  "Badr": "حي بدر",
  "Bahjah": "حي بهجة",
  "Bahrah": "حي بحرة",
  "Banban": "حي بنبان",
  "Bani Abdul Ashhal": "حي بني عبدالاشهل",
  "Bani Al Najjar": "حى بني النجار",
  "Bani Bayadah": "حي بني بياضة",
  "Bani Dhafir": "حي بني ظفر",
  "Bani Harithah": "حي بني حارثة",
  "Bani Khidrah": "حي بني خدرة",
  "Bani Maan": "بلدة بني معن",
  "Bani Malik": "حي بنى مالك",
  "Bani Muawiyah": "حي بني معاوية",
  "Bani Salman": "حي بنى سلمان",
  "Bani Suhaym": "حي بني سهيم",
  "Baq'a": "بقعاء",
  "Baqa Al Qadima": "حي بقعاء القديمه",
  "Baqa Al Sharqia": "حي بقعاء الشرقيه",
  "Baqa Al Sharqia Al Qadima": "حي بقعاء الشرقيه القديمه",
  "Barak": "حي برك",
  "Barzah": "حي برزة",
  "Barzan": "حي برزان",
  "Batha Quraysh": "حي بطحاء قريش",
  "Bawdah": "حي هجرة بوضة",
  "Bay La Sun": "حي البيلسان",
  "Bilal": "حي بلال",
  "Biljurashi": "بلجرشي",
  "Billahmar": "بللحمر",
  "Billasmar": "بللسمر",
  "Bir Abayn": "حي بئر أبين",
  "Bir Uthman": "حي بئر عثمان",
  "Bishah": "بيشة",
  "Bonded And Reexport Zone": "منطقة الايداع واعادة التصنيع",
  "Border Guard Housing": "مهاجع حرس الحدود",
  "Border Guard Iskan": "حي إسكان حرس الحدود",
  "Bryman": "حي بريمان",
  "Buqayq": "بقيق",
  "Buraidah": "بريدة",
  "Butishah": "حي بوتيشة",
  "C 1": "حي ج1",
  "C 34": "حي ج 34",
  "C 35": "حي ج 35",
  "C1": "حي ج1",
  "C10": "حي ج10",
  "C11": "حي ج11",
  "C12": "حي ج12",
  "C13": "حي ج13",
  "C14": "حي ج14",
  "C15": "حي ج15",
  "C16": "حي ج16",
  "C17": "حي ج17",
  "C18": "حي ج18",
  "C19": "حي ج19",
  "C2": "حي ج2",
  "C20": "حي ج20",
  "C21": "حي ج21",
  "C22": "حي ج22",
  "C23": "حي ج23",
  "C24": "حي ج24",
  "C25": "حي ج25",
  "C26": "حي ج26",
  "C27": "حي ج27",
  "C28": "حي ج28",
  "C29": "حي ج29",
  "C3": "حي ج3",
  "C30": "حي ج30",
  "C31": "حي ج31",
  "C32": "حي ج32",
  "C33": "حي ج33",
  "C34": "حي ج34",
  "C35": "حي ج35",
  "C36": "حي ج36",
  "C37": "حي ج37",
  "C38": "حي ج38",
  "C39": "حي ج39",
  "C4": "حي ج4",
  "C40": "حي ج40",
  "C41": "حي ج41",
  "C43": "حي ج43",
  "C44": "حي ج44",
  "C5": "حي ج5",
  "C6": "حي ج6",
  "C7": "حي ج7",
  "C8": "حي ج8",
  "C9": "حي ج9",
  "Centeral Tandaha": "حي وسط تندحة",
  "City Center": "وسط المدينة",
  "Cordoba": "حي قرطبة",
  "Dahdah": "حي دحضة",
  "Dahiyat Al Malik Fahd": "حي ضاحية الملك فهد",
  "Dahiyat King Fahd": "حي ضاحية الملك فهد",
  "Dahiyat Namar": "حي ضاحية نمار",
  "Dahiyat Prince Sultan Northern": "حي ضاحية الامير سلطان الشمالية",
  "Dahiyat Prince Sultan Southern": "حي ضاحية الامير سلطان الجنوبية",
  "Damak": "حي ضمك",
  "Dammam": "الدمام",
  "Damshiah": "حي دمشية",
  "Dana": "حي الدانة",
  "Darin": "حي دارين",
  "Dariyah": "ضرية",
  "Dawmat Al Jandal": "دومة الجندل",
  "Dhaea": "حي ضعة",
  "Dhahban Town": "حي بلدة ذهبان",
  "Dhahiyat Al Iskan": "حي ضاحية الاسكان",
  "Dhahiyat Al Iskan Extension Area": "منطقة إمتداد ضاحية الإسكان",
  "Dhahran": "الظهران",
  "Dhahran Al Janub": "ظهران الجنوب",
  "Dhahrat Al Badeah": "حي ظهرة البديعة",
  "Dhahrat Laban": "حي ظهرة لبن",
  "Dhalalah": "حي ذلالة",
  "Dhu Al Hulayfah": "حي ذو الحليفة",
  "Dhurah": "حي ذرة",
  "Dirab": "حي ديراب",
  "Down Town": "البلدة القديمة",
  "Duba": "ضبا",
  "Duruma": "ضرما",
  "East Airport A": "حي شرق المطار أ",
  "East Airport B": "حي شرق المطار ب",
  "East Airport C": "حي شرق المطار ج",
  "East Airport D": "حي شرق المطار د",
  "East Al Faisaliyah": "حي الفيصلية شرق",
  "East Al Uwayqilah City Subdivision Plan": "مخطط شرق مدينة العويقيلة",
  "East Darah": "حي شرق الدارة",
  "East Dhahrat Al Oudah": "حي ظهرة العودة شرق",
  "East Naseem": "حي النسيم الشرقي",
  "East Rajla": "حي شرق رجلا",
  "East Shuabah": "حي الشعبة الشرقية",
  "East Umm Al Hamam": "حي ام الحمام الشرقي",
  "Eastern Dhahban": "حي ذهبان الشرقى",
  "Eawanah": "عوانه",
  "Education Administration": "ادارة التعليم",
  "Entaj": "حي الإنتاج",
  "Faidat Aban Alahmar": "فيضة ابان الاحمر",
  "Faidat Al Salamat": "فيضة السلمات",
  "Faisaliyah North": "حي الفيصلية الشمالية",
  "Faisaliyah South": "حي الفيصلية الجنوبية",
  "Fawaz": "حي فواز",
  "Faydat Al Fawazin": "حي فيضة الفوازين",
  "Faza": "حي فازع",
  "Fulaij": "حي فليج",
  "Gamsy": "بلدة غمسي",
  "Gaslah": "حي غسلة",
  "Ghalil": "حي غليل",
  "Gharan": "غران",
  "Gharb Adh Dhahran": "حي غرب الظهران",
  "Gharb An Nabiyah": "حي غرب النابية",
  "Ghaziyyat": "حي غزيات",
  "Ghirnatah": "حي غرناطة",
  "Ghirnatah Eastern": "حي غرناطة الشرقي",
  "Ghirnatah Wesrtern": "حي غرناطة الغربي",
  "Ghobairah": "حي غبيرة",
  "Ghorab": "حي غراب",
  "Ghulail": "حي غليل",
  "Ghusaiba": "حي غصيبة",
  "Ghuwayla A": "حي الغويلا أ",
  "Ghuwayla C": "حي الغويلا ج",
  "Ghuwayla D": "حي الغويلا د",
  "Goverment Departments": "حي الدوائر الحكومية",
  "Government Departments": "حي الدوائر الحكوميه",
  "Government Departments Area A": "الدوائر الحكومية أ",
  "Government Departments Area B": "الدوائر الحكومية ب",
  "Government Departments Area C": "الدوائر الحكومية ج",
  "Government Departments Area D": "الدوائر الحكومية د",
  "Government Departments Area E": "الدوائر الحكومية هـ",
  "Government Departments Area F": "الدوائر الحكومية و",
  "Government Departments Complex": "مجمع الدوائر الحكومية",
  "Government Departments Complex 1st": "حي مجمع الدوائر الحكومية الأول",
  "Government Departments Complex 2nd": "حي مجمع الدوائر الحكومية الثاني",
  "Governmental": "حكومي",
  "Haddaj": "حي هداج",
  "Hadera": "حي الخضيرة",
  "Hadhawda": "حى حضوضاء",
  "Hadraj": "حي حدرج",
  "Hadri Al Bilad": "حي حدري البلاد",
  "Hafair Al Eahin Al Gharbi": "حي حفاير العهين الغربي",
  "Hafair Al Eahin Al Sharqi": "حي حفاير العهين الشرقي",
  "Hafar Al Batin": "حفر الباطن",
  "Hafira Al Sabaa Al Gharbi": "حي حفيرة السبعة الغربي",
  "Hafira Al Sabaa Al Shamali": "حي حفيرة السبعة الشمالي",
  "Hail": "حائل",
  "Hail International Airport": "مطار حائل الدولي",
  "Hajr": "حي هجر",
  "Hajr 10th": "حي هجر العاشر",
  "Hajr 11th": "حي هجر الحادي عشر",
  "Hajr 12th": "حي هجر الثاني عشر",
  "Hajr 1st": "حي هجر الأول",
  "Hajr 2nd": "حي هجر الثاني",
  "Hajr 3rd": "حي هجر الثالث",
  "Hajr 4th": "حي هجر الرابع",
  "Hajr 5th": "حي هجر الخامس",
  "Hajr 6th": "حي هجر السادس",
  "Hajr 7th": "حي هجر السابع",
  "Hajr 8th": "حي هجر الثامن",
  "Hajr 9th": "حي هجر التاسع",
  "Hakimat Abi Arish": "حي حاكمة ابي عريش",
  "Hakimat Al Dagharir": "حي حاكمة الدغارير",
  "Hakimiat Al Iz": "حي حكامية العز",
  "Halah Abdullah Qabea": "حله عبدالله قبع",
  "Halah Abu Marei": "حله ابو مرعي",
  "Halah Al Hukmaa": "حله الحكمى",
  "Halah Al Kalabih": "حله الكلابيه",
  "Halah Al Qamiri": "حله القميري",
  "Halah Al Sahluli": "حله الصهلولي",
  "Halah Aleaqibiu": "حله العقيبي",
  "Halah Alhawa Tyn": "حله الحو تين",
  "Halah Attieh": "حله عطيه",
  "Halah Bin Alwaan": "حله بن علوان",
  "Halah Maruei Bin Shamy": "حله مروعي بن شامي",
  "Halah Mishary": "حله مشاري",
  "Halah Muhamad Eisa": "حله محمد عيسى",
  "Halah Muhsin Al Muhasana": "حله محسنالمحاسنة",
  "Halat Mahish": "حي حلة محيش",
  "Hanaqfah": "حنقفه",
  "Haql": "حقل",
  "Harat Al Bab And Ash Shamiyah": "حي حارة الباب والشامية",
  "Hareer": "حي الحرير",
  "Harmah": "حرمة",
  "Hawtat Bani Tamim": "حوطة بني تميم",
  "Hawtat Sudair": "حوطة سدير",
  "Hazm": "حي حزم",
  "Hazrat Al Janoub": "حي حزرة الجنوب",
  "Hejaz": "حي الحجاز",
  "Hijrat Bin Saeed": "حي هجرة ابن سعيد",
  "Historical Center Al Mubarraz": "حي وسط المبرز التاريخي",
  "Hiteen": "حي حطين",
  "Hubuna": "حي حبونا",
  "Hulat Abu Habibuh": "حلة ابو حبيبه",
  "Hulat Al Earshi": "حلة العرشي",
  "Hulat Al Makki": "حلة المكي",
  "Hulat Ali Bin Musa": "حلة علي بن موسى",
  "Hulat Iibrahim Eisaa": "حلة ابراهيم عيسى",
  "Hullat Al Ahwass": "حي حلة الأحوس",
  "Hura Al Wabra": "حى حرة الوبرة",
  "Huraymila": "حريملاء",
  "Husaydah": "حي حصيدة",
  "Huwailan": "حي حويلان",
  "Huwaya Al Janoubiyah": "حي حوايا الجنوبية",
  "Huwaya Ash Shamaliyyah": "حي حوايا الشمالية",
  "Hyt": "حي هيت",
  "Ibn Khaldun": "حي ابن خلدون",
  "Ibn Sina": "حي ابن سيناء",
  "Idman": "حي ادمان",
  "Imam Muhammed Bin Saud Islamic University": "جامعة الامام محمد بن سعود الاسلامية",
  "Imam Muhammed Ibn Saud Islamic University": "جامعة الامام محمد بن سعود الاسلامية",
  "Industrial": "حي الصناعية",
  "Industrial Area": "المنطقة الصناعية",
  "Industrial Area Phase 2 And 3": "المنطقة الصناعية المرحلة الثانية والثالثة",
  "Industrial City": "حي المدينة الصناعية",
  "Inkas": "حي انكاس",
  "Irqah": "عرقة",
  "Ishbiliya": "حي اشبيليا",
  "Ishbiliyah": "حي اشبيلية",
  "Ishbiliyah Northern": "حي اشبيلية الشمالي",
  "Ishbiliyah Southern": "حي اشبيلية الجنوبي",
  "Jabal An Nur": "حي جبل النور",
  "Jabal Ayr": "حي جبل عير",
  "Jabal Uhud": "حي جبل احد",
  "Jabrah": "حي جبرة",
  "Jalajil": "جلاجل",
  "Jalmudah": "حي جلمودة",
  "Jameema": "جميما",
  "Janub Al Mustashfa Al Askari": "حي جنوب المستشفى العسكري",
  "Janub Nimrah": "مخطط جنوب نمره",
  "Janub Yadamah": "حي جنوب يدمة",
  "Jaranah": "حي جعرانة",
  "Jareer": "حي جرير",
  "Jarham": "حي جرهم",
  "Jaribuh": "جريبه",
  "Jarwal": "حي جرول",
  "Jawatha": "جواثا",
  "Jawharat Al Kharj": "حي جوهرة الخرج",
  "Jazan": "جازان",
  "Jeddah": "جدة",
  "Jeddah Eslamic Seaport": "ميناء جدة الاسلامي",
  "Jima Um Khalid": "حي جماء أم خالد",
  "Josham": "حي جشم",
  "Juba": "حي جوبا",
  "Jukhairah": "حي جخيرة",
  "Julijlah": "بلدة جليجلة",
  "Juman": "حي جمان",
  "Juwatha": "حي جواثا",
  "Kamirah": "حي قامرة",
  "Kara As Sardi": "حي كرا السردي",
  "Katanah": "حي كتانة",
  "Khakh": "حي خاخ",
  "Khalab": "حي خلب",
  "Khalidiyah West": "حي غرب الخالدية",
  "Khamis Mushayt": "خميس مشيط",
  "Khashm Al An": "خشم العان",
  "Khaybar": "خيبر",
  "Khazma": "حي خذماء",
  "Khub Al Buraydi": "حي خب البريدي",
  "Khub Ath Thanyan": "حي خب الثنيان",
  "Khudar": "حي خضار",
  "Khudayra": "حي خضيراء",
  "Khulays": "خليص",
  "Khusayyibah": "حي خصيبة",
  "King Abdul Aziz Seaport": "حي ميناء الملك عبدالعزيز",
  "King Abdulaziz": "حي الملك عبدالعزيز",
  "King Abdulaziz International Airport": "مطار الملك عبدالعزيز الدولي",
  "King Abdulaziz University": "جامعة الملك عبدالعزيز",
  "King Abdullah": "حي الملك عبدالله",
  "King Abdullah City For Energy": "مدينة الملك عبدالله للطاقة",
  "King Abdullah Economic City": "مدينة الملك عبدالله الاقتصادية",
  "King Abdullah Military City": "مدينة الملك عبدالله العسكرية",
  "King Abdullah Port": "حي ميناء الملك عبد الله",
  "King Abdullah University Of Science And Technology": "جامعة الملك عبدالله للعلوم والتقنية",
  "King Fahd": "حي الملك فهد",
  "King Fahd International Airport": "مطار الملك فهد الدولي",
  "King Fahd University Of Petroleum And Minerals": "جامعة الملك فهد للبترول والمعادن",
  "King Faisal": "حي الملك فيصل",
  "King Faisal Naval Base": "قاعدة الملك فيصل البحرية",
  "King Faisal University": "مدينة الملك فيصل الجامعية",
  "King Faisal University 1st": "حي جامعة الملك فيصل الأول",
  "King Faisal University 2nd": "حي جامعة الملك فيصل الثاني",
  "King Faisal University 3rd": "حي جامعة الملك فيصل الثالث",
  "King Khalid": "حي الملك خالد",
  "King Khalid International Airport": "مطار الملك خالد",
  "King Salman": "حي الملك سلمان",
  "King Salman Energy Park": "مدينة الملك سلمان للطاقة",
  "King Saud": "حي الملك سعود",
  "King Saud University": "جامعة الملك سعود",
  "Kittanah": "حي كتانة",
  "Kofat": "كفت",
  "Kuaykib": "حي كويكب",
  "Kudy": "حي كدي",
  "Kuwaikib": "حي الكويكب",
  "Laban": "حي لبن",
  "Labdah": "حي لبدة",
  "Ladhah": "حي لذه",
  "Lagoon Preserved Area": "منطقة البحيرة المحمية",
  "Layla": "ليلى",
  "Light Industrial Park": "منطقة الصناعات الخفيفة",
  "Limas": "حي ليماس",
  "Maaelah": "حي معيلة",
  "Maashi": "حي معشي",
  "Madain Al Fahd": "حي مدائن الفهد",
  "Madina Al Hojaj": "حي مدينة الحجاج",
  "Madina At Tomor": "حي مدينة التمور",
  "Madinah": "المدينة المنورة",
  "Madinat Al Ummal": "حي مدينة العمال",
  "Mahairis": "حي محيرس",
  "Mahasin 1st": "حي محاسن الأول",
  "Mahasin 2nd": "حي محاسن الثاني",
  "Mahasin Aramco 1st": "حي محاسن ارامكو الأول",
  "Mahasin Aramco 2nd": "حي محاسن ارامكو الثاني",
  "Mahasin Aramco 3rd": "حي محاسن ارامكو الثالث",
  "Mahasin Aramco 4th": "حي محاسن ارامكو الرابع",
  "Mahasin Aramco 5th": "حي محاسن ارامكو الخامس",
  "Mahd Adh Dhahab": "مهد الذهب",
  "Majaar": "حي مجعر",
  "Makkah": "مكة المكرمة",
  "Manfuha Al Jadidah": "حي منفوحة الجديدة",
  "Manfuhah": "حي منفوحة",
  "Mansih": "منسيه",
  "Mansubi Al Taleem 1st": "حي منسوبي التعليم الأول",
  "Mansubi Al Taleem 2nd": "حي منسوبي التعليم الثاني",
  "Mansuriyah": "حي المنصورية",
  "Marbidah": "حي مربيدة",
  "Margh": "حي مرخ",
  "Markaz Al Shararh": "حي مركز الشرارة",
  "Masarah 1": "حي مسرة 1",
  "Masarah 2": "حي مسرة 2",
  "Mashreq": "حي المشرق",
  "Masjid Ad Dara": "حي مسجد الدرع",
  "Masloum": "حي مصلوم",
  "Masmla": "حي مثمله",
  "Maysan": "حي ميسان",
  "Mayyas": "حي مياس",
  "Meakal": "حي معكال",
  "Middle Oraija": "حي العريجاء الوسطى",
  "Milhi": "حي ملهي",
  "Military City": "المدينة العسكرية",
  "Military City Housing": "سكن المدينة العسكرية",
  "Military College": "الكلية الحربية",
  "Military School": "حي المدرسة العسكرية",
  "Mishrif": "حي مشرف",
  "Mishrifah": "حي مشرفة",
  "Mishrifat Amudan": "مشرفة عمودان",
  "Mizhirah": "حي مزهرة",
  "Mlihah": "حي مليحة",
  "Mraykh": "حي مريخ",
  "Mshrif": "حي مشرف",
  "Mughaydah": "حي مغيضة",
  "Muhayil": "محايل",
  "Munif": "حي منيف",
  "Munifah": "حي منيفة",
  "Muntazah": "حي منتزه",
  "Muqabil": "حي مقابل",
  "Murjan": "حي المرجان",
  "Murooj": "حي المروج",
  "Musaddah": "حي مصده",
  "Mustaqbal": "حي المستقبل",
  "Muthalath Asharqiyah": "حي مثلث الشرقية",
  "Nadi Al Forosiyah": "حي نادي الفروسية",
  "Nahiqah": "حي نهيقة",
  "Nahuqah": "حي نهوقة",
  "Najd": "حي نجد",
  "Najmah": "حي نجمة",
  "Najran": "نجران",
  "Najran University": "جامعة نجران",
  "Nakhab": "حي نخب",
  "Namar": "حي نمار",
  "Nashwan": "حي نشوان",
  "National Guard": "الحرس الوطني",
  "National Guard Property": "أملاك الحرس الوطني",
  "Nawarah": "حي نواره",
  "Nazwa": "حي نزوى",
  "New Industrial": "حي الصناعية الجديدة",
  "New International Airport": "المطار الدولي الجديد",
  "New Taif University": "جامعة الطائف الجديدة",
  "Nifi": "نفي",
  "Nimra Al Mukhatat": "حي نمره المخطط",
  "No 1": "حي رقم 1",
  "No 2": "حي رقم 2",
  "No 3": "حي رقم 3",
  "No 4": "حي رقم 4",
  "No 5": "حي رقم 5",
  "No 6": "حي رقم 6",
  "No 7": "حي رقم 7",
  "No 8": "حي رقم 8",
  "No 9": "حي رقم 9",
  "No10": "حي رقم 10",
  "North Mathar": "حي المعذر الشمالي",
  "North Mishaliyah": "حي المشعلية الشمالية",
  "North Rajla": "حي رجلا الشماليـة",
  "North Shurfah": "حي الشرفة الشمالية",
  "North Tandaha": "حي شمال تندحة",
  "Northern Border University": "جامعة الحدود الشمالية",
  "Nubala": "حي نبلاء",
  "Nurah": "نورة",
  "Nursun": "حي نورسان",
  "Ofoq": "حي الأفق",
  "Ohod": "حي احد",
  "Okaz": "حي عكاظ",
  "Olaishah": "حي عليشة",
  "Olaya": "العليا",
  "Old Industrial": "حي الصناعية القديمة",
  "Oraid": "حي عريض",
  "Oraifi Industrial": "حي صناعية العريفي",
  "Petromin": "حي بترومين",
  "Prince Abdul Majeed": "حي الامير عبدالمجيد",
  "Prince Abdulellah Bin Abdulaziz": "حي الامير عبدالاله بن عبدالعزيز",
  "Prince Fahd Ibn Salman": "حي الامير فهد بن سلمان",
  "Prince Mishal": "حي الامير مشعل",
  "Prince Muhammed Ibn Saud": "حي الامير محمد بن سعود",
  "Prince Naif": "حي الامير نايف",
  "Prince Sultan": "حي الامير سلطان",
  "Prince Sultan Air Base": "قاعدة الامير سلطان الجوية",
  "Prince Sultan Bin Abdulaziz International Airport": "مطــار الامير سلطان بن عبدالعزيز الدولي",
  "Private Area": "منطقة خاصة",
  "Qambar": "حي قمبر",
  "Qami": "حي القميع",
  "Qaryan": "حي قريان",
  "Qaryat Al 'Ulya": "قرية العليا",
  "Qaryat Al Jabnon": "حي قرية الجبنون",
  "Qaryat Al Jawabirih": "قرية الجوابره",
  "Qasr Aali": "حي قصر عالي",
  "Qasr Al Khalij": "حي قصر الخليج",
  "Qasr Ibn Aqil": "حي قصر بن عقيل",
  "Qfaar": "حي قفار",
  "Qibah": "قبة",
  "Qouz Al Jaafrah": "قوز الجعافره",
  "Quba": "حي قباء",
  "Qubeiba": "حى القبيبة",
  "Qubeiban": "حي قبيبان",
  "Qurban": "حي قربان",
  "Qurtubah": "حي قرطبة",
  "Qurwa": "حي قروى",
  "Quwaiyyah": "حي قويعية",
  "Rabigh": "رابغ",
  "Rabwat Al Hajeb": "حي ربوة الحاجب",
  "Radwa": "حي رضوى",
  "Rafha'": "رفحاء",
  "Raht": "حي رهط",
  "Ramat": "حي رامات",
  "Ranyah": "رنية",
  "Ras Tannurah": "راس تنورة",
  "Raseel": "حي رسيل",
  "Rawaq": "حي رواق",
  "Ray Zakhir": "حي ريع زاخر",
  "Rayman": "حي ريمان",
  "Reetan": "حي ريتان",
  "Rest House Area": "منطقة الاستراحات",
  "Riha": "حي ريحه",
  "Rise": "حي رايس",
  "Riyad Al Khabra": "رياض الخبراء",
  "Riyadh": "الرياض",
  "Ruwad": "حي الرواد",
  "Saaghir": "حي صاغر",
  "Sababah": "حي صبابة",
  "Sabt Al 'Alayah": "سبت العلاية",
  "Sabya": "صبيا",
  "Sad Al Ghaba": "حى سد الغابة",
  "Sadr Al Gharbaiyah": "حي صدر الغربية",
  "Safwa": "صفوى",
  "Safwan": "حي صفوان",
  "Sahara": "حي صحارى",
  "Sahban": "حي صهبان",
  "Sahifat": "حي صحيفات",
  "Sakaka": "سكاكا",
  "Salahuddin": "حي صلاح الدين",
  "Salahuddin Al Sharqi": "حي صلاح الدين الشرقي",
  "Salam": "حي سلام",
  "Salam Park": "منتزه سلام",
  "Salwa": "حي سلوى",
  "Samah": "حي سماح",
  "Samdah": "حي صمدة",
  "Samtah": "حي صامطة",
  "Sanabis": "حي سنابس",
  "Saq": "حي ساق",
  "Saqrah": "حي صقرة",
  "Saqrah Northern": "حي صقرة الشمالي",
  "Sarat Abidah": "سراة عبيدة",
  "Saudi Arabia": "المملكة العربية السعودية",
  "Sayhat": "سيهات",
  "Sayl Al Dalhimiyah": "حي سيل الدلهمية",
  "Sea Front": "الواجهة البحرية",
  "Security Forces Housing": "حي اسكان قوى الأمن",
  "Sedr": "حي سدر",
  "Semnan": "حي سمنان",
  "Shaab Dhahban": "حي شعب ذهبان",
  "Shahbah": "حي شهبة",
  "Shahdah": "شهده",
  "Shaib Amir And Shaib Ali": "حي شعب عامر وشعب علي",
  "Shakar": "حي شكر",
  "Shamal At Tadamun": "حي شمال التضامن",
  "Shamsan": "حي شمسان",
  "Shaqra'": "شقراء",
  "Sharai Al Mujahidin": "حي شرائع المجاهدين",
  "Sharqia": "حي الشرقية",
  "Sharurah": "شرورة",
  "Shateebah": "حي الشطيبة",
  "Shayban": "شيبان",
  "Shiab Reer": "حي شعب رير",
  "Shidhat": "حي شظاة",
  "Shihar": "حي شهار",
  "Shiraf": "حي شراف",
  "Shobra": "حي شبرا",
  "Shokor": "حي شكر",
  "Shuab Bran": "حي شعب بران",
  "Shubaah": "حي شباعة",
  "Shubra": "حي شبرا",
  "Shukhib": "حي شخيب",
  "Shuran": "حي شوران",
  "Sikkah Al Hadid": "حي سكة الحديد",
  "Sinaiyah Al Fawaziyah": "حي صناعية الفوازية",
  "Sinaiyah Ath Thuqbah": "حي صناعية الثقبة",
  "Sinaiyat Al Hadidiyah": "حي صناعية الحديدية",
  "Siyah": "حي صياح",
  "Skirinah": "حي سكيرينة",
  "Snam": "حي سنام",
  "South Mishaliyah": "حي المشعلية الجنوبية",
  "South Of University": "حي جنوب الجامعة",
  "South Rajla": "حي رجلا الجنوبية",
  "South Shurfah": "حي الشرفة الجنوبية",
  "South Tandaha": "حي جنوب تندحة",
  "Southern Districts": "الأحياء الجنوبية",
  "Sports City": "المدينة الرياضية",
  "Sports Stadium": "الاستاد الرياضي",
  "Subdivision Plan 1c": "مخطط ج1",
  "Subdivision Plan 2c": "مخطط ج2",
  "Subdivision Plan 3c": "مخطط ج3",
  "Subdivision Plan 4c": "مخطط ج4",
  "Subdivision Plan A": "مخطط ا",
  "Subdivision Plan B": "مخطط ب",
  "Sudair Industrial And Business City": "مدينة سدير للصناعة والأعمال",
  "Sudayr": "حي سدير",
  "Sudayrah": "حي سديرة",
  "Sultanah": "حي سلطانة",
  "Suq Al Mashiya": "حي سوق الماشية",
  "Suq Mashiya Al Jadid": "حي سوق الماشيه الجديد",
  "Suq Ukadh": "حي سوق عكاظ",
  "Suqam": "حي سقام",
  "Suwayr": "صوير",
  "Tabab": "طبب",
  "Tabah": "حي طابة",
  "Tabuk": "تبوك",
  "Taibah": "حى طيبة",
  "Talah": "حي التالة",
  "Tanmiyah": "حي التنمية",
  "Tanumah": "تنومة",
  "Tara": "حي تارة",
  "Tarib": "طريب",
  "Tarut": "تاروت",
  "Tathlith": "تثليث",
  "Taybah": "حي طيبة",
  "Tayib Al Ism": "حي طيب الاسم",
  "Tayma'": "تيماء",
  "Tebah": "حي طيبة",
  "Telal Arar": "حي تلال عرعر",
  "Tendaha": "تندحة",
  "Thadiq": "ثادق",
  "Thasallal": "حي تصلال",
  "Thulaim": "حي ثليم",
  "Thuwal": "حي ثول",
  "Tihamah": "حي تهامة",
  "Tubarjal": "طبرجل",
  "Tumair": "تمير",
  "Tumair Industrial": "حي صناعية تمير",
  "Turaif": "طريف",
  "Turbah": "تربه",
  "Tuwaiq": "حي طويق",
  "Tuwik": "حي طويق",
  "Tyhan (Hulat Tyhan)": "تيهان (حلة تيهان)",
  "Uhd": "حي احد",
  "Uhud": "حي احد",
  "Um Al Dayan": "حي ام الضيان",
  "Um Al Hamam": "حي ام الحمام",
  "Um Al Seouf": "حي ام السيوف",
  "Um Anam": "حي ام عنم",
  "Um Asalam": "حي ام السلم",
  "Um Hableen Al Gharbiyyah": "حي أم حبلين الغربية",
  "Um Hableen Al Sharqiyyah": "حي أم حبلين الشرقية",
  "Um Khraisan": "حي ام خريسان",
  "Um Talha": "حي ام طلحة",
  "Umluj": "املج",
  "Umm Al Hamam": "ام الحمام",
  "Umm Al Jazm": "حي ام الجزم",
  "Umm Al Qahfah": "ام القحفه",
  "Umm Al Shaal": "حي ام الشعال",
  "Umm Al Shibaqa": "ام الشباقاء",
  "Umm Alarad": "حي أم العراد",
  "Umm Alearsh": "ام العرش",
  "Umm As Sahik": "حي ام الساهك",
  "Umm Sabah": "حي أم سبعة",
  "Umm Saleem": "حي ام سليم",
  "Umm Surur": "حي ام سرور",
  "Umm Thalaah": "حي ام ثلعة",
  "Umm Ushayrah": "حي ام عشيرة",
  "Unayzah": "عنيزة",
  "University City": "المدينة الجامعية",
  "Uqaz": "حي عكاظ",
  "Uqlat As Suqur": "عقلة الصقور",
  "Urierah": "حي عريعرة",
  "Urwah": "حي عروة",
  "Utayqah": "حي عتيقة",
  "Uyun Al Jawa'": "عيون الجواء",
  "Wadi Ad Dawasir": "وادي الدواسر",
  "Wadi Al Battan": "حي وادي البطان",
  "Wadi Al Hamdh": "حي وادي الحمض",
  "Wadi Ar Rimma": "حي وادي الرمة",
  "Wadi Jalil": "حي وادي جليل",
  "Wadi Mahzur": "حي وادي مهزور",
  "Wadi Mudhainib": "حي وادي مذينب",
  "Wady Laban": "حي وادي لبن",
  "Wairah": "حي وعيرة",
  "Wajah Alhasan": "وجه الحسن",
  "Waly Al Ahd": "حي ولي العهد",
  "Warehouse": "حي المستودعات",
  "Warehouse Area": "منطقة المستودعات",
  "Warqan": "حي ورقان",
  "Waselah": "حي وسيلة",
  "Wasit": "حي واسط",
  "Wassat Al Oyon": "وسط العيون",
  "West Al Faisaliyah": "حي الفيصلية غرب",
  "West Dawmat Al Jandal": "حي غرب دومة الجندل",
  "West Dhahrat Al Oudah": "حي ظهرة العودة غرب",
  "West Naseem": "حي النسيم الغربي",
  "West Oraija": "حي العريجاء الغربي",
  "West Shuabah": "حي الشعبة الغربية",
  "West Shurfah": "حي الشرفة الغربية",
  "West Suwaidi": "حي السويدي الغربي",
  "West Umm Al Hamam": "حي ام الحمام الغربي",
  "Western Dhahban": "حي ذهبان الغربى",
  "Yabrin / Jabrin": "يبرين",
  "Yadamah": "يدمة",
  "Yadamah Al Awal": "حي يدمة الاول",
  "Yadamah Al Thani": "حي يدمة الثاني",
  "Yanbu": "ينبع",
  "Yanbu Al Balad": "حي ينبع البلد",
  "Yanbu Al Sinaiyah": "ينبع الصناعية",
  "Yebrin": "حي يبرين",
  "Zamiqa": "حي زميقة",
  "Zarabah": "زربه",
  "Zawr Al Ammari": "حي زور العماري",
  "Zawr Al Harith": "حي زور الحارث",
  "Zawr Wadiah": "حي زور وادعة",
  "Ziyad": "حي زياد",
  "Zubaiydah": "حي زبيدة",
  "Zubarah Al Jidyeen": "زباره الجديين",
};
